/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite Runner API
 * BoxLite Runner API
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

import type { ContainerCapabilitiesDTO } from './container-capabilities-dto';

export interface AdvancedBoxOptionsDTO {
    'capabilities': ContainerCapabilitiesDTO;
}
