/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite Runner API
 * BoxLite Runner API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EnumsBoxState } from './enums-box-state';

export interface BoxInfoResponse {
    'daemonVersion'?: string;
    /**
     * ExitCode is the main command\'s exit code, present only when the box stopped because that command exited. Absence, not 0, is what says \"not recorded\": 0 is the exit code of every command that succeeded, so a reader has to tell a missing field from a zero one.
     */
    'exitCode'?: number;
    'state'?: EnumsBoxState;
}



