/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite Runner API
 * BoxLite Runner API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * DiskIoLimitsDTO caps a box\'s disk I/O: bandwidth in bytes per second and operations per second, each per direction. A zero or omitted field is unlimited. Mirrors BoxOptions.disk_io in the runtime.
 * @export
 * @interface DiskIoLimitsDTO
 */
export interface DiskIoLimitsDTO {
    'readBps'?: number;
    'readIops'?: number;
    'writeBps'?: number;
    'writeIops'?: number;
}

