/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite Runner API
 * BoxLite Runner API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface DtoVolumeDTO {
    'mountPath'?: string;
    /**
     * ReadOnly binds the volume (or its Subpath) into the box read-only. Omitted on the wire means read-write, so an older API that never sends it keeps today\'s behaviour.
     */
    'readOnly'?: boolean;
    'subpath'?: string;
    'volumeId'?: string;
}

