/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { TopUpCheckoutDto } from '../models';
// @ts-ignore
import type { TopUpRequestDto } from '../models';
// @ts-ignore
import type { WalletResponseDto } from '../models';
/**
 * BillingApi - axios parameter creator
 */
export const BillingApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         *
         * @summary Get the organization\'s wallet balance + billing status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWallet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/billing/wallet`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Start a manual wallet top-up (returns a checkout URL)
         * @param {TopUpRequestDto} topUpRequestDto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        topUpWallet: async (topUpRequestDto: TopUpRequestDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'topUpRequestDto' is not null or undefined
            assertParamExists('topUpWallet', 'topUpRequestDto', topUpRequestDto)
            const localVarPath = `/billing/wallet/top-up`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2 required

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(topUpRequestDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * BillingApi - functional programming interface
 */
export const BillingApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = BillingApiAxiosParamCreator(configuration)
    return {
        /**
         *
         * @summary Get the organization\'s wallet balance + billing status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getWallet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WalletResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getWallet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BillingApi.getWallet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary Start a manual wallet top-up (returns a checkout URL)
         * @param {TopUpRequestDto} topUpRequestDto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async topUpWallet(topUpRequestDto: TopUpRequestDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TopUpCheckoutDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.topUpWallet(topUpRequestDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BillingApi.topUpWallet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * BillingApi - factory interface
 */
export const BillingApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = BillingApiFp(configuration)
    return {
        /**
         *
         * @summary Get the organization\'s wallet balance + billing status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWallet(options?: RawAxiosRequestConfig): AxiosPromise<WalletResponseDto> {
            return localVarFp.getWallet(options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Start a manual wallet top-up (returns a checkout URL)
         * @param {TopUpRequestDto} topUpRequestDto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        topUpWallet(topUpRequestDto: TopUpRequestDto, options?: RawAxiosRequestConfig): AxiosPromise<TopUpCheckoutDto> {
            return localVarFp.topUpWallet(topUpRequestDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * BillingApi - object-oriented interface
 */
export class BillingApi extends BaseAPI {
    /**
     *
     * @summary Get the organization\'s wallet balance + billing status
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getWallet(options?: RawAxiosRequestConfig) {
        return BillingApiFp(this.configuration).getWallet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Start a manual wallet top-up (returns a checkout URL)
     * @param {TopUpRequestDto} topUpRequestDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public topUpWallet(topUpRequestDto: TopUpRequestDto, options?: RawAxiosRequestConfig) {
        return BillingApiFp(this.configuration).topUpWallet(topUpRequestDto, options).then((request) => request(this.axios, this.basePath));
    }
}
