/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { BoxAccessGrant } from '../models';
// @ts-ignore
import type { BoxAccessGrantCreated } from '../models';
// @ts-ignore
import type { CreateBoxAccessGrant } from '../models';
/**
 * BoxAccessGrantApi - axios parameter creator
 */
export const BoxAccessGrantApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a box-scoped access grant
         * @param {string} boxIdOrName ID or name of the box
         * @param {CreateBoxAccessGrant} createBoxAccessGrant 
         * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createBoxAccessGrant: async (boxIdOrName: string, createBoxAccessGrant: CreateBoxAccessGrant, xBoxLiteOrganizationID?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'boxIdOrName' is not null or undefined
            assertParamExists('createBoxAccessGrant', 'boxIdOrName', boxIdOrName)
            // verify required parameter 'createBoxAccessGrant' is not null or undefined
            assertParamExists('createBoxAccessGrant', 'createBoxAccessGrant', createBoxAccessGrant)
            const localVarPath = `/box/{boxIdOrName}/access-grants`
                .replace('{boxIdOrName}', encodeURIComponent(String(boxIdOrName)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication oauth2 required

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            if (xBoxLiteOrganizationID != null) {
                localVarHeaderParameter['X-BoxLite-Organization-ID'] = String(xBoxLiteOrganizationID);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createBoxAccessGrant, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List box-scoped access grants
         * @param {string} boxIdOrName ID or name of the box
         * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listBoxAccessGrants: async (boxIdOrName: string, xBoxLiteOrganizationID?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'boxIdOrName' is not null or undefined
            assertParamExists('listBoxAccessGrants', 'boxIdOrName', boxIdOrName)
            const localVarPath = `/box/{boxIdOrName}/access-grants`
                .replace('{boxIdOrName}', encodeURIComponent(String(boxIdOrName)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication oauth2 required

            localVarHeaderParameter['Accept'] = 'application/json';

            if (xBoxLiteOrganizationID != null) {
                localVarHeaderParameter['X-BoxLite-Organization-ID'] = String(xBoxLiteOrganizationID);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Revoke a box-scoped access grant
         * @param {string} boxIdOrName ID or name of the box
         * @param {string} grantId ID of the access grant to revoke
         * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        revokeBoxAccessGrant: async (boxIdOrName: string, grantId: string, xBoxLiteOrganizationID?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'boxIdOrName' is not null or undefined
            assertParamExists('revokeBoxAccessGrant', 'boxIdOrName', boxIdOrName)
            // verify required parameter 'grantId' is not null or undefined
            assertParamExists('revokeBoxAccessGrant', 'grantId', grantId)
            const localVarPath = `/box/{boxIdOrName}/access-grants/{grantId}`
                .replace('{boxIdOrName}', encodeURIComponent(String(boxIdOrName)))
                .replace('{grantId}', encodeURIComponent(String(grantId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication oauth2 required


            if (xBoxLiteOrganizationID != null) {
                localVarHeaderParameter['X-BoxLite-Organization-ID'] = String(xBoxLiteOrganizationID);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * BoxAccessGrantApi - functional programming interface
 */
export const BoxAccessGrantApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = BoxAccessGrantApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create a box-scoped access grant
         * @param {string} boxIdOrName ID or name of the box
         * @param {CreateBoxAccessGrant} createBoxAccessGrant 
         * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createBoxAccessGrant(boxIdOrName: string, createBoxAccessGrant: CreateBoxAccessGrant, xBoxLiteOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BoxAccessGrantCreated>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createBoxAccessGrant(boxIdOrName, createBoxAccessGrant, xBoxLiteOrganizationID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BoxAccessGrantApi.createBoxAccessGrant']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List box-scoped access grants
         * @param {string} boxIdOrName ID or name of the box
         * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listBoxAccessGrants(boxIdOrName: string, xBoxLiteOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<BoxAccessGrant>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listBoxAccessGrants(boxIdOrName, xBoxLiteOrganizationID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BoxAccessGrantApi.listBoxAccessGrants']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Revoke a box-scoped access grant
         * @param {string} boxIdOrName ID or name of the box
         * @param {string} grantId ID of the access grant to revoke
         * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async revokeBoxAccessGrant(boxIdOrName: string, grantId: string, xBoxLiteOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.revokeBoxAccessGrant(boxIdOrName, grantId, xBoxLiteOrganizationID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BoxAccessGrantApi.revokeBoxAccessGrant']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * BoxAccessGrantApi - factory interface
 */
export const BoxAccessGrantApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = BoxAccessGrantApiFp(configuration)
    return {
        /**
         * 
         * @summary Create a box-scoped access grant
         * @param {string} boxIdOrName ID or name of the box
         * @param {CreateBoxAccessGrant} createBoxAccessGrant 
         * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createBoxAccessGrant(boxIdOrName: string, createBoxAccessGrant: CreateBoxAccessGrant, xBoxLiteOrganizationID?: string, options?: RawAxiosRequestConfig): AxiosPromise<BoxAccessGrantCreated> {
            return localVarFp.createBoxAccessGrant(boxIdOrName, createBoxAccessGrant, xBoxLiteOrganizationID, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List box-scoped access grants
         * @param {string} boxIdOrName ID or name of the box
         * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listBoxAccessGrants(boxIdOrName: string, xBoxLiteOrganizationID?: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<BoxAccessGrant>> {
            return localVarFp.listBoxAccessGrants(boxIdOrName, xBoxLiteOrganizationID, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Revoke a box-scoped access grant
         * @param {string} boxIdOrName ID or name of the box
         * @param {string} grantId ID of the access grant to revoke
         * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        revokeBoxAccessGrant(boxIdOrName: string, grantId: string, xBoxLiteOrganizationID?: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.revokeBoxAccessGrant(boxIdOrName, grantId, xBoxLiteOrganizationID, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * BoxAccessGrantApi - object-oriented interface
 */
export class BoxAccessGrantApi extends BaseAPI {
    /**
     * 
     * @summary Create a box-scoped access grant
     * @param {string} boxIdOrName ID or name of the box
     * @param {CreateBoxAccessGrant} createBoxAccessGrant 
     * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createBoxAccessGrant(boxIdOrName: string, createBoxAccessGrant: CreateBoxAccessGrant, xBoxLiteOrganizationID?: string, options?: RawAxiosRequestConfig) {
        return BoxAccessGrantApiFp(this.configuration).createBoxAccessGrant(boxIdOrName, createBoxAccessGrant, xBoxLiteOrganizationID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List box-scoped access grants
     * @param {string} boxIdOrName ID or name of the box
     * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listBoxAccessGrants(boxIdOrName: string, xBoxLiteOrganizationID?: string, options?: RawAxiosRequestConfig) {
        return BoxAccessGrantApiFp(this.configuration).listBoxAccessGrants(boxIdOrName, xBoxLiteOrganizationID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Revoke a box-scoped access grant
     * @param {string} boxIdOrName ID or name of the box
     * @param {string} grantId ID of the access grant to revoke
     * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public revokeBoxAccessGrant(boxIdOrName: string, grantId: string, xBoxLiteOrganizationID?: string, options?: RawAxiosRequestConfig) {
        return BoxAccessGrantApiFp(this.configuration).revokeBoxAccessGrant(boxIdOrName, grantId, xBoxLiteOrganizationID, options).then((request) => request(this.axios, this.basePath));
    }
}

