/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { MetricsResponse } from '../models';
// @ts-ignore
import type { PaginatedLogs } from '../models';
// @ts-ignore
import type { PaginatedTraces } from '../models';
// @ts-ignore
import type { TraceSpan } from '../models';
/**
 * ObservabilityApi - axios parameter creator
 */
export const ObservabilityApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Search tenant-scoped platform and Box logs
         * @param {Date} from 
         * @param {Date} to 
         * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
         * @param {number} [page] 
         * @param {number} [limit] 
         * @param {Array<GetTenantLogsSourcesEnum>} [sources] 
         * @param {string} [runnerId] Exact logical Runner ID
         * @param {string} [boxId] Exact Box ID
         * @param {string} [jobId] Exact Job ID
         * @param {string} [search] Case-insensitive literal substring
         * @param {Array<GetTenantLogsSeveritiesEnum>} [severities] 
         * @param {string} [traceId] Exact OpenTelemetry trace ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTenantLogs: async (from: Date, to: Date, xBoxLiteOrganizationID?: string, page?: number, limit?: number, sources?: Array<GetTenantLogsSourcesEnum>, runnerId?: string, boxId?: string, jobId?: string, search?: string, severities?: Array<GetTenantLogsSeveritiesEnum>, traceId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'from' is not null or undefined
            assertParamExists('getTenantLogs', 'from', from)
            // verify required parameter 'to' is not null or undefined
            assertParamExists('getTenantLogs', 'to', to)
            const localVarPath = `/observability/logs`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication oauth2 required

            if (from !== undefined) {
                localVarQueryParameter['from'] = (from as any instanceof Date) ?
                    (from as any).toISOString() :
                    from;
            }

            if (to !== undefined) {
                localVarQueryParameter['to'] = (to as any instanceof Date) ?
                    (to as any).toISOString() :
                    to;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (sources) {
                localVarQueryParameter['sources'] = sources;
            }

            if (runnerId !== undefined) {
                localVarQueryParameter['runnerId'] = runnerId;
            }

            if (boxId !== undefined) {
                localVarQueryParameter['boxId'] = boxId;
            }

            if (jobId !== undefined) {
                localVarQueryParameter['jobId'] = jobId;
            }

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            if (severities) {
                localVarQueryParameter['severities'] = severities;
            }

            if (traceId !== undefined) {
                localVarQueryParameter['traceId'] = traceId;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            if (xBoxLiteOrganizationID != null) {
                localVarHeaderParameter['X-BoxLite-Organization-ID'] = String(xBoxLiteOrganizationID);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get allowlisted metrics for an owned Box
         * @param {Date} from 
         * @param {Date} to 
         * @param {string} boxId Exact Box ID
         * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
         * @param {Array<string>} [metricNames] Allowlisted metric names
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTenantMetrics: async (from: Date, to: Date, boxId: string, xBoxLiteOrganizationID?: string, metricNames?: Array<string>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'from' is not null or undefined
            assertParamExists('getTenantMetrics', 'from', from)
            // verify required parameter 'to' is not null or undefined
            assertParamExists('getTenantMetrics', 'to', to)
            // verify required parameter 'boxId' is not null or undefined
            assertParamExists('getTenantMetrics', 'boxId', boxId)
            const localVarPath = `/observability/metrics`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication oauth2 required

            if (from !== undefined) {
                localVarQueryParameter['from'] = (from as any instanceof Date) ?
                    (from as any).toISOString() :
                    from;
            }

            if (to !== undefined) {
                localVarQueryParameter['to'] = (to as any instanceof Date) ?
                    (to as any).toISOString() :
                    to;
            }

            if (boxId !== undefined) {
                localVarQueryParameter['boxId'] = boxId;
            }

            if (metricNames) {
                localVarQueryParameter['metricNames'] = metricNames;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            if (xBoxLiteOrganizationID != null) {
                localVarHeaderParameter['X-BoxLite-Organization-ID'] = String(xBoxLiteOrganizationID);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get every tenant-owned span in a trace
         * @param {string} traceId 
         * @param {Date} from 
         * @param {Date} to 
         * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
         * @param {string} [boxId] Optional owned Box filter
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTenantTraceSpans: async (traceId: string, from: Date, to: Date, xBoxLiteOrganizationID?: string, boxId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'traceId' is not null or undefined
            assertParamExists('getTenantTraceSpans', 'traceId', traceId)
            // verify required parameter 'from' is not null or undefined
            assertParamExists('getTenantTraceSpans', 'from', from)
            // verify required parameter 'to' is not null or undefined
            assertParamExists('getTenantTraceSpans', 'to', to)
            const localVarPath = `/observability/traces/{traceId}`
                .replace('{traceId}', encodeURIComponent(String(traceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication oauth2 required

            if (from !== undefined) {
                localVarQueryParameter['from'] = (from as any instanceof Date) ?
                    (from as any).toISOString() :
                    from;
            }

            if (to !== undefined) {
                localVarQueryParameter['to'] = (to as any instanceof Date) ?
                    (to as any).toISOString() :
                    to;
            }

            if (boxId !== undefined) {
                localVarQueryParameter['boxId'] = boxId;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            if (xBoxLiteOrganizationID != null) {
                localVarHeaderParameter['X-BoxLite-Organization-ID'] = String(xBoxLiteOrganizationID);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Search tenant-scoped distributed traces
         * @param {Date} from 
         * @param {Date} to 
         * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
         * @param {number} [page] 
         * @param {number} [limit] 
         * @param {Array<GetTenantTracesSourcesEnum>} [sources] 
         * @param {string} [runnerId] Exact logical Runner ID
         * @param {string} [boxId] Exact Box ID
         * @param {string} [jobId] Exact Job ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTenantTraces: async (from: Date, to: Date, xBoxLiteOrganizationID?: string, page?: number, limit?: number, sources?: Array<GetTenantTracesSourcesEnum>, runnerId?: string, boxId?: string, jobId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'from' is not null or undefined
            assertParamExists('getTenantTraces', 'from', from)
            // verify required parameter 'to' is not null or undefined
            assertParamExists('getTenantTraces', 'to', to)
            const localVarPath = `/observability/traces`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication oauth2 required

            if (from !== undefined) {
                localVarQueryParameter['from'] = (from as any instanceof Date) ?
                    (from as any).toISOString() :
                    from;
            }

            if (to !== undefined) {
                localVarQueryParameter['to'] = (to as any instanceof Date) ?
                    (to as any).toISOString() :
                    to;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (sources) {
                localVarQueryParameter['sources'] = sources;
            }

            if (runnerId !== undefined) {
                localVarQueryParameter['runnerId'] = runnerId;
            }

            if (boxId !== undefined) {
                localVarQueryParameter['boxId'] = boxId;
            }

            if (jobId !== undefined) {
                localVarQueryParameter['jobId'] = jobId;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            if (xBoxLiteOrganizationID != null) {
                localVarHeaderParameter['X-BoxLite-Organization-ID'] = String(xBoxLiteOrganizationID);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ObservabilityApi - functional programming interface
 */
export const ObservabilityApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ObservabilityApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Search tenant-scoped platform and Box logs
         * @param {Date} from 
         * @param {Date} to 
         * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
         * @param {number} [page] 
         * @param {number} [limit] 
         * @param {Array<GetTenantLogsSourcesEnum>} [sources] 
         * @param {string} [runnerId] Exact logical Runner ID
         * @param {string} [boxId] Exact Box ID
         * @param {string} [jobId] Exact Job ID
         * @param {string} [search] Case-insensitive literal substring
         * @param {Array<GetTenantLogsSeveritiesEnum>} [severities] 
         * @param {string} [traceId] Exact OpenTelemetry trace ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTenantLogs(from: Date, to: Date, xBoxLiteOrganizationID?: string, page?: number, limit?: number, sources?: Array<GetTenantLogsSourcesEnum>, runnerId?: string, boxId?: string, jobId?: string, search?: string, severities?: Array<GetTenantLogsSeveritiesEnum>, traceId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaginatedLogs>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTenantLogs(from, to, xBoxLiteOrganizationID, page, limit, sources, runnerId, boxId, jobId, search, severities, traceId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ObservabilityApi.getTenantLogs']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get allowlisted metrics for an owned Box
         * @param {Date} from 
         * @param {Date} to 
         * @param {string} boxId Exact Box ID
         * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
         * @param {Array<string>} [metricNames] Allowlisted metric names
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTenantMetrics(from: Date, to: Date, boxId: string, xBoxLiteOrganizationID?: string, metricNames?: Array<string>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MetricsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTenantMetrics(from, to, boxId, xBoxLiteOrganizationID, metricNames, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ObservabilityApi.getTenantMetrics']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get every tenant-owned span in a trace
         * @param {string} traceId 
         * @param {Date} from 
         * @param {Date} to 
         * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
         * @param {string} [boxId] Optional owned Box filter
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTenantTraceSpans(traceId: string, from: Date, to: Date, xBoxLiteOrganizationID?: string, boxId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<TraceSpan>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTenantTraceSpans(traceId, from, to, xBoxLiteOrganizationID, boxId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ObservabilityApi.getTenantTraceSpans']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Search tenant-scoped distributed traces
         * @param {Date} from 
         * @param {Date} to 
         * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
         * @param {number} [page] 
         * @param {number} [limit] 
         * @param {Array<GetTenantTracesSourcesEnum>} [sources] 
         * @param {string} [runnerId] Exact logical Runner ID
         * @param {string} [boxId] Exact Box ID
         * @param {string} [jobId] Exact Job ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTenantTraces(from: Date, to: Date, xBoxLiteOrganizationID?: string, page?: number, limit?: number, sources?: Array<GetTenantTracesSourcesEnum>, runnerId?: string, boxId?: string, jobId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaginatedTraces>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTenantTraces(from, to, xBoxLiteOrganizationID, page, limit, sources, runnerId, boxId, jobId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ObservabilityApi.getTenantTraces']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ObservabilityApi - factory interface
 */
export const ObservabilityApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ObservabilityApiFp(configuration)
    return {
        /**
         * 
         * @summary Search tenant-scoped platform and Box logs
         * @param {Date} from 
         * @param {Date} to 
         * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
         * @param {number} [page] 
         * @param {number} [limit] 
         * @param {Array<GetTenantLogsSourcesEnum>} [sources] 
         * @param {string} [runnerId] Exact logical Runner ID
         * @param {string} [boxId] Exact Box ID
         * @param {string} [jobId] Exact Job ID
         * @param {string} [search] Case-insensitive literal substring
         * @param {Array<GetTenantLogsSeveritiesEnum>} [severities] 
         * @param {string} [traceId] Exact OpenTelemetry trace ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTenantLogs(from: Date, to: Date, xBoxLiteOrganizationID?: string, page?: number, limit?: number, sources?: Array<GetTenantLogsSourcesEnum>, runnerId?: string, boxId?: string, jobId?: string, search?: string, severities?: Array<GetTenantLogsSeveritiesEnum>, traceId?: string, options?: RawAxiosRequestConfig): AxiosPromise<PaginatedLogs> {
            return localVarFp.getTenantLogs(from, to, xBoxLiteOrganizationID, page, limit, sources, runnerId, boxId, jobId, search, severities, traceId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get allowlisted metrics for an owned Box
         * @param {Date} from 
         * @param {Date} to 
         * @param {string} boxId Exact Box ID
         * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
         * @param {Array<string>} [metricNames] Allowlisted metric names
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTenantMetrics(from: Date, to: Date, boxId: string, xBoxLiteOrganizationID?: string, metricNames?: Array<string>, options?: RawAxiosRequestConfig): AxiosPromise<MetricsResponse> {
            return localVarFp.getTenantMetrics(from, to, boxId, xBoxLiteOrganizationID, metricNames, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get every tenant-owned span in a trace
         * @param {string} traceId 
         * @param {Date} from 
         * @param {Date} to 
         * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
         * @param {string} [boxId] Optional owned Box filter
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTenantTraceSpans(traceId: string, from: Date, to: Date, xBoxLiteOrganizationID?: string, boxId?: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<TraceSpan>> {
            return localVarFp.getTenantTraceSpans(traceId, from, to, xBoxLiteOrganizationID, boxId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Search tenant-scoped distributed traces
         * @param {Date} from 
         * @param {Date} to 
         * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
         * @param {number} [page] 
         * @param {number} [limit] 
         * @param {Array<GetTenantTracesSourcesEnum>} [sources] 
         * @param {string} [runnerId] Exact logical Runner ID
         * @param {string} [boxId] Exact Box ID
         * @param {string} [jobId] Exact Job ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTenantTraces(from: Date, to: Date, xBoxLiteOrganizationID?: string, page?: number, limit?: number, sources?: Array<GetTenantTracesSourcesEnum>, runnerId?: string, boxId?: string, jobId?: string, options?: RawAxiosRequestConfig): AxiosPromise<PaginatedTraces> {
            return localVarFp.getTenantTraces(from, to, xBoxLiteOrganizationID, page, limit, sources, runnerId, boxId, jobId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ObservabilityApi - object-oriented interface
 */
export class ObservabilityApi extends BaseAPI {
    /**
     * 
     * @summary Search tenant-scoped platform and Box logs
     * @param {Date} from 
     * @param {Date} to 
     * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
     * @param {number} [page] 
     * @param {number} [limit] 
     * @param {Array<GetTenantLogsSourcesEnum>} [sources] 
     * @param {string} [runnerId] Exact logical Runner ID
     * @param {string} [boxId] Exact Box ID
     * @param {string} [jobId] Exact Job ID
     * @param {string} [search] Case-insensitive literal substring
     * @param {Array<GetTenantLogsSeveritiesEnum>} [severities] 
     * @param {string} [traceId] Exact OpenTelemetry trace ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getTenantLogs(from: Date, to: Date, xBoxLiteOrganizationID?: string, page?: number, limit?: number, sources?: Array<GetTenantLogsSourcesEnum>, runnerId?: string, boxId?: string, jobId?: string, search?: string, severities?: Array<GetTenantLogsSeveritiesEnum>, traceId?: string, options?: RawAxiosRequestConfig) {
        return ObservabilityApiFp(this.configuration).getTenantLogs(from, to, xBoxLiteOrganizationID, page, limit, sources, runnerId, boxId, jobId, search, severities, traceId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get allowlisted metrics for an owned Box
     * @param {Date} from 
     * @param {Date} to 
     * @param {string} boxId Exact Box ID
     * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
     * @param {Array<string>} [metricNames] Allowlisted metric names
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getTenantMetrics(from: Date, to: Date, boxId: string, xBoxLiteOrganizationID?: string, metricNames?: Array<string>, options?: RawAxiosRequestConfig) {
        return ObservabilityApiFp(this.configuration).getTenantMetrics(from, to, boxId, xBoxLiteOrganizationID, metricNames, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get every tenant-owned span in a trace
     * @param {string} traceId 
     * @param {Date} from 
     * @param {Date} to 
     * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
     * @param {string} [boxId] Optional owned Box filter
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getTenantTraceSpans(traceId: string, from: Date, to: Date, xBoxLiteOrganizationID?: string, boxId?: string, options?: RawAxiosRequestConfig) {
        return ObservabilityApiFp(this.configuration).getTenantTraceSpans(traceId, from, to, xBoxLiteOrganizationID, boxId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Search tenant-scoped distributed traces
     * @param {Date} from 
     * @param {Date} to 
     * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
     * @param {number} [page] 
     * @param {number} [limit] 
     * @param {Array<GetTenantTracesSourcesEnum>} [sources] 
     * @param {string} [runnerId] Exact logical Runner ID
     * @param {string} [boxId] Exact Box ID
     * @param {string} [jobId] Exact Job ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getTenantTraces(from: Date, to: Date, xBoxLiteOrganizationID?: string, page?: number, limit?: number, sources?: Array<GetTenantTracesSourcesEnum>, runnerId?: string, boxId?: string, jobId?: string, options?: RawAxiosRequestConfig) {
        return ObservabilityApiFp(this.configuration).getTenantTraces(from, to, xBoxLiteOrganizationID, page, limit, sources, runnerId, boxId, jobId, options).then((request) => request(this.axios, this.basePath));
    }
}

export const GetTenantLogsSourcesEnum = {
    API: 'api',
    WORKER: 'worker',
    RUNNER: 'runner',
    RUNTIME_WRAPPER: 'runtime-wrapper',
    BOX: 'box',
    COLLECTOR_DELIVERY: 'collector-delivery',
    UNKNOWN_DEFAULT_OPEN_API: '11184809',
} as const;
export type GetTenantLogsSourcesEnum = typeof GetTenantLogsSourcesEnum[keyof typeof GetTenantLogsSourcesEnum];
export const GetTenantLogsSeveritiesEnum = {
    DEBUG: 'DEBUG',
    INFO: 'INFO',
    WARN: 'WARN',
    ERROR: 'ERROR',
    FATAL: 'FATAL',
    UNKNOWN_DEFAULT_OPEN_API: '11184809',
} as const;
export type GetTenantLogsSeveritiesEnum = typeof GetTenantLogsSeveritiesEnum[keyof typeof GetTenantLogsSeveritiesEnum];
export const GetTenantTracesSourcesEnum = {
    API: 'api',
    WORKER: 'worker',
    RUNNER: 'runner',
    RUNTIME_WRAPPER: 'runtime-wrapper',
    BOX: 'box',
    COLLECTOR_DELIVERY: 'collector-delivery',
    UNKNOWN_DEFAULT_OPEN_API: '11184809',
} as const;
export type GetTenantTracesSourcesEnum = typeof GetTenantTracesSourcesEnum[keyof typeof GetTenantTracesSourcesEnum];
