/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AggregatedUsage } from '../models';
// @ts-ignore
import type { BoxUsage } from '../models';
// @ts-ignore
import type { UsageChartPoint } from '../models';
// @ts-ignore
import type { UsagePeriod } from '../models';
/**
 * UsageApi - axios parameter creator
 */
export const UsageApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retrieve aggregated usage for an organization within a time range
         * @summary Get aggregated usage
         * @param {string} organizationId 
         * @param {Date} from Inclusive range start as an RFC3339 timestamp
         * @param {Date} to Exclusive range end as an RFC3339 timestamp
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usageControllerGetAggregatedUsage: async (organizationId: string, from: Date, to: Date, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'organizationId' is not null or undefined
            assertParamExists('usageControllerGetAggregatedUsage', 'organizationId', organizationId)
            // verify required parameter 'from' is not null or undefined
            assertParamExists('usageControllerGetAggregatedUsage', 'from', from)
            // verify required parameter 'to' is not null or undefined
            assertParamExists('usageControllerGetAggregatedUsage', 'to', to)
            const localVarPath = `/organization/{organizationId}/usage/aggregated`
                .replace('{organizationId}', encodeURIComponent(String(organizationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication oauth2 required

            if (from !== undefined) {
                localVarQueryParameter['from'] = (from as any instanceof Date) ?
                    (from as any).toISOString() :
                    from;
            }

            if (to !== undefined) {
                localVarQueryParameter['to'] = (to as any instanceof Date) ?
                    (to as any).toISOString() :
                    to;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve per-box usage for an organization within a time range
         * @summary Get per-box usage
         * @param {string} organizationId 
         * @param {Date} from Inclusive range start as an RFC3339 timestamp
         * @param {Date} to Exclusive range end as an RFC3339 timestamp
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usageControllerGetBoxUsage: async (organizationId: string, from: Date, to: Date, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'organizationId' is not null or undefined
            assertParamExists('usageControllerGetBoxUsage', 'organizationId', organizationId)
            // verify required parameter 'from' is not null or undefined
            assertParamExists('usageControllerGetBoxUsage', 'from', from)
            // verify required parameter 'to' is not null or undefined
            assertParamExists('usageControllerGetBoxUsage', 'to', to)
            const localVarPath = `/organization/{organizationId}/usage/box`
                .replace('{organizationId}', encodeURIComponent(String(organizationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication oauth2 required

            if (from !== undefined) {
                localVarQueryParameter['from'] = (from as any instanceof Date) ?
                    (from as any).toISOString() :
                    from;
            }

            if (to !== undefined) {
                localVarQueryParameter['to'] = (to as any instanceof Date) ?
                    (to as any).toISOString() :
                    to;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve usage periods for a specific box within a time range
         * @summary Get box usage periods
         * @param {string} organizationId 
         * @param {string} boxId 
         * @param {Date} from Inclusive range start as an RFC3339 timestamp
         * @param {Date} to Exclusive range end as an RFC3339 timestamp
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usageControllerGetBoxUsagePeriods: async (organizationId: string, boxId: string, from: Date, to: Date, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'organizationId' is not null or undefined
            assertParamExists('usageControllerGetBoxUsagePeriods', 'organizationId', organizationId)
            // verify required parameter 'boxId' is not null or undefined
            assertParamExists('usageControllerGetBoxUsagePeriods', 'boxId', boxId)
            // verify required parameter 'from' is not null or undefined
            assertParamExists('usageControllerGetBoxUsagePeriods', 'from', from)
            // verify required parameter 'to' is not null or undefined
            assertParamExists('usageControllerGetBoxUsagePeriods', 'to', to)
            const localVarPath = `/organization/{organizationId}/box/{boxId}/usage`
                .replace('{organizationId}', encodeURIComponent(String(organizationId)))
                .replace('{boxId}', encodeURIComponent(String(boxId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication oauth2 required

            if (from !== undefined) {
                localVarQueryParameter['from'] = (from as any instanceof Date) ?
                    (from as any).toISOString() :
                    from;
            }

            if (to !== undefined) {
                localVarQueryParameter['to'] = (to as any instanceof Date) ?
                    (to as any).toISOString() :
                    to;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve UTC-day usage chart points for an organization within a time range
         * @summary Get usage chart data
         * @param {string} organizationId 
         * @param {Date} from Inclusive range start as an RFC3339 timestamp
         * @param {Date} to Exclusive range end as an RFC3339 timestamp
         * @param {string} [region] Only include usage recorded in this region
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usageControllerGetUsageChart: async (organizationId: string, from: Date, to: Date, region?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'organizationId' is not null or undefined
            assertParamExists('usageControllerGetUsageChart', 'organizationId', organizationId)
            // verify required parameter 'from' is not null or undefined
            assertParamExists('usageControllerGetUsageChart', 'from', from)
            // verify required parameter 'to' is not null or undefined
            assertParamExists('usageControllerGetUsageChart', 'to', to)
            const localVarPath = `/organization/{organizationId}/usage/chart`
                .replace('{organizationId}', encodeURIComponent(String(organizationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication oauth2 required

            if (from !== undefined) {
                localVarQueryParameter['from'] = (from as any instanceof Date) ?
                    (from as any).toISOString() :
                    from;
            }

            if (to !== undefined) {
                localVarQueryParameter['to'] = (to as any instanceof Date) ?
                    (to as any).toISOString() :
                    to;
            }

            if (region !== undefined) {
                localVarQueryParameter['region'] = region;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UsageApi - functional programming interface
 */
export const UsageApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UsageApiAxiosParamCreator(configuration)
    return {
        /**
         * Retrieve aggregated usage for an organization within a time range
         * @summary Get aggregated usage
         * @param {string} organizationId 
         * @param {Date} from Inclusive range start as an RFC3339 timestamp
         * @param {Date} to Exclusive range end as an RFC3339 timestamp
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usageControllerGetAggregatedUsage(organizationId: string, from: Date, to: Date, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AggregatedUsage>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usageControllerGetAggregatedUsage(organizationId, from, to, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsageApi.usageControllerGetAggregatedUsage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieve per-box usage for an organization within a time range
         * @summary Get per-box usage
         * @param {string} organizationId 
         * @param {Date} from Inclusive range start as an RFC3339 timestamp
         * @param {Date} to Exclusive range end as an RFC3339 timestamp
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usageControllerGetBoxUsage(organizationId: string, from: Date, to: Date, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<BoxUsage>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usageControllerGetBoxUsage(organizationId, from, to, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsageApi.usageControllerGetBoxUsage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieve usage periods for a specific box within a time range
         * @summary Get box usage periods
         * @param {string} organizationId 
         * @param {string} boxId 
         * @param {Date} from Inclusive range start as an RFC3339 timestamp
         * @param {Date} to Exclusive range end as an RFC3339 timestamp
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usageControllerGetBoxUsagePeriods(organizationId: string, boxId: string, from: Date, to: Date, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<UsagePeriod>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usageControllerGetBoxUsagePeriods(organizationId, boxId, from, to, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsageApi.usageControllerGetBoxUsagePeriods']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieve UTC-day usage chart points for an organization within a time range
         * @summary Get usage chart data
         * @param {string} organizationId 
         * @param {Date} from Inclusive range start as an RFC3339 timestamp
         * @param {Date} to Exclusive range end as an RFC3339 timestamp
         * @param {string} [region] Only include usage recorded in this region
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usageControllerGetUsageChart(organizationId: string, from: Date, to: Date, region?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<UsageChartPoint>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usageControllerGetUsageChart(organizationId, from, to, region, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsageApi.usageControllerGetUsageChart']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UsageApi - factory interface
 */
export const UsageApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UsageApiFp(configuration)
    return {
        /**
         * Retrieve aggregated usage for an organization within a time range
         * @summary Get aggregated usage
         * @param {string} organizationId 
         * @param {Date} from Inclusive range start as an RFC3339 timestamp
         * @param {Date} to Exclusive range end as an RFC3339 timestamp
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usageControllerGetAggregatedUsage(organizationId: string, from: Date, to: Date, options?: RawAxiosRequestConfig): AxiosPromise<AggregatedUsage> {
            return localVarFp.usageControllerGetAggregatedUsage(organizationId, from, to, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve per-box usage for an organization within a time range
         * @summary Get per-box usage
         * @param {string} organizationId 
         * @param {Date} from Inclusive range start as an RFC3339 timestamp
         * @param {Date} to Exclusive range end as an RFC3339 timestamp
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usageControllerGetBoxUsage(organizationId: string, from: Date, to: Date, options?: RawAxiosRequestConfig): AxiosPromise<Array<BoxUsage>> {
            return localVarFp.usageControllerGetBoxUsage(organizationId, from, to, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve usage periods for a specific box within a time range
         * @summary Get box usage periods
         * @param {string} organizationId 
         * @param {string} boxId 
         * @param {Date} from Inclusive range start as an RFC3339 timestamp
         * @param {Date} to Exclusive range end as an RFC3339 timestamp
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usageControllerGetBoxUsagePeriods(organizationId: string, boxId: string, from: Date, to: Date, options?: RawAxiosRequestConfig): AxiosPromise<Array<UsagePeriod>> {
            return localVarFp.usageControllerGetBoxUsagePeriods(organizationId, boxId, from, to, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve UTC-day usage chart points for an organization within a time range
         * @summary Get usage chart data
         * @param {string} organizationId 
         * @param {Date} from Inclusive range start as an RFC3339 timestamp
         * @param {Date} to Exclusive range end as an RFC3339 timestamp
         * @param {string} [region] Only include usage recorded in this region
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usageControllerGetUsageChart(organizationId: string, from: Date, to: Date, region?: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<UsageChartPoint>> {
            return localVarFp.usageControllerGetUsageChart(organizationId, from, to, region, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UsageApi - object-oriented interface
 */
export class UsageApi extends BaseAPI {
    /**
     * Retrieve aggregated usage for an organization within a time range
     * @summary Get aggregated usage
     * @param {string} organizationId 
     * @param {Date} from Inclusive range start as an RFC3339 timestamp
     * @param {Date} to Exclusive range end as an RFC3339 timestamp
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public usageControllerGetAggregatedUsage(organizationId: string, from: Date, to: Date, options?: RawAxiosRequestConfig) {
        return UsageApiFp(this.configuration).usageControllerGetAggregatedUsage(organizationId, from, to, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve per-box usage for an organization within a time range
     * @summary Get per-box usage
     * @param {string} organizationId 
     * @param {Date} from Inclusive range start as an RFC3339 timestamp
     * @param {Date} to Exclusive range end as an RFC3339 timestamp
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public usageControllerGetBoxUsage(organizationId: string, from: Date, to: Date, options?: RawAxiosRequestConfig) {
        return UsageApiFp(this.configuration).usageControllerGetBoxUsage(organizationId, from, to, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve usage periods for a specific box within a time range
     * @summary Get box usage periods
     * @param {string} organizationId 
     * @param {string} boxId 
     * @param {Date} from Inclusive range start as an RFC3339 timestamp
     * @param {Date} to Exclusive range end as an RFC3339 timestamp
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public usageControllerGetBoxUsagePeriods(organizationId: string, boxId: string, from: Date, to: Date, options?: RawAxiosRequestConfig) {
        return UsageApiFp(this.configuration).usageControllerGetBoxUsagePeriods(organizationId, boxId, from, to, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve UTC-day usage chart points for an organization within a time range
     * @summary Get usage chart data
     * @param {string} organizationId 
     * @param {Date} from Inclusive range start as an RFC3339 timestamp
     * @param {Date} to Exclusive range end as an RFC3339 timestamp
     * @param {string} [region] Only include usage recorded in this region
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public usageControllerGetUsageChart(organizationId: string, from: Date, to: Date, region?: string, options?: RawAxiosRequestConfig) {
        return UsageApiFp(this.configuration).usageControllerGetUsageChart(organizationId, from, to, region, options).then((request) => request(this.axios, this.basePath));
    }
}

