/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { UsageConcurrencySeriesDto } from '../models';
/**
 * UsageApi - axios parameter creator
 */
export const UsageApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get organization concurrency timeline
         * @param {string} organizationId Organization ID
         * @param {Date} [from] Inclusive start of the requested timeline. Defaults to 30 days before &#x60;to&#x60;.
         * @param {Date} [to] Inclusive end of the requested timeline. Defaults to the current time.
         * @param {GetOrganizationUsageConcurrencyGranularityEnum} [granularity] Spacing between concurrency snapshots.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOrganizationUsageConcurrency: async (organizationId: string, from?: Date, to?: Date, granularity?: GetOrganizationUsageConcurrencyGranularityEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'organizationId' is not null or undefined
            assertParamExists('getOrganizationUsageConcurrency', 'organizationId', organizationId)
            const localVarPath = `/organizations/{organizationId}/concurrency`
                .replace('{organizationId}', encodeURIComponent(String(organizationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication oauth2 required

            if (from !== undefined) {
                localVarQueryParameter['from'] = (from as any instanceof Date) ?
                    (from as any).toISOString() :
                    from;
            }

            if (to !== undefined) {
                localVarQueryParameter['to'] = (to as any instanceof Date) ?
                    (to as any).toISOString() :
                    to;
            }

            if (granularity !== undefined) {
                localVarQueryParameter['granularity'] = granularity;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UsageApi - functional programming interface
 */
export const UsageApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UsageApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get organization concurrency timeline
         * @param {string} organizationId Organization ID
         * @param {Date} [from] Inclusive start of the requested timeline. Defaults to 30 days before &#x60;to&#x60;.
         * @param {Date} [to] Inclusive end of the requested timeline. Defaults to the current time.
         * @param {GetOrganizationUsageConcurrencyGranularityEnum} [granularity] Spacing between concurrency snapshots.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getOrganizationUsageConcurrency(organizationId: string, from?: Date, to?: Date, granularity?: GetOrganizationUsageConcurrencyGranularityEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UsageConcurrencySeriesDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getOrganizationUsageConcurrency(organizationId, from, to, granularity, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsageApi.getOrganizationUsageConcurrency']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UsageApi - factory interface
 */
export const UsageApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UsageApiFp(configuration)
    return {
        /**
         * 
         * @summary Get organization concurrency timeline
         * @param {string} organizationId Organization ID
         * @param {Date} [from] Inclusive start of the requested timeline. Defaults to 30 days before &#x60;to&#x60;.
         * @param {Date} [to] Inclusive end of the requested timeline. Defaults to the current time.
         * @param {GetOrganizationUsageConcurrencyGranularityEnum} [granularity] Spacing between concurrency snapshots.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOrganizationUsageConcurrency(organizationId: string, from?: Date, to?: Date, granularity?: GetOrganizationUsageConcurrencyGranularityEnum, options?: RawAxiosRequestConfig): AxiosPromise<UsageConcurrencySeriesDto> {
            return localVarFp.getOrganizationUsageConcurrency(organizationId, from, to, granularity, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UsageApi - object-oriented interface
 */
export class UsageApi extends BaseAPI {
    /**
     * 
     * @summary Get organization concurrency timeline
     * @param {string} organizationId Organization ID
     * @param {Date} [from] Inclusive start of the requested timeline. Defaults to 30 days before &#x60;to&#x60;.
     * @param {Date} [to] Inclusive end of the requested timeline. Defaults to the current time.
     * @param {GetOrganizationUsageConcurrencyGranularityEnum} [granularity] Spacing between concurrency snapshots.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getOrganizationUsageConcurrency(organizationId: string, from?: Date, to?: Date, granularity?: GetOrganizationUsageConcurrencyGranularityEnum, options?: RawAxiosRequestConfig) {
        return UsageApiFp(this.configuration).getOrganizationUsageConcurrency(organizationId, from, to, granularity, options).then((request) => request(this.axios, this.basePath));
    }
}

export const GetOrganizationUsageConcurrencyGranularityEnum = {
    HOUR: 'hour',
    DAY: 'day',
    UNKNOWN_DEFAULT_OPEN_API: '11184809',
} as const;
export type GetOrganizationUsageConcurrencyGranularityEnum = typeof GetOrganizationUsageConcurrencyGranularityEnum[keyof typeof GetOrganizationUsageConcurrencyGranularityEnum];
