/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface AggregatedUsage {
    'boxCount': number;
    'firstStart'?: Date;
    'lastEnd'?: Date;
    'totalCPUSeconds': number;
    'totalDiskGBSeconds': number;
    'totalGPUSeconds': number;
    /**
     * Always 0 for the self-hosted raw ledger. Monetary rating belongs to the external billing service.
     */
    'totalPrice': number;
    'totalRAMGBSeconds': number;
}

