/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

import type { LinuxCapabilities } from './linux-capabilities'

export interface BoxAdvancedOptions {
  capabilities: LinuxCapabilities
}
