/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface BoxAccessGrantCreated {
    /**
     * Unique identifier for the access grant
     */
    'id': string;
    /**
     * ID of the box this grant is scoped to
     */
    'boxId': string;
    /**
     * Capability scopes granted
     */
    'scopes': Array<BoxAccessGrantCreatedScopesEnum>;
    /**
     * When the grant expires
     */
    'expiresAt': Date;
    /**
     * One-time plaintext app key. Not recoverable after this response; store it now.
     */
    'appKey': string;
}

export const BoxAccessGrantCreatedScopesEnum = {
    SSH: 'ssh',
    UNKNOWN_DEFAULT_OPEN_API: '11184809',
} as const;

export type BoxAccessGrantCreatedScopesEnum = typeof BoxAccessGrantCreatedScopesEnum[keyof typeof BoxAccessGrantCreatedScopesEnum];


