/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Announcement } from './announcement';
// May contain unused imports in some cases
// @ts-ignore
import type { OidcConfig } from './oidc-config';
// May contain unused imports in some cases
// @ts-ignore
import type { PosthogConfig } from './posthog-config';
// May contain unused imports in some cases
// @ts-ignore
import type { RateLimitConfig } from './rate-limit-config';
// May contain unused imports in some cases
// @ts-ignore
import type { SupportedImage } from './supported-image';

export interface BoxliteConfiguration {
    /**
     * BoxLite version
     */
    'version': string;
    /**
     * PostHog configuration
     */
    'posthog'?: PosthogConfig;
    /**
     * OIDC configuration
     */
    'oidc': OidcConfig;
    /**
     * Whether linked accounts are enabled
     */
    'linkedAccountsEnabled': boolean;
    /**
     * System announcements
     */
    'announcements': { [key: string]: Announcement; };
    /**
     * Pylon application ID
     */
    'pylonAppId'?: string;
    /**
     * Proxy template URL
     */
    'proxyTemplateUrl': string;
    /**
     * Toolbox template URL
     */
    'proxyToolboxUrl': string;
    /**
     * Dashboard URL
     */
    'dashboardUrl': string;
    /**
     * Whether maintenance mode is enabled
     */
    'maintananceMode': boolean;
    /**
     * Current environment
     */
    'environment': string;
    /**
     * Ordered images accepted by the box-create API; the first entry is the default
     */
    'supportedImages': Array<SupportedImage>;
    /**
     * Billing API URL
     */
    'billingApiUrl'?: string;
    /**
     * Analytics API URL
     */
    'analyticsApiUrl'?: string;
    /**
     * Rate limit configuration
     */
    'rateLimit'?: RateLimitConfig;
}

