/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface CreateTemporarySshCredential {
    /**
     * ID of a previously issued, active `ssh`-scoped access grant for this box
     */
    'grantId': string;
    /**
     * Canonical OpenSSH public key line, e.g. \"ssh-ed25519 AAAA... user@host\"
     */
    'publicKey': string;
    /**
     * Credential lifetime in seconds (default 300, max bounded by the parent grant expiry)
     */
    'expiresInSeconds'?: number;
}

