/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The type of the job
 */

export const JobType = {
    CREATE_BOX: 'CREATE_BOX',
    START_BOX: 'START_BOX',
    STOP_BOX: 'STOP_BOX',
    DESTROY_BOX: 'DESTROY_BOX',
    UPDATE_BOX_NETWORK_SETTINGS: 'UPDATE_BOX_NETWORK_SETTINGS',
    EXPORT_BOX: 'EXPORT_BOX',
    IMPORT_BOX: 'IMPORT_BOX',
    ROLLBACK_EXPORT_BOX: 'ROLLBACK_EXPORT_BOX',
    ROLLBACK_IMPORT_BOX: 'ROLLBACK_IMPORT_BOX',
    DISCARD_EXPORTED_BOX: 'DISCARD_EXPORTED_BOX',
    UNKNOWN_DEFAULT_OPEN_API: '11184809',
} as const;

export type JobType = typeof JobType[keyof typeof JobType];

