/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface OrganizationUsageOverview {
    /**
     * vCPU currently consumed by running boxes
     */
    'currentCpuUsage': number;
    /**
     * Total vCPU the organization may consume
     */
    'totalCpuQuota': number;
    /**
     * Memory in GB currently consumed by running boxes
     */
    'currentMemoryUsage': number;
    /**
     * Total memory in GB the organization may consume
     */
    'totalMemoryQuota': number;
    /**
     * Disk in GB currently occupied by boxes
     */
    'currentDiskUsage': number;
    /**
     * Total disk in GB the organization may occupy
     */
    'totalDiskQuota': number;
    /**
     * GPUs currently consumed by running boxes
     */
    'currentGpuUsage': number;
    /**
     * Total GPUs the organization may consume; 0 denies GPU boxes
     */
    'totalGpuQuota': number;
    /**
     * Boxes currently running
     */
    'currentBoxUsage': number;
    /**
     * Maximum number of concurrently running boxes
     */
    'maxConcurrentBoxes': number;
}

