/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RegistryCredentialKind } from './registry-credential-kind';

export interface RegistryCredential {
    'id': string;
    'kind': RegistryCredentialKind;
    'registryHost': string;
    /**
     * Empty for the whole registry
     */
    'repositoryPrefix': string;
    'username': string;
    /**
     * The user who added it
     */
    'createdBy': string | null;
    'createdAt': string;
}



