/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BoxState } from './box-state';

export interface RunnerBoxObservation {
    /**
     * Control-plane box ID observed on the runner
     */
    'boxId': string;
    /**
     * Actual box state observed by the runner
     */
    'actualState': BoxState;
    /**
     * Control-plane runtime generation associated with the observed instance. Zero means the runner cannot provide generation evidence.
     */
    'runtimeGeneration': number;
}



