/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface SystemImagesConfig {
    /**
     * Curated Base image reference
     */
    'base': string;
    /**
     * Curated Python image reference
     */
    'python': string;
    /**
     * Curated Node.js image reference
     */
    'node': string;
}
