/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface UpdateOrganizationRole {
    /**
     * The name of the role
     */
    'name': string;
    /**
     * The description of the role
     */
    'description': string;
    /**
     * The list of permissions assigned to the role
     */
    'permissions': Array<UpdateOrganizationRolePermissionsEnum>;
}

export const UpdateOrganizationRolePermissionsEnum = {
    WRITE_BOXES: 'write:boxes',
    DELETE_BOXES: 'delete:boxes',
    UNKNOWN_DEFAULT_OPEN_API: '11184809',
} as const;

export type UpdateOrganizationRolePermissionsEnum = typeof UpdateOrganizationRolePermissionsEnum[keyof typeof UpdateOrganizationRolePermissionsEnum];
