/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface UrlConfig {
    /**
     * Public REST API URL including the /api prefix. SDK and CLI quickstarts should use this URL.
     */
    'publicRestApiUrl': string;
    /**
     * Dashboard runtime API URL including the /api prefix. This is the endpoint the bundled dashboard is configured to call.
     */
    'dashboardApiUrl': string;
}
