/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface WalletResponseDto {
    'balanceCents': number;
    'ongoingBalanceCents': number;
    'name': string;
    'creditCardConnected': boolean;
    'freeBalanceCents'?: number;
    'paidBalanceCents'?: number;
    'billingStatus'?: WalletResponseDtoBillingStatusEnum;
    'hasFailedOrPendingInvoice'?: boolean;
}

export const WalletResponseDtoBillingStatusEnum = {
    TRIAL: 'trial',
    ACTIVE: 'active',
    LOW_BALANCE: 'low_balance',
    ZERO_BALANCE: 'zero_balance',
    SUSPENDED: 'suspended',
    CLOSED: 'closed',
    UNKNOWN_DEFAULT_OPEN_API: '11184809',
} as const;

export type WalletResponseDtoBillingStatusEnum = typeof WalletResponseDtoBillingStatusEnum[keyof typeof WalletResponseDtoBillingStatusEnum];
