/*
 * Copyright 2026 BoxLite AI
 * SPDX-License-Identifier: AGPL-3.0
 */

import { QueryRunner } from 'typeorm'
import { AddBoxBillingTransitionOutbox1786000500000 } from './1786000500000-add-box-billing-transition-outbox-migration'

describe('AddBoxBillingTransitionOutbox1786000500000', () => {
  const queryRunner = (failurePattern?: string) => {
    const runner = {
      query: jest.fn().mockImplementation(async (statement: string) => {
        if (failurePattern && statement.includes(failurePattern)) {
          throw new Error('injected migration failure')
        }
      }),
      startTransaction: jest.fn().mockResolvedValue(undefined),
      commitTransaction: jest.fn().mockResolvedValue(undefined),
      rollbackTransaction: jest.fn().mockResolvedValue(undefined),
    }
    return runner as unknown as QueryRunner
  }

  it('installs an idempotent ordered outbox and upgrades the existing trigger', async () => {
    const runner = queryRunner()
    const migration = new AddBoxBillingTransitionOutbox1786000500000()

    await migration.up(runner)

    const sql = (runner.query as jest.Mock).mock.calls.map(([statement]) => statement).join('\n')
    expect(migration.transaction).toBe(false)
    expect(runner.startTransaction).toHaveBeenCalledTimes(1)
    expect(runner.commitTransaction).toHaveBeenCalledTimes(1)
    expect(runner.rollbackTransaction).not.toHaveBeenCalled()
    expect(sql).toContain('CREATE TABLE IF NOT EXISTS "box_billing_transitions"')
    expect(sql).toContain('"id" bigint GENERATED BY DEFAULT AS IDENTITY')
    expect(sql).toContain('CREATE INDEX IF NOT EXISTS "box_billing_transitions_pending_box_idx"')
    expect(sql).toContain('CREATE INDEX IF NOT EXISTS "box_billing_transitions_pending_shard_idx"')
    expect(sql).toContain('CREATE OR REPLACE FUNCTION set_box_billing_changed_at()')
    expect(sql).toContain('INSERT INTO "box_billing_transitions"')
    expect(sql).toContain('NEW."desiredState"')
    expect(sql).toContain('OLD."desiredState"')
    expect(sql).toContain('boundary := clock_timestamp()')
    expect(sql).toContain('boundary := GREATEST(boundary, OLD."billingChangedAt")')
    expect(sql).toContain('BEFORE INSERT OR UPDATE ON "box"')
    expect(sql).toContain('SET lock_timeout')
    expect((runner.query as jest.Mock).mock.calls.at(-1)?.[0]).toBe('RESET lock_timeout')
    expect(sql).not.toContain('ADD COLUMN IF NOT EXISTS "billingChangedAt"')
  })

  it('rolls back the whole trigger upgrade on failure', async () => {
    const runner = queryRunner('CREATE TRIGGER')

    await expect(new AddBoxBillingTransitionOutbox1786000500000().up(runner)).rejects.toThrow(
      'injected migration failure',
    )

    expect(runner.commitTransaction).not.toHaveBeenCalled()
    expect(runner.rollbackTransaction).toHaveBeenCalledTimes(1)
    expect(runner.query).toHaveBeenLastCalledWith('RESET lock_timeout')
  })

  it('restores the prior update-only trigger without removing prior migration state', async () => {
    const runner = queryRunner()

    await new AddBoxBillingTransitionOutbox1786000500000().down(runner)

    const sql = (runner.query as jest.Mock).mock.calls.map(([statement]) => statement).join('\n')
    const pendingGuard = (runner.query as jest.Mock).mock.calls.findIndex(([statement]) =>
      statement.includes('cannot remove billing transition outbox while unprocessed rows remain'),
    )
    const dropTable = (runner.query as jest.Mock).mock.calls.findIndex(([statement]) =>
      statement.includes('DROP TABLE IF EXISTS "box_billing_transitions"'),
    )
    expect(sql).toContain('DROP TABLE IF EXISTS "box_billing_transitions"')
    expect(pendingGuard).toBeGreaterThan(-1)
    expect(dropTable).toBeGreaterThan(pendingGuard)
    expect(sql).toContain('BEFORE UPDATE ON "box"')
    expect(sql).not.toContain('BEFORE INSERT OR UPDATE ON "box"')
    expect(sql).not.toContain('DROP COLUMN IF EXISTS "billingChangedAt"')
    expect(sql).not.toContain('DROP FUNCTION IF EXISTS set_box_billing_changed_at()')
    expect(runner.commitTransaction).toHaveBeenCalledTimes(1)
  })
})
