/*
 * Copyright 2026 BoxLite AI
 * SPDX-License-Identifier: AGPL-3.0
 */

import { MigrationInterface, QueryRunner } from 'typeorm'

/**
 * Upgrades billingChangedAt's last-write marker to an ordered transactional
 * outbox. This is intentionally separate from 1786000000000: environments
 * that already recorded that migration must still receive the upgrade.
 */
export class AddBoxBillingTransitionOutbox1786000500000 implements MigrationInterface {
  name = 'AddBoxBillingTransitionOutbox1786000500000'
  transaction = false

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`SET lock_timeout = '5s'`)
    await queryRunner.startTransaction()
    try {
      await queryRunner.query(`
        CREATE TABLE IF NOT EXISTS "box_billing_transitions" (
          "id" bigint GENERATED BY DEFAULT AS IDENTITY,
          "boxId" character varying NOT NULL,
          "organizationId" uuid NOT NULL,
          "region" character varying NOT NULL,
          "runnerId" uuid,
          "state" character varying NOT NULL,
          "desiredState" character varying NOT NULL,
          "cpu" double precision NOT NULL,
          "gpu" double precision NOT NULL,
          "mem" double precision NOT NULL,
          "disk" double precision NOT NULL,
          "pending" boolean NOT NULL,
          "occurredAt" TIMESTAMP WITH TIME ZONE NOT NULL,
          "processedAt" TIMESTAMP WITH TIME ZONE,
          CONSTRAINT "box_billing_transitions_id_pk" PRIMARY KEY ("id")
        )
      `)
      await queryRunner.query(`
        CREATE INDEX IF NOT EXISTS "box_billing_transitions_pending_box_idx"
          ON "box_billing_transitions" ("boxId", "id")
          WHERE "processedAt" IS NULL
      `)
      await queryRunner.query(`
        CREATE INDEX IF NOT EXISTS "box_billing_transitions_pending_shard_idx"
          ON "box_billing_transitions" ("runnerId", "id")
          WHERE "processedAt" IS NULL
      `)
      await queryRunner.query(`
        CREATE OR REPLACE FUNCTION set_box_billing_changed_at()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $function$
        DECLARE
          boundary TIMESTAMP WITH TIME ZONE;
          billing_changed boolean;
        BEGIN
          IF TG_OP = 'INSERT' THEN
            billing_changed := true;
          ELSE
            billing_changed := ROW(
              NEW."state",
              NEW."desiredState",
              NEW."cpu",
              NEW."gpu",
              NEW."mem",
              NEW."disk",
              NEW."organizationId",
              NEW."region"
            ) IS DISTINCT FROM ROW(
              OLD."state",
              OLD."desiredState",
              OLD."cpu",
              OLD."gpu",
              OLD."mem",
              OLD."disk",
              OLD."organizationId",
              OLD."region"
            );
          END IF;

          IF billing_changed THEN
            boundary := clock_timestamp();
            IF TG_OP <> 'INSERT' AND OLD."billingChangedAt" IS NOT NULL THEN
              boundary := GREATEST(boundary, OLD."billingChangedAt");
            END IF;
            NEW."billingChangedAt" := boundary;

            INSERT INTO "box_billing_transitions" (
              "boxId",
              "organizationId",
              "region",
              "runnerId",
              "state",
              "desiredState",
              "cpu",
              "gpu",
              "mem",
              "disk",
              "pending",
              "occurredAt"
            ) VALUES (
              NEW."id",
              NEW."organizationId",
              NEW."region",
              NEW."runnerId",
              NEW."state"::text,
              NEW."desiredState"::text,
              NEW."cpu",
              NEW."gpu",
              NEW."mem",
              NEW."disk",
              NEW."pending",
              boundary
            );
          ELSE
            NEW."billingChangedAt" := OLD."billingChangedAt";
          END IF;
          RETURN NEW;
        END;
        $function$
      `)
      await queryRunner.query(`DROP TRIGGER IF EXISTS "box_billing_changed_at_trigger" ON "box"`)
      await queryRunner.query(`
        CREATE TRIGGER "box_billing_changed_at_trigger"
          BEFORE INSERT OR UPDATE ON "box"
          FOR EACH ROW
          EXECUTE FUNCTION set_box_billing_changed_at()
      `)
      await queryRunner.commitTransaction()
    } catch (error) {
      await queryRunner.rollbackTransaction()
      throw error
    } finally {
      await queryRunner.query(`RESET lock_timeout`)
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`SET lock_timeout = '5s'`)
    await queryRunner.startTransaction()
    try {
      await queryRunner.query(`DROP TRIGGER IF EXISTS "box_billing_changed_at_trigger" ON "box"`)
      await queryRunner.query(`
        DO $migration$
        BEGIN
          IF EXISTS (
            SELECT 1
              FROM "box_billing_transitions"
             WHERE "processedAt" IS NULL
          ) THEN
            RAISE EXCEPTION USING
              ERRCODE = '55000',
              MESSAGE = 'cannot remove billing transition outbox while unprocessed rows remain';
          END IF;
        END;
        $migration$
      `)
      await queryRunner.query(`
        CREATE OR REPLACE FUNCTION set_box_billing_changed_at()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $function$
        BEGIN
          IF ROW(
            NEW."state",
            NEW."cpu",
            NEW."gpu",
            NEW."mem",
            NEW."disk",
            NEW."organizationId",
            NEW."region"
          ) IS DISTINCT FROM ROW(
            OLD."state",
            OLD."cpu",
            OLD."gpu",
            OLD."mem",
            OLD."disk",
            OLD."organizationId",
            OLD."region"
          ) THEN
            NEW."billingChangedAt" := statement_timestamp();
          ELSE
            NEW."billingChangedAt" := OLD."billingChangedAt";
          END IF;
          RETURN NEW;
        END;
        $function$
      `)
      await queryRunner.query(`
        CREATE TRIGGER "box_billing_changed_at_trigger"
          BEFORE UPDATE ON "box"
          FOR EACH ROW
          EXECUTE FUNCTION set_box_billing_changed_at()
      `)
      await queryRunner.query(`DROP TABLE IF EXISTS "box_billing_transitions"`)
      await queryRunner.commitTransaction()
    } catch (error) {
      await queryRunner.rollbackTransaction()
      throw error
    } finally {
      await queryRunner.query(`RESET lock_timeout`)
    }
  }
}
