BOXLITE_E2E_INSTANCE=three
BOXLITE_E2E_HEADLESS=true
BOXLITE_E2E_API_PORT=3201
BOXLITE_E2E_POSTGRES_PORT=55433
BOXLITE_E2E_REDIS_PORT=16380
BOXLITE_E2E_RUNNER_API_PORT=8082
BOXLITE_E2E_PROXY_PORT=4200
