/*
 * Copyright 2025 Daytona Platforms Inc.
 * Modified by BoxLite AI, 2025-2026
 * SPDX-License-Identifier: AGPL-3.0
 */

// Client-side twin of the server's default box-name generator, used only to fill
// the Create-Box name placeholder with a realistic sample ("cozy-otter") instead
// of a static hint. It is cosmetic: leaving the name blank still submits no name,
// so the server remains the source of truth for the actual name (and its per-org
// collision fallback). The word lists are duplicated verbatim from
// apps/api/src/box/utils/box-name-generator.ts — the dashboard consumes no
// name-suggestion endpoint, so keep the two lists in sync by hand.

const ADJECTIVES = [
  'agile',
  'amber',
  'astute',
  'bold',
  'bouncy',
  'brave',
  'breezy',
  'brilliant',
  'brisk',
  'calm',
  'cheery',
  'clever',
  'cosmic',
  'cozy',
  'crimson',
  'crisp',
  'dapper',
  'daring',
  'darting',
  'deft',
  'dreamy',
  'dusky',
  'eager',
  'fierce',
  'fluffy',
  'fresh',
  'gallant',
  'gentle',
  'gliding',
  'glossy',
  'golden',
  'hearty',
  'hovering',
  'hushed',
  'indigo',
  'intrepid',
  'ivory',
  'jade',
  'jaunty',
  'jolly',
  'jovial',
  'keen',
  'lively',
  'lofty',
  'lucid',
  'lunar',
  'mellow',
  'mighty',
  'mild',
  'mystic',
  'neat',
  'nebular',
  'nimble',
  'opal',
  'perky',
  'placid',
  'plucky',
  'polished',
  'prismatic',
  'quick',
  'radiant',
  'savvy',
  'serene',
  'sharp',
  'silver',
  'sleek',
  'snappy',
  'snug',
  'soaring',
  'solar',
  'sparkly',
  'starry',
  'swift',
  'tidy',
  'tranquil',
  'valiant',
  'vibrant',
  'vivid',
  'witty',
  'zippy',
] as const

const ANIMALS = [
  'alpaca',
  'badger',
  'bat',
  'bear',
  'beaver',
  'bee',
  'beluga',
  'bluebird',
  'bluejay',
  'bobcat',
  'bumblebee',
  'bunny',
  'butterfly',
  'calf',
  'canary',
  'capybara',
  'cardinal',
  'cat',
  'chameleon',
  'chick',
  'chickadee',
  'chinchilla',
  'chipmunk',
  'cockatiel',
  'corgi',
  'cottontail',
  'crab',
  'cub',
  'deer',
  'dolphin',
  'dove',
  'dragonfly',
  'duck',
  'duckling',
  'eagle',
  'falcon',
  'fawn',
  'ferret',
  'finch',
  'firefly',
  'flamingo',
  'fox',
  'frog',
  'gecko',
  'goldfinch',
  'goose',
  'gosling',
  'guppy',
  'hamster',
  'hare',
  'hawk',
  'hedgehog',
  'heron',
  'hummingbird',
  'joey',
  'kangaroo',
  'kit',
  'kitten',
  'koala',
  'ladybug',
  'lamb',
  'lemur',
  'llama',
  'lovebird',
  'lynx',
  'magpie',
  'manatee',
  'marmot',
  'meerkat',
  'mole',
  'mouse',
  'narwhal',
  'nightingale',
  'ocelot',
  'octopus',
  'otter',
  'owl',
  'owlet',
  'panda',
  'parakeet',
  'parrot',
  'peacock',
  'pelican',
  'penguin',
  'piglet',
  'platypus',
  'pony',
  'porpoise',
  'possum',
  'puffin',
  'pup',
  'puppy',
  'quokka',
  'rabbit',
  'raccoon',
  'raven',
  'robin',
  'salamander',
  'seahorse',
  'seal',
  'sheep',
  'sloth',
  'snail',
  'sparrow',
  'squirrel',
  'starfish',
  'stingray',
  'swallow',
  'swan',
  'tadpole',
  'tortoise',
  'toucan',
  'turtle',
  'wallaby',
  'walrus',
  'whale',
  'wolf',
  'wombat',
  'woodpecker',
  'wren',
] as const

function pick<T>(arr: readonly T[]): T {
  return arr[Math.floor(Math.random() * arr.length)]
}

/** Generate a sample default box name like `cozy-otter` (lowercase, hyphenated). */
export function generateBoxName(): string {
  return `${pick(ADJECTIVES)}-${pick(ANIMALS)}`
}
