/*
 * Copyright 2025 BoxLite AI
 * SPDX-License-Identifier: AGPL-3.0
 */

import { ApiProperty, ApiPropertyOptional, ApiSchema } from '@nestjs/swagger'
import { IsString, IsNotEmpty, MaxLength } from 'class-validator'

/**
 * Request body for issuing an SSH certificate.
 *
 * There is deliberately no private-key field. The caller generates the pair
 * locally and submits only the public half, so this API never has a user
 * private key to leak, log or lose.
 */
@ApiSchema({ name: 'CreateSshCertificateRequest' })
export class CreateSshCertificateRequestDto {
  @ApiProperty({
    name: 'public_key',
    description: 'Canonical OpenSSH public key line generated by the caller. Ed25519 only.',
    example: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAI...',
    maxLength: 8192,
  })
  @IsString()
  @IsNotEmpty()
  @MaxLength(8192)
  public_key: string
}

/**
 * Public certificate credential metadata.
 *
 * Every field here is safe to return, display and log: there is no user
 * private key and no CA private material, by construction.
 */
@ApiSchema({ name: 'SshCertificateCredential' })
export class SshCertificateCredentialDto {
  @ApiProperty({ description: 'Opaque credential ID and revoke target. Not an SSH authenticator.' })
  id: string

  @ApiProperty({ name: 'box_id' })
  box_id: string

  @ApiProperty({ description: 'The signed public OpenSSH user certificate.' })
  certificate: string

  @ApiProperty({ name: 'public_key' })
  public_key: string

  @ApiProperty({ description: 'SHA-256 fingerprint of the bound public key.' })
  fingerprint: string

  @ApiProperty({
    description:
      'Certificate serial, unique within the signing CA. A decimal uint64 string: the value can exceed 2^53 and would lose precision as a JSON number.',
    example: '1234567890123456789',
  })
  serial: string

  @ApiProperty({ name: 'ca_key_id', description: 'Non-secret signing key/version identifier.' })
  ca_key_id: string

  @ApiProperty({ name: 'valid_after' })
  valid_after: string

  @ApiProperty({ name: 'expires_at' })
  expires_at: string

  @ApiPropertyOptional({
    name: 'revoked_at',
    nullable: true,
    description:
      'Set once revoked. A revoked credential is no longer active, but an already-issued certificate stays usable until expires_at.',
  })
  revoked_at: string | null

  @ApiProperty({ description: 'Region-aware direct-tunnel hostname for guest port 22.' })
  host: string

  @ApiProperty({ example: 22 })
  port: number

  @ApiProperty({
    name: 'ssh_command',
    description:
      'SSH command template. <private-key> and <certificate> are placeholders the caller substitutes.',
  })
  ssh_command: string

  @ApiProperty({ name: 'proxy_command' })
  proxy_command: string

  @ApiPropertyOptional({
    name: 'known_hosts',
    description:
      'known_hosts line for the box host key. NOT YET POPULATED: the guest persists a stable host key but no path yet delivers it here, so this is currently always empty.',
  })
  known_hosts: string

  @ApiProperty({ name: 'created_at' })
  created_at: string

  @ApiProperty({ name: 'updated_at' })
  updated_at: string
}

@ApiSchema({ name: 'ListSshCertificatesResponse' })
export class ListSshCertificatesResponseDto {
  @ApiProperty({ type: [SshCertificateCredentialDto] })
  certificates: SshCertificateCredentialDto[]
}
