/*
 * Copyright 2025 Daytona Platforms Inc.
 * Modified by BoxLite AI, 2025-2026
 * SPDX-License-Identifier: AGPL-3.0
 */

export enum JobType {
  CREATE_BOX = 'CREATE_BOX',
  START_BOX = 'START_BOX',
  STOP_BOX = 'STOP_BOX',
  DESTROY_BOX = 'DESTROY_BOX',
  UPDATE_BOX_NETWORK_SETTINGS = 'UPDATE_BOX_NETWORK_SETTINGS',
  EXPORT_BOX = 'EXPORT_BOX',
  IMPORT_BOX = 'IMPORT_BOX',
  ROLLBACK_EXPORT_BOX = 'ROLLBACK_EXPORT_BOX',
  ROLLBACK_IMPORT_BOX = 'ROLLBACK_IMPORT_BOX',
  DISCARD_EXPORTED_BOX = 'DISCARD_EXPORTED_BOX',
}
