/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


type RegistriesAPI interface {

	/*
	CreateRegistryCredential Add a registry credential

	A login for a private registry. The password is stored where this API cannot read it back, and is never returned.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return RegistriesAPICreateRegistryCredentialRequest
	*/
	CreateRegistryCredential(ctx context.Context) RegistriesAPICreateRegistryCredentialRequest

	// CreateRegistryCredentialExecute executes the request
	//  @return RegistryCredential
	CreateRegistryCredentialExecute(r RegistriesAPICreateRegistryCredentialRequest) (*RegistryCredential, *http.Response, error)

	/*
	DeleteRegistryCredential Remove a registry credential

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id
	@return RegistriesAPIDeleteRegistryCredentialRequest
	*/
	DeleteRegistryCredential(ctx context.Context, id string) RegistriesAPIDeleteRegistryCredentialRequest

	// DeleteRegistryCredentialExecute executes the request
	DeleteRegistryCredentialExecute(r RegistriesAPIDeleteRegistryCredentialRequest) (*http.Response, error)

	/*
	ListRegistryCredentials List registry credentials

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return RegistriesAPIListRegistryCredentialsRequest
	*/
	ListRegistryCredentials(ctx context.Context) RegistriesAPIListRegistryCredentialsRequest

	// ListRegistryCredentialsExecute executes the request
	//  @return []RegistryCredential
	ListRegistryCredentialsExecute(r RegistriesAPIListRegistryCredentialsRequest) ([]RegistryCredential, *http.Response, error)
}

// RegistriesAPIService RegistriesAPI service
type RegistriesAPIService service

type RegistriesAPICreateRegistryCredentialRequest struct {
	ctx context.Context
	ApiService RegistriesAPI
	createRegistryCredential *CreateRegistryCredential
	xBoxLiteOrganizationID *string
}

func (r RegistriesAPICreateRegistryCredentialRequest) CreateRegistryCredential(createRegistryCredential CreateRegistryCredential) RegistriesAPICreateRegistryCredentialRequest {
	r.createRegistryCredential = &createRegistryCredential
	return r
}

// Use with JWT to specify the organization ID
func (r RegistriesAPICreateRegistryCredentialRequest) XBoxLiteOrganizationID(xBoxLiteOrganizationID string) RegistriesAPICreateRegistryCredentialRequest {
	r.xBoxLiteOrganizationID = &xBoxLiteOrganizationID
	return r
}

func (r RegistriesAPICreateRegistryCredentialRequest) Execute() (*RegistryCredential, *http.Response, error) {
	return r.ApiService.CreateRegistryCredentialExecute(r)
}

/*
CreateRegistryCredential Add a registry credential

A login for a private registry. The password is stored where this API cannot read it back, and is never returned.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return RegistriesAPICreateRegistryCredentialRequest
*/
func (a *RegistriesAPIService) CreateRegistryCredential(ctx context.Context) RegistriesAPICreateRegistryCredentialRequest {
	return RegistriesAPICreateRegistryCredentialRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return RegistryCredential
func (a *RegistriesAPIService) CreateRegistryCredentialExecute(r RegistriesAPICreateRegistryCredentialRequest) (*RegistryCredential, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *RegistryCredential
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "RegistriesAPIService.CreateRegistryCredential")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/registries"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.createRegistryCredential == nil {
		return localVarReturnValue, nil, reportError("createRegistryCredential is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xBoxLiteOrganizationID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-BoxLite-Organization-ID", r.xBoxLiteOrganizationID, "simple", "")
	}
	// body params
	localVarPostBody = r.createRegistryCredential
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type RegistriesAPIDeleteRegistryCredentialRequest struct {
	ctx context.Context
	ApiService RegistriesAPI
	id string
	xBoxLiteOrganizationID *string
}

// Use with JWT to specify the organization ID
func (r RegistriesAPIDeleteRegistryCredentialRequest) XBoxLiteOrganizationID(xBoxLiteOrganizationID string) RegistriesAPIDeleteRegistryCredentialRequest {
	r.xBoxLiteOrganizationID = &xBoxLiteOrganizationID
	return r
}

func (r RegistriesAPIDeleteRegistryCredentialRequest) Execute() (*http.Response, error) {
	return r.ApiService.DeleteRegistryCredentialExecute(r)
}

/*
DeleteRegistryCredential Remove a registry credential

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id
 @return RegistriesAPIDeleteRegistryCredentialRequest
*/
func (a *RegistriesAPIService) DeleteRegistryCredential(ctx context.Context, id string) RegistriesAPIDeleteRegistryCredentialRequest {
	return RegistriesAPIDeleteRegistryCredentialRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
	}
}

// Execute executes the request
func (a *RegistriesAPIService) DeleteRegistryCredentialExecute(r RegistriesAPIDeleteRegistryCredentialRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "RegistriesAPIService.DeleteRegistryCredential")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/registries/{id}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xBoxLiteOrganizationID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-BoxLite-Organization-ID", r.xBoxLiteOrganizationID, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type RegistriesAPIListRegistryCredentialsRequest struct {
	ctx context.Context
	ApiService RegistriesAPI
	xBoxLiteOrganizationID *string
}

// Use with JWT to specify the organization ID
func (r RegistriesAPIListRegistryCredentialsRequest) XBoxLiteOrganizationID(xBoxLiteOrganizationID string) RegistriesAPIListRegistryCredentialsRequest {
	r.xBoxLiteOrganizationID = &xBoxLiteOrganizationID
	return r
}

func (r RegistriesAPIListRegistryCredentialsRequest) Execute() ([]RegistryCredential, *http.Response, error) {
	return r.ApiService.ListRegistryCredentialsExecute(r)
}

/*
ListRegistryCredentials List registry credentials

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return RegistriesAPIListRegistryCredentialsRequest
*/
func (a *RegistriesAPIService) ListRegistryCredentials(ctx context.Context) RegistriesAPIListRegistryCredentialsRequest {
	return RegistriesAPIListRegistryCredentialsRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return []RegistryCredential
func (a *RegistriesAPIService) ListRegistryCredentialsExecute(r RegistriesAPIListRegistryCredentialsRequest) ([]RegistryCredential, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  []RegistryCredential
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "RegistriesAPIService.ListRegistryCredentials")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/registries"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xBoxLiteOrganizationID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-BoxLite-Organization-ID", r.xBoxLiteOrganizationID, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
