/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


type InternalBillingAPI interface {

	/*
	BillingControllerFetchArchived Fetch one archived usage period by id

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param periodId
	@return InternalBillingAPIBillingControllerFetchArchivedRequest
	*/
	BillingControllerFetchArchived(ctx context.Context, periodId string) InternalBillingAPIBillingControllerFetchArchivedRequest

	// BillingControllerFetchArchivedExecute executes the request
	//  @return BillingPeriodDto
	BillingControllerFetchArchivedExecute(r InternalBillingAPIBillingControllerFetchArchivedRequest) (*BillingPeriodDto, *http.Response, error)

	/*
	BillingControllerListOpenForOrganization List still-running (hot table) usage periods for an organization

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param organizationId
	@return InternalBillingAPIBillingControllerListOpenForOrganizationRequest
	*/
	BillingControllerListOpenForOrganization(ctx context.Context, organizationId string) InternalBillingAPIBillingControllerListOpenForOrganizationRequest

	// BillingControllerListOpenForOrganizationExecute executes the request
	//  @return BillingPeriodListDto
	BillingControllerListOpenForOrganizationExecute(r InternalBillingAPIBillingControllerListOpenForOrganizationRequest) (*BillingPeriodListDto, *http.Response, error)

	/*
	BillingControllerListUnbilled List unbilled archived usage periods, oldest endAt first

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return InternalBillingAPIBillingControllerListUnbilledRequest
	*/
	BillingControllerListUnbilled(ctx context.Context) InternalBillingAPIBillingControllerListUnbilledRequest

	// BillingControllerListUnbilledExecute executes the request
	//  @return BillingPeriodListDto
	BillingControllerListUnbilledExecute(r InternalBillingAPIBillingControllerListUnbilledRequest) (*BillingPeriodListDto, *http.Response, error)

	/*
	BillingControllerMarkBilled Compare-and-swap the period from unbilled to billed

	Returns marked=false if the period was already billed or does not exist -- never an error.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param periodId
	@return InternalBillingAPIBillingControllerMarkBilledRequest
	*/
	BillingControllerMarkBilled(ctx context.Context, periodId string) InternalBillingAPIBillingControllerMarkBilledRequest

	// BillingControllerMarkBilledExecute executes the request
	//  @return MarkBilledResultDto
	BillingControllerMarkBilledExecute(r InternalBillingAPIBillingControllerMarkBilledRequest) (*MarkBilledResultDto, *http.Response, error)
}

// InternalBillingAPIService InternalBillingAPI service
type InternalBillingAPIService service

type InternalBillingAPIBillingControllerFetchArchivedRequest struct {
	ctx context.Context
	ApiService InternalBillingAPI
	periodId string
}

func (r InternalBillingAPIBillingControllerFetchArchivedRequest) Execute() (*BillingPeriodDto, *http.Response, error) {
	return r.ApiService.BillingControllerFetchArchivedExecute(r)
}

/*
BillingControllerFetchArchived Fetch one archived usage period by id

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param periodId
 @return InternalBillingAPIBillingControllerFetchArchivedRequest
*/
func (a *InternalBillingAPIService) BillingControllerFetchArchived(ctx context.Context, periodId string) InternalBillingAPIBillingControllerFetchArchivedRequest {
	return InternalBillingAPIBillingControllerFetchArchivedRequest{
		ApiService: a,
		ctx: ctx,
		periodId: periodId,
	}
}

// Execute executes the request
//  @return BillingPeriodDto
func (a *InternalBillingAPIService) BillingControllerFetchArchivedExecute(r InternalBillingAPIBillingControllerFetchArchivedRequest) (*BillingPeriodDto, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *BillingPeriodDto
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "InternalBillingAPIService.BillingControllerFetchArchived")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/internal/billing/periods/{periodId}"
	localVarPath = strings.Replace(localVarPath, "{"+"periodId"+"}", url.PathEscape(parameterValueToString(r.periodId, "periodId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type InternalBillingAPIBillingControllerListOpenForOrganizationRequest struct {
	ctx context.Context
	ApiService InternalBillingAPI
	organizationId string
}

func (r InternalBillingAPIBillingControllerListOpenForOrganizationRequest) Execute() (*BillingPeriodListDto, *http.Response, error) {
	return r.ApiService.BillingControllerListOpenForOrganizationExecute(r)
}

/*
BillingControllerListOpenForOrganization List still-running (hot table) usage periods for an organization

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param organizationId
 @return InternalBillingAPIBillingControllerListOpenForOrganizationRequest
*/
func (a *InternalBillingAPIService) BillingControllerListOpenForOrganization(ctx context.Context, organizationId string) InternalBillingAPIBillingControllerListOpenForOrganizationRequest {
	return InternalBillingAPIBillingControllerListOpenForOrganizationRequest{
		ApiService: a,
		ctx: ctx,
		organizationId: organizationId,
	}
}

// Execute executes the request
//  @return BillingPeriodListDto
func (a *InternalBillingAPIService) BillingControllerListOpenForOrganizationExecute(r InternalBillingAPIBillingControllerListOpenForOrganizationRequest) (*BillingPeriodListDto, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *BillingPeriodListDto
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "InternalBillingAPIService.BillingControllerListOpenForOrganization")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/internal/billing/organizations/{organizationId}/open-periods"
	localVarPath = strings.Replace(localVarPath, "{"+"organizationId"+"}", url.PathEscape(parameterValueToString(r.organizationId, "organizationId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type InternalBillingAPIBillingControllerListUnbilledRequest struct {
	ctx context.Context
	ApiService InternalBillingAPI
	limit *float32
}

func (r InternalBillingAPIBillingControllerListUnbilledRequest) Limit(limit float32) InternalBillingAPIBillingControllerListUnbilledRequest {
	r.limit = &limit
	return r
}

func (r InternalBillingAPIBillingControllerListUnbilledRequest) Execute() (*BillingPeriodListDto, *http.Response, error) {
	return r.ApiService.BillingControllerListUnbilledExecute(r)
}

/*
BillingControllerListUnbilled List unbilled archived usage periods, oldest endAt first

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return InternalBillingAPIBillingControllerListUnbilledRequest
*/
func (a *InternalBillingAPIService) BillingControllerListUnbilled(ctx context.Context) InternalBillingAPIBillingControllerListUnbilledRequest {
	return InternalBillingAPIBillingControllerListUnbilledRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return BillingPeriodListDto
func (a *InternalBillingAPIService) BillingControllerListUnbilledExecute(r InternalBillingAPIBillingControllerListUnbilledRequest) (*BillingPeriodListDto, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *BillingPeriodListDto
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "InternalBillingAPIService.BillingControllerListUnbilled")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/internal/billing/unbilled-periods"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.limit == nil {
		return localVarReturnValue, nil, reportError("limit is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "limit", r.limit, "form", "")
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type InternalBillingAPIBillingControllerMarkBilledRequest struct {
	ctx context.Context
	ApiService InternalBillingAPI
	periodId string
}

func (r InternalBillingAPIBillingControllerMarkBilledRequest) Execute() (*MarkBilledResultDto, *http.Response, error) {
	return r.ApiService.BillingControllerMarkBilledExecute(r)
}

/*
BillingControllerMarkBilled Compare-and-swap the period from unbilled to billed

Returns marked=false if the period was already billed or does not exist -- never an error.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param periodId
 @return InternalBillingAPIBillingControllerMarkBilledRequest
*/
func (a *InternalBillingAPIService) BillingControllerMarkBilled(ctx context.Context, periodId string) InternalBillingAPIBillingControllerMarkBilledRequest {
	return InternalBillingAPIBillingControllerMarkBilledRequest{
		ApiService: a,
		ctx: ctx,
		periodId: periodId,
	}
}

// Execute executes the request
//  @return MarkBilledResultDto
func (a *InternalBillingAPIService) BillingControllerMarkBilledExecute(r InternalBillingAPIBillingControllerMarkBilledRequest) (*MarkBilledResultDto, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *MarkBilledResultDto
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "InternalBillingAPIService.BillingControllerMarkBilled")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/internal/billing/periods/{periodId}/mark-billed"
	localVarPath = strings.Replace(localVarPath, "{"+"periodId"+"}", url.PathEscape(parameterValueToString(r.periodId, "periodId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
