/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the OrganizationReferralCode type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizationReferralCode{}

// OrganizationReferralCode struct for OrganizationReferralCode
type OrganizationReferralCode struct {
	OrganizationId string `json:"organizationId"`
	ReferralCode string `json:"referralCode" validate:"regexp=^[ABCDEFGHJKLMNPQRSTUVWXYZ23456789]{10}$"`
	AdditionalProperties map[string]interface{}
}

type _OrganizationReferralCode OrganizationReferralCode

// NewOrganizationReferralCode instantiates a new OrganizationReferralCode object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationReferralCode(organizationId string, referralCode string) *OrganizationReferralCode {
	this := OrganizationReferralCode{}
	this.OrganizationId = organizationId
	this.ReferralCode = referralCode
	return &this
}

// NewOrganizationReferralCodeWithDefaults instantiates a new OrganizationReferralCode object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationReferralCodeWithDefaults() *OrganizationReferralCode {
	this := OrganizationReferralCode{}
	return &this
}

// GetOrganizationId returns the OrganizationId field value
func (o *OrganizationReferralCode) GetOrganizationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value
// and a boolean to check if the value has been set.
func (o *OrganizationReferralCode) GetOrganizationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrganizationId, true
}

// SetOrganizationId sets field value
func (o *OrganizationReferralCode) SetOrganizationId(v string) {
	o.OrganizationId = v
}

// GetReferralCode returns the ReferralCode field value
func (o *OrganizationReferralCode) GetReferralCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ReferralCode
}

// GetReferralCodeOk returns a tuple with the ReferralCode field value
// and a boolean to check if the value has been set.
func (o *OrganizationReferralCode) GetReferralCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReferralCode, true
}

// SetReferralCode sets field value
func (o *OrganizationReferralCode) SetReferralCode(v string) {
	o.ReferralCode = v
}

func (o OrganizationReferralCode) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizationReferralCode) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["organizationId"] = o.OrganizationId
	toSerialize["referralCode"] = o.ReferralCode

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *OrganizationReferralCode) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"organizationId",
		"referralCode",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrganizationReferralCode := _OrganizationReferralCode{}

	err = json.Unmarshal(data, &varOrganizationReferralCode)

	if err != nil {
		return err
	}

	*o = OrganizationReferralCode(varOrganizationReferralCode)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "organizationId")
		delete(additionalProperties, "referralCode")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableOrganizationReferralCode struct {
	value *OrganizationReferralCode
	isSet bool
}

func (v NullableOrganizationReferralCode) Get() *OrganizationReferralCode {
	return v.value
}

func (v *NullableOrganizationReferralCode) Set(val *OrganizationReferralCode) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationReferralCode) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationReferralCode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationReferralCode(val *OrganizationReferralCode) *NullableOrganizationReferralCode {
	return &NullableOrganizationReferralCode{value: val, isSet: true}
}

func (v NullableOrganizationReferralCode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationReferralCode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


