/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the SupportedImage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SupportedImage{}

// SupportedImage struct for SupportedImage
type SupportedImage struct {
	// Stable image selector accepted by the box-create API
	Name string `json:"name"`
	// Exact OCI image reference resolved by the box-create API
	Ref string `json:"ref"`
	AdditionalProperties map[string]interface{}
}

type _SupportedImage SupportedImage

// NewSupportedImage instantiates a new SupportedImage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSupportedImage(name string, ref string) *SupportedImage {
	this := SupportedImage{}
	this.Name = name
	this.Ref = ref
	return &this
}

// NewSupportedImageWithDefaults instantiates a new SupportedImage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSupportedImageWithDefaults() *SupportedImage {
	this := SupportedImage{}
	return &this
}

// GetName returns the Name field value
func (o *SupportedImage) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SupportedImage) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SupportedImage) SetName(v string) {
	o.Name = v
}

// GetRef returns the Ref field value
func (o *SupportedImage) GetRef() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Ref
}

// GetRefOk returns a tuple with the Ref field value
// and a boolean to check if the value has been set.
func (o *SupportedImage) GetRefOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ref, true
}

// SetRef sets field value
func (o *SupportedImage) SetRef(v string) {
	o.Ref = v
}

func (o SupportedImage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SupportedImage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["ref"] = o.Ref

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SupportedImage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"ref",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSupportedImage := _SupportedImage{}

	err = json.Unmarshal(data, &varSupportedImage)

	if err != nil {
		return err
	}

	*o = SupportedImage(varSupportedImage)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "ref")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSupportedImage struct {
	value *SupportedImage
	isSet bool
}

func (v NullableSupportedImage) Get() *SupportedImage {
	return v.value
}

func (v *NullableSupportedImage) Set(val *SupportedImage) {
	v.value = val
	v.isSet = true
}

func (v NullableSupportedImage) IsSet() bool {
	return v.isSet
}

func (v *NullableSupportedImage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSupportedImage(val *SupportedImage) *NullableSupportedImage {
	return &NullableSupportedImage{value: val, isSet: true}
}

func (v NullableSupportedImage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSupportedImage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
