/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
)

// JobType The type of the job
type JobType string

// List of JobType
const (
	JOBTYPE_CREATE_BOX JobType = "CREATE_BOX"
	JOBTYPE_START_BOX JobType = "START_BOX"
	JOBTYPE_STOP_BOX JobType = "STOP_BOX"
	JOBTYPE_DESTROY_BOX JobType = "DESTROY_BOX"
	JOBTYPE_UPDATE_BOX_NETWORK_SETTINGS JobType = "UPDATE_BOX_NETWORK_SETTINGS"
	JOBTYPE_EXPORT_BOX JobType = "EXPORT_BOX"
	JOBTYPE_IMPORT_BOX JobType = "IMPORT_BOX"
	JOBTYPE_ROLLBACK_EXPORT_BOX JobType = "ROLLBACK_EXPORT_BOX"
	JOBTYPE_ROLLBACK_IMPORT_BOX JobType = "ROLLBACK_IMPORT_BOX"
	JOBTYPE_DISCARD_EXPORTED_BOX JobType = "DISCARD_EXPORTED_BOX"
	JOBTYPE_UNKNOWN_DEFAULT_OPEN_API JobType = "unknown_default_open_api"
)

// All allowed values of JobType enum
var AllowedJobTypeEnumValues = []JobType{
	"CREATE_BOX",
	"START_BOX",
	"STOP_BOX",
	"DESTROY_BOX",
	"UPDATE_BOX_NETWORK_SETTINGS",
	"EXPORT_BOX",
	"IMPORT_BOX",
	"ROLLBACK_EXPORT_BOX",
	"ROLLBACK_IMPORT_BOX",
	"DISCARD_EXPORTED_BOX",
	"unknown_default_open_api",
}

func (v *JobType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := JobType(value)
	for _, existing := range AllowedJobTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = JOBTYPE_UNKNOWN_DEFAULT_OPEN_API
	return nil
}

// NewJobTypeFromValue returns a pointer to a valid JobType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewJobTypeFromValue(v string) (*JobType, error) {
	ev := JobType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		enumValue := JOBTYPE_UNKNOWN_DEFAULT_OPEN_API
		return &enumValue, nil
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v JobType) IsValid() bool {
	for _, existing := range AllowedJobTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to JobType value
func (v JobType) Ptr() *JobType {
	return &v
}

type NullableJobType struct {
	value *JobType
	isSet bool
}

func (v NullableJobType) Get() *JobType {
	return v.value
}

func (v *NullableJobType) Set(val *JobType) {
	v.value = val
	v.isSet = true
}

func (v NullableJobType) IsSet() bool {
	return v.isSet
}

func (v *NullableJobType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobType(val *JobType) *NullableJobType {
	return &NullableJobType{value: val, isSet: true}
}

func (v NullableJobType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
