/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the UpdateOrganizationConcurrencyEntitlementDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateOrganizationConcurrencyEntitlementDto{}

// UpdateOrganizationConcurrencyEntitlementDto struct for UpdateOrganizationConcurrencyEntitlementDto
type UpdateOrganizationConcurrencyEntitlementDto struct {
	// Maximum concurrent boxes. Null means unlimited.
	MaxConcurrentBoxes NullableFloat32 `json:"maxConcurrentBoxes"`
	AdditionalProperties map[string]interface{}
}

type _UpdateOrganizationConcurrencyEntitlementDto UpdateOrganizationConcurrencyEntitlementDto

// NewUpdateOrganizationConcurrencyEntitlementDto instantiates a new UpdateOrganizationConcurrencyEntitlementDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateOrganizationConcurrencyEntitlementDto(maxConcurrentBoxes NullableFloat32) *UpdateOrganizationConcurrencyEntitlementDto {
	this := UpdateOrganizationConcurrencyEntitlementDto{}
	this.MaxConcurrentBoxes = maxConcurrentBoxes
	return &this
}

// NewUpdateOrganizationConcurrencyEntitlementDtoWithDefaults instantiates a new UpdateOrganizationConcurrencyEntitlementDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateOrganizationConcurrencyEntitlementDtoWithDefaults() *UpdateOrganizationConcurrencyEntitlementDto {
	this := UpdateOrganizationConcurrencyEntitlementDto{}
	return &this
}

// GetMaxConcurrentBoxes returns the MaxConcurrentBoxes field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *UpdateOrganizationConcurrencyEntitlementDto) GetMaxConcurrentBoxes() float32 {
	if o == nil || o.MaxConcurrentBoxes.Get() == nil {
		var ret float32
		return ret
	}

	return *o.MaxConcurrentBoxes.Get()
}

// GetMaxConcurrentBoxesOk returns a tuple with the MaxConcurrentBoxes field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateOrganizationConcurrencyEntitlementDto) GetMaxConcurrentBoxesOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MaxConcurrentBoxes.Get(), o.MaxConcurrentBoxes.IsSet()
}

// SetMaxConcurrentBoxes sets field value
func (o *UpdateOrganizationConcurrencyEntitlementDto) SetMaxConcurrentBoxes(v float32) {
	o.MaxConcurrentBoxes.Set(&v)
}

func (o UpdateOrganizationConcurrencyEntitlementDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateOrganizationConcurrencyEntitlementDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["maxConcurrentBoxes"] = o.MaxConcurrentBoxes.Get()

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateOrganizationConcurrencyEntitlementDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"maxConcurrentBoxes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateOrganizationConcurrencyEntitlementDto := _UpdateOrganizationConcurrencyEntitlementDto{}

	err = json.Unmarshal(data, &varUpdateOrganizationConcurrencyEntitlementDto)

	if err != nil {
		return err
	}

	*o = UpdateOrganizationConcurrencyEntitlementDto(varUpdateOrganizationConcurrencyEntitlementDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "maxConcurrentBoxes")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateOrganizationConcurrencyEntitlementDto struct {
	value *UpdateOrganizationConcurrencyEntitlementDto
	isSet bool
}

func (v NullableUpdateOrganizationConcurrencyEntitlementDto) Get() *UpdateOrganizationConcurrencyEntitlementDto {
	return v.value
}

func (v *NullableUpdateOrganizationConcurrencyEntitlementDto) Set(val *UpdateOrganizationConcurrencyEntitlementDto) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateOrganizationConcurrencyEntitlementDto) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateOrganizationConcurrencyEntitlementDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateOrganizationConcurrencyEntitlementDto(val *UpdateOrganizationConcurrencyEntitlementDto) *NullableUpdateOrganizationConcurrencyEntitlementDto {
	return &NullableUpdateOrganizationConcurrencyEntitlementDto{value: val, isSet: true}
}

func (v NullableUpdateOrganizationConcurrencyEntitlementDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateOrganizationConcurrencyEntitlementDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


