/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the OrganizationConcurrencyDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizationConcurrencyDto{}

// OrganizationConcurrencyDto struct for OrganizationConcurrencyDto
type OrganizationConcurrencyDto struct {
	// Boxes occupying a concurrency slot now
	Current float32 `json:"current"`
	// Effective concurrency entitlement. Null means unlimited.
	Limit NullableFloat32 `json:"limit"`
	// Concurrency changes during the requested rolling window
	Points []OrganizationConcurrencyPointDto `json:"points"`
	AdditionalProperties map[string]interface{}
}

type _OrganizationConcurrencyDto OrganizationConcurrencyDto

// NewOrganizationConcurrencyDto instantiates a new OrganizationConcurrencyDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationConcurrencyDto(current float32, limit NullableFloat32, points []OrganizationConcurrencyPointDto) *OrganizationConcurrencyDto {
	this := OrganizationConcurrencyDto{}
	this.Current = current
	this.Limit = limit
	this.Points = points
	return &this
}

// NewOrganizationConcurrencyDtoWithDefaults instantiates a new OrganizationConcurrencyDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationConcurrencyDtoWithDefaults() *OrganizationConcurrencyDto {
	this := OrganizationConcurrencyDto{}
	return &this
}

// GetCurrent returns the Current field value
func (o *OrganizationConcurrencyDto) GetCurrent() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Current
}

// GetCurrentOk returns a tuple with the Current field value
// and a boolean to check if the value has been set.
func (o *OrganizationConcurrencyDto) GetCurrentOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Current, true
}

// SetCurrent sets field value
func (o *OrganizationConcurrencyDto) SetCurrent(v float32) {
	o.Current = v
}

// GetLimit returns the Limit field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *OrganizationConcurrencyDto) GetLimit() float32 {
	if o == nil || o.Limit.Get() == nil {
		var ret float32
		return ret
	}

	return *o.Limit.Get()
}

// GetLimitOk returns a tuple with the Limit field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OrganizationConcurrencyDto) GetLimitOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Limit.Get(), o.Limit.IsSet()
}

// SetLimit sets field value
func (o *OrganizationConcurrencyDto) SetLimit(v float32) {
	o.Limit.Set(&v)
}

// GetPoints returns the Points field value
func (o *OrganizationConcurrencyDto) GetPoints() []OrganizationConcurrencyPointDto {
	if o == nil {
		var ret []OrganizationConcurrencyPointDto
		return ret
	}

	return o.Points
}

// GetPointsOk returns a tuple with the Points field value
// and a boolean to check if the value has been set.
func (o *OrganizationConcurrencyDto) GetPointsOk() ([]OrganizationConcurrencyPointDto, bool) {
	if o == nil {
		return nil, false
	}
	return o.Points, true
}

// SetPoints sets field value
func (o *OrganizationConcurrencyDto) SetPoints(v []OrganizationConcurrencyPointDto) {
	o.Points = v
}

func (o OrganizationConcurrencyDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizationConcurrencyDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["current"] = o.Current
	toSerialize["limit"] = o.Limit.Get()
	toSerialize["points"] = o.Points

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *OrganizationConcurrencyDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"current",
		"limit",
		"points",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrganizationConcurrencyDto := _OrganizationConcurrencyDto{}

	err = json.Unmarshal(data, &varOrganizationConcurrencyDto)

	if err != nil {
		return err
	}

	*o = OrganizationConcurrencyDto(varOrganizationConcurrencyDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "current")
		delete(additionalProperties, "limit")
		delete(additionalProperties, "points")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableOrganizationConcurrencyDto struct {
	value *OrganizationConcurrencyDto
	isSet bool
}

func (v NullableOrganizationConcurrencyDto) Get() *OrganizationConcurrencyDto {
	return v.value
}

func (v *NullableOrganizationConcurrencyDto) Set(val *OrganizationConcurrencyDto) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationConcurrencyDto) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationConcurrencyDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationConcurrencyDto(val *OrganizationConcurrencyDto) *NullableOrganizationConcurrencyDto {
	return &NullableOrganizationConcurrencyDto{value: val, isSet: true}
}

func (v NullableOrganizationConcurrencyDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationConcurrencyDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


