/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the RunnerRegistryCredential type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RunnerRegistryCredential{}

// RunnerRegistryCredential struct for RunnerRegistryCredential
type RunnerRegistryCredential struct {
	Kind RegistryCredentialKind `json:"kind"`
	// Username the registry expects
	Username string `json:"username"`
	// Secret Manager version holding the password
	SecretVersion string `json:"secretVersion"`
	AdditionalProperties map[string]interface{}
}

type _RunnerRegistryCredential RunnerRegistryCredential

// NewRunnerRegistryCredential instantiates a new RunnerRegistryCredential object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRunnerRegistryCredential(kind RegistryCredentialKind, username string, secretVersion string) *RunnerRegistryCredential {
	this := RunnerRegistryCredential{}
	this.Kind = kind
	this.Username = username
	this.SecretVersion = secretVersion
	return &this
}

// NewRunnerRegistryCredentialWithDefaults instantiates a new RunnerRegistryCredential object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRunnerRegistryCredentialWithDefaults() *RunnerRegistryCredential {
	this := RunnerRegistryCredential{}
	return &this
}

// GetKind returns the Kind field value
func (o *RunnerRegistryCredential) GetKind() RegistryCredentialKind {
	if o == nil {
		var ret RegistryCredentialKind
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *RunnerRegistryCredential) GetKindOk() (*RegistryCredentialKind, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *RunnerRegistryCredential) SetKind(v RegistryCredentialKind) {
	o.Kind = v
}

// GetUsername returns the Username field value
func (o *RunnerRegistryCredential) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *RunnerRegistryCredential) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *RunnerRegistryCredential) SetUsername(v string) {
	o.Username = v
}

// GetSecretVersion returns the SecretVersion field value
func (o *RunnerRegistryCredential) GetSecretVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SecretVersion
}

// GetSecretVersionOk returns a tuple with the SecretVersion field value
// and a boolean to check if the value has been set.
func (o *RunnerRegistryCredential) GetSecretVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SecretVersion, true
}

// SetSecretVersion sets field value
func (o *RunnerRegistryCredential) SetSecretVersion(v string) {
	o.SecretVersion = v
}

func (o RunnerRegistryCredential) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RunnerRegistryCredential) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["kind"] = o.Kind
	toSerialize["username"] = o.Username
	toSerialize["secretVersion"] = o.SecretVersion

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RunnerRegistryCredential) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"kind",
		"username",
		"secretVersion",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRunnerRegistryCredential := _RunnerRegistryCredential{}

	err = json.Unmarshal(data, &varRunnerRegistryCredential)

	if err != nil {
		return err
	}

	*o = RunnerRegistryCredential(varRunnerRegistryCredential)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "kind")
		delete(additionalProperties, "username")
		delete(additionalProperties, "secretVersion")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRunnerRegistryCredential struct {
	value *RunnerRegistryCredential
	isSet bool
}

func (v NullableRunnerRegistryCredential) Get() *RunnerRegistryCredential {
	return v.value
}

func (v *NullableRunnerRegistryCredential) Set(val *RunnerRegistryCredential) {
	v.value = val
	v.isSet = true
}

func (v NullableRunnerRegistryCredential) IsSet() bool {
	return v.isSet
}

func (v *NullableRunnerRegistryCredential) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRunnerRegistryCredential(val *RunnerRegistryCredential) *NullableRunnerRegistryCredential {
	return &NullableRunnerRegistryCredential{value: val, isSet: true}
}

func (v NullableRunnerRegistryCredential) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRunnerRegistryCredential) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


