/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the BillingPeriodDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BillingPeriodDto{}

// BillingPeriodDto struct for BillingPeriodDto
type BillingPeriodDto struct {
	PeriodId string `json:"periodId"`
	BoxId string `json:"boxId"`
	OrganizationId NullableString `json:"organizationId"`
	Region string `json:"region"`
	StartAt string `json:"startAt"`
	EndAt NullableString `json:"endAt"`
	Cpu float32 `json:"cpu"`
	Gpu float32 `json:"gpu"`
	Mem float32 `json:"mem"`
	Disk float32 `json:"disk"`
	AdditionalProperties map[string]interface{}
}

type _BillingPeriodDto BillingPeriodDto

// NewBillingPeriodDto instantiates a new BillingPeriodDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBillingPeriodDto(periodId string, boxId string, organizationId NullableString, region string, startAt string, endAt NullableString, cpu float32, gpu float32, mem float32, disk float32) *BillingPeriodDto {
	this := BillingPeriodDto{}
	this.PeriodId = periodId
	this.BoxId = boxId
	this.OrganizationId = organizationId
	this.Region = region
	this.StartAt = startAt
	this.EndAt = endAt
	this.Cpu = cpu
	this.Gpu = gpu
	this.Mem = mem
	this.Disk = disk
	return &this
}

// NewBillingPeriodDtoWithDefaults instantiates a new BillingPeriodDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBillingPeriodDtoWithDefaults() *BillingPeriodDto {
	this := BillingPeriodDto{}
	return &this
}

// GetPeriodId returns the PeriodId field value
func (o *BillingPeriodDto) GetPeriodId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PeriodId
}

// GetPeriodIdOk returns a tuple with the PeriodId field value
// and a boolean to check if the value has been set.
func (o *BillingPeriodDto) GetPeriodIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PeriodId, true
}

// SetPeriodId sets field value
func (o *BillingPeriodDto) SetPeriodId(v string) {
	o.PeriodId = v
}

// GetBoxId returns the BoxId field value
func (o *BillingPeriodDto) GetBoxId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BoxId
}

// GetBoxIdOk returns a tuple with the BoxId field value
// and a boolean to check if the value has been set.
func (o *BillingPeriodDto) GetBoxIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BoxId, true
}

// SetBoxId sets field value
func (o *BillingPeriodDto) SetBoxId(v string) {
	o.BoxId = v
}

// GetOrganizationId returns the OrganizationId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *BillingPeriodDto) GetOrganizationId() string {
	if o == nil || o.OrganizationId.Get() == nil {
		var ret string
		return ret
	}

	return *o.OrganizationId.Get()
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BillingPeriodDto) GetOrganizationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OrganizationId.Get(), o.OrganizationId.IsSet()
}

// SetOrganizationId sets field value
func (o *BillingPeriodDto) SetOrganizationId(v string) {
	o.OrganizationId.Set(&v)
}

// GetRegion returns the Region field value
func (o *BillingPeriodDto) GetRegion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Region
}

// GetRegionOk returns a tuple with the Region field value
// and a boolean to check if the value has been set.
func (o *BillingPeriodDto) GetRegionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Region, true
}

// SetRegion sets field value
func (o *BillingPeriodDto) SetRegion(v string) {
	o.Region = v
}

// GetStartAt returns the StartAt field value
func (o *BillingPeriodDto) GetStartAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StartAt
}

// GetStartAtOk returns a tuple with the StartAt field value
// and a boolean to check if the value has been set.
func (o *BillingPeriodDto) GetStartAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartAt, true
}

// SetStartAt sets field value
func (o *BillingPeriodDto) SetStartAt(v string) {
	o.StartAt = v
}

// GetEndAt returns the EndAt field value
// If the value is explicit nil, the zero value for string will be returned
func (o *BillingPeriodDto) GetEndAt() string {
	if o == nil || o.EndAt.Get() == nil {
		var ret string
		return ret
	}

	return *o.EndAt.Get()
}

// GetEndAtOk returns a tuple with the EndAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BillingPeriodDto) GetEndAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EndAt.Get(), o.EndAt.IsSet()
}

// SetEndAt sets field value
func (o *BillingPeriodDto) SetEndAt(v string) {
	o.EndAt.Set(&v)
}

// GetCpu returns the Cpu field value
func (o *BillingPeriodDto) GetCpu() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Cpu
}

// GetCpuOk returns a tuple with the Cpu field value
// and a boolean to check if the value has been set.
func (o *BillingPeriodDto) GetCpuOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cpu, true
}

// SetCpu sets field value
func (o *BillingPeriodDto) SetCpu(v float32) {
	o.Cpu = v
}

// GetGpu returns the Gpu field value
func (o *BillingPeriodDto) GetGpu() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Gpu
}

// GetGpuOk returns a tuple with the Gpu field value
// and a boolean to check if the value has been set.
func (o *BillingPeriodDto) GetGpuOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Gpu, true
}

// SetGpu sets field value
func (o *BillingPeriodDto) SetGpu(v float32) {
	o.Gpu = v
}

// GetMem returns the Mem field value
func (o *BillingPeriodDto) GetMem() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Mem
}

// GetMemOk returns a tuple with the Mem field value
// and a boolean to check if the value has been set.
func (o *BillingPeriodDto) GetMemOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mem, true
}

// SetMem sets field value
func (o *BillingPeriodDto) SetMem(v float32) {
	o.Mem = v
}

// GetDisk returns the Disk field value
func (o *BillingPeriodDto) GetDisk() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Disk
}

// GetDiskOk returns a tuple with the Disk field value
// and a boolean to check if the value has been set.
func (o *BillingPeriodDto) GetDiskOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Disk, true
}

// SetDisk sets field value
func (o *BillingPeriodDto) SetDisk(v float32) {
	o.Disk = v
}

func (o BillingPeriodDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BillingPeriodDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["periodId"] = o.PeriodId
	toSerialize["boxId"] = o.BoxId
	toSerialize["organizationId"] = o.OrganizationId.Get()
	toSerialize["region"] = o.Region
	toSerialize["startAt"] = o.StartAt
	toSerialize["endAt"] = o.EndAt.Get()
	toSerialize["cpu"] = o.Cpu
	toSerialize["gpu"] = o.Gpu
	toSerialize["mem"] = o.Mem
	toSerialize["disk"] = o.Disk

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BillingPeriodDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"periodId",
		"boxId",
		"organizationId",
		"region",
		"startAt",
		"endAt",
		"cpu",
		"gpu",
		"mem",
		"disk",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBillingPeriodDto := _BillingPeriodDto{}

	err = json.Unmarshal(data, &varBillingPeriodDto)

	if err != nil {
		return err
	}

	*o = BillingPeriodDto(varBillingPeriodDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "periodId")
		delete(additionalProperties, "boxId")
		delete(additionalProperties, "organizationId")
		delete(additionalProperties, "region")
		delete(additionalProperties, "startAt")
		delete(additionalProperties, "endAt")
		delete(additionalProperties, "cpu")
		delete(additionalProperties, "gpu")
		delete(additionalProperties, "mem")
		delete(additionalProperties, "disk")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBillingPeriodDto struct {
	value *BillingPeriodDto
	isSet bool
}

func (v NullableBillingPeriodDto) Get() *BillingPeriodDto {
	return v.value
}

func (v *NullableBillingPeriodDto) Set(val *BillingPeriodDto) {
	v.value = val
	v.isSet = true
}

func (v NullableBillingPeriodDto) IsSet() bool {
	return v.isSet
}

func (v *NullableBillingPeriodDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBillingPeriodDto(val *BillingPeriodDto) *NullableBillingPeriodDto {
	return &NullableBillingPeriodDto{value: val, isSet: true}
}

func (v NullableBillingPeriodDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBillingPeriodDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


