/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


type BoxAccessGrantAPI interface {

	/*
	CreateBoxAccessGrant Create a box-scoped access grant

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param boxIdOrName ID or name of the box
	@return BoxAccessGrantAPICreateBoxAccessGrantRequest
	*/
	CreateBoxAccessGrant(ctx context.Context, boxIdOrName string) BoxAccessGrantAPICreateBoxAccessGrantRequest

	// CreateBoxAccessGrantExecute executes the request
	//  @return BoxAccessGrantCreated
	CreateBoxAccessGrantExecute(r BoxAccessGrantAPICreateBoxAccessGrantRequest) (*BoxAccessGrantCreated, *http.Response, error)

	/*
	ListBoxAccessGrants List box-scoped access grants

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param boxIdOrName ID or name of the box
	@return BoxAccessGrantAPIListBoxAccessGrantsRequest
	*/
	ListBoxAccessGrants(ctx context.Context, boxIdOrName string) BoxAccessGrantAPIListBoxAccessGrantsRequest

	// ListBoxAccessGrantsExecute executes the request
	//  @return []BoxAccessGrant
	ListBoxAccessGrantsExecute(r BoxAccessGrantAPIListBoxAccessGrantsRequest) ([]BoxAccessGrant, *http.Response, error)

	/*
	RevokeBoxAccessGrant Revoke a box-scoped access grant

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param boxIdOrName ID or name of the box
	@param grantId ID of the access grant to revoke
	@return BoxAccessGrantAPIRevokeBoxAccessGrantRequest
	*/
	RevokeBoxAccessGrant(ctx context.Context, boxIdOrName string, grantId string) BoxAccessGrantAPIRevokeBoxAccessGrantRequest

	// RevokeBoxAccessGrantExecute executes the request
	RevokeBoxAccessGrantExecute(r BoxAccessGrantAPIRevokeBoxAccessGrantRequest) (*http.Response, error)
}

// BoxAccessGrantAPIService BoxAccessGrantAPI service
type BoxAccessGrantAPIService service

type BoxAccessGrantAPICreateBoxAccessGrantRequest struct {
	ctx context.Context
	ApiService BoxAccessGrantAPI
	boxIdOrName string
	createBoxAccessGrant *CreateBoxAccessGrant
	xBoxLiteOrganizationID *string
}

func (r BoxAccessGrantAPICreateBoxAccessGrantRequest) CreateBoxAccessGrant(createBoxAccessGrant CreateBoxAccessGrant) BoxAccessGrantAPICreateBoxAccessGrantRequest {
	r.createBoxAccessGrant = &createBoxAccessGrant
	return r
}

// Use with JWT to specify the organization ID
func (r BoxAccessGrantAPICreateBoxAccessGrantRequest) XBoxLiteOrganizationID(xBoxLiteOrganizationID string) BoxAccessGrantAPICreateBoxAccessGrantRequest {
	r.xBoxLiteOrganizationID = &xBoxLiteOrganizationID
	return r
}

func (r BoxAccessGrantAPICreateBoxAccessGrantRequest) Execute() (*BoxAccessGrantCreated, *http.Response, error) {
	return r.ApiService.CreateBoxAccessGrantExecute(r)
}

/*
CreateBoxAccessGrant Create a box-scoped access grant

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param boxIdOrName ID or name of the box
 @return BoxAccessGrantAPICreateBoxAccessGrantRequest
*/
func (a *BoxAccessGrantAPIService) CreateBoxAccessGrant(ctx context.Context, boxIdOrName string) BoxAccessGrantAPICreateBoxAccessGrantRequest {
	return BoxAccessGrantAPICreateBoxAccessGrantRequest{
		ApiService: a,
		ctx: ctx,
		boxIdOrName: boxIdOrName,
	}
}

// Execute executes the request
//  @return BoxAccessGrantCreated
func (a *BoxAccessGrantAPIService) CreateBoxAccessGrantExecute(r BoxAccessGrantAPICreateBoxAccessGrantRequest) (*BoxAccessGrantCreated, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *BoxAccessGrantCreated
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "BoxAccessGrantAPIService.CreateBoxAccessGrant")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/box/{boxIdOrName}/access-grants"
	localVarPath = strings.Replace(localVarPath, "{"+"boxIdOrName"+"}", url.PathEscape(parameterValueToString(r.boxIdOrName, "boxIdOrName")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.createBoxAccessGrant == nil {
		return localVarReturnValue, nil, reportError("createBoxAccessGrant is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xBoxLiteOrganizationID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-BoxLite-Organization-ID", r.xBoxLiteOrganizationID, "simple", "")
	}
	// body params
	localVarPostBody = r.createBoxAccessGrant
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type BoxAccessGrantAPIListBoxAccessGrantsRequest struct {
	ctx context.Context
	ApiService BoxAccessGrantAPI
	boxIdOrName string
	xBoxLiteOrganizationID *string
}

// Use with JWT to specify the organization ID
func (r BoxAccessGrantAPIListBoxAccessGrantsRequest) XBoxLiteOrganizationID(xBoxLiteOrganizationID string) BoxAccessGrantAPIListBoxAccessGrantsRequest {
	r.xBoxLiteOrganizationID = &xBoxLiteOrganizationID
	return r
}

func (r BoxAccessGrantAPIListBoxAccessGrantsRequest) Execute() ([]BoxAccessGrant, *http.Response, error) {
	return r.ApiService.ListBoxAccessGrantsExecute(r)
}

/*
ListBoxAccessGrants List box-scoped access grants

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param boxIdOrName ID or name of the box
 @return BoxAccessGrantAPIListBoxAccessGrantsRequest
*/
func (a *BoxAccessGrantAPIService) ListBoxAccessGrants(ctx context.Context, boxIdOrName string) BoxAccessGrantAPIListBoxAccessGrantsRequest {
	return BoxAccessGrantAPIListBoxAccessGrantsRequest{
		ApiService: a,
		ctx: ctx,
		boxIdOrName: boxIdOrName,
	}
}

// Execute executes the request
//  @return []BoxAccessGrant
func (a *BoxAccessGrantAPIService) ListBoxAccessGrantsExecute(r BoxAccessGrantAPIListBoxAccessGrantsRequest) ([]BoxAccessGrant, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  []BoxAccessGrant
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "BoxAccessGrantAPIService.ListBoxAccessGrants")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/box/{boxIdOrName}/access-grants"
	localVarPath = strings.Replace(localVarPath, "{"+"boxIdOrName"+"}", url.PathEscape(parameterValueToString(r.boxIdOrName, "boxIdOrName")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xBoxLiteOrganizationID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-BoxLite-Organization-ID", r.xBoxLiteOrganizationID, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type BoxAccessGrantAPIRevokeBoxAccessGrantRequest struct {
	ctx context.Context
	ApiService BoxAccessGrantAPI
	boxIdOrName string
	grantId string
	xBoxLiteOrganizationID *string
}

// Use with JWT to specify the organization ID
func (r BoxAccessGrantAPIRevokeBoxAccessGrantRequest) XBoxLiteOrganizationID(xBoxLiteOrganizationID string) BoxAccessGrantAPIRevokeBoxAccessGrantRequest {
	r.xBoxLiteOrganizationID = &xBoxLiteOrganizationID
	return r
}

func (r BoxAccessGrantAPIRevokeBoxAccessGrantRequest) Execute() (*http.Response, error) {
	return r.ApiService.RevokeBoxAccessGrantExecute(r)
}

/*
RevokeBoxAccessGrant Revoke a box-scoped access grant

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param boxIdOrName ID or name of the box
 @param grantId ID of the access grant to revoke
 @return BoxAccessGrantAPIRevokeBoxAccessGrantRequest
*/
func (a *BoxAccessGrantAPIService) RevokeBoxAccessGrant(ctx context.Context, boxIdOrName string, grantId string) BoxAccessGrantAPIRevokeBoxAccessGrantRequest {
	return BoxAccessGrantAPIRevokeBoxAccessGrantRequest{
		ApiService: a,
		ctx: ctx,
		boxIdOrName: boxIdOrName,
		grantId: grantId,
	}
}

// Execute executes the request
func (a *BoxAccessGrantAPIService) RevokeBoxAccessGrantExecute(r BoxAccessGrantAPIRevokeBoxAccessGrantRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "BoxAccessGrantAPIService.RevokeBoxAccessGrant")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/box/{boxIdOrName}/access-grants/{grantId}"
	localVarPath = strings.Replace(localVarPath, "{"+"boxIdOrName"+"}", url.PathEscape(parameterValueToString(r.boxIdOrName, "boxIdOrName")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"grantId"+"}", url.PathEscape(parameterValueToString(r.grantId, "grantId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xBoxLiteOrganizationID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-BoxLite-Organization-ID", r.xBoxLiteOrganizationID, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}
