/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


type SshAccessAPI interface {

	/*
	CreateTemporarySshCredential Create a temporary SSH credential for a box

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param boxIdOrName ID or name of the box
	@return SshAccessAPICreateTemporarySshCredentialRequest
	*/
	CreateTemporarySshCredential(ctx context.Context, boxIdOrName string) SshAccessAPICreateTemporarySshCredentialRequest

	// CreateTemporarySshCredentialExecute executes the request
	//  @return TemporarySshCredentialCreated
	CreateTemporarySshCredentialExecute(r SshAccessAPICreateTemporarySshCredentialRequest) (*TemporarySshCredentialCreated, *http.Response, error)

	/*
	ListTemporarySshCredentials List temporary SSH credentials for a box

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param boxIdOrName ID or name of the box
	@return SshAccessAPIListTemporarySshCredentialsRequest
	*/
	ListTemporarySshCredentials(ctx context.Context, boxIdOrName string) SshAccessAPIListTemporarySshCredentialsRequest

	// ListTemporarySshCredentialsExecute executes the request
	//  @return []TemporarySshCredential
	ListTemporarySshCredentialsExecute(r SshAccessAPIListTemporarySshCredentialsRequest) ([]TemporarySshCredential, *http.Response, error)

	/*
	RevokeTemporarySshCredential Revoke a temporary SSH credential

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param boxIdOrName ID or name of the box
	@param credentialId ID of the SSH credential to revoke
	@return SshAccessAPIRevokeTemporarySshCredentialRequest
	*/
	RevokeTemporarySshCredential(ctx context.Context, boxIdOrName string, credentialId string) SshAccessAPIRevokeTemporarySshCredentialRequest

	// RevokeTemporarySshCredentialExecute executes the request
	RevokeTemporarySshCredentialExecute(r SshAccessAPIRevokeTemporarySshCredentialRequest) (*http.Response, error)
}

// SshAccessAPIService SshAccessAPI service
type SshAccessAPIService service

type SshAccessAPICreateTemporarySshCredentialRequest struct {
	ctx context.Context
	ApiService SshAccessAPI
	boxIdOrName string
	createTemporarySshCredential *CreateTemporarySshCredential
	xBoxLiteAppKey *string
	xBoxLiteOrganizationID *string
}

func (r SshAccessAPICreateTemporarySshCredentialRequest) CreateTemporarySshCredential(createTemporarySshCredential CreateTemporarySshCredential) SshAccessAPICreateTemporarySshCredentialRequest {
	r.createTemporarySshCredential = &createTemporarySshCredential
	return r
}

// Box-scoped app key issued by a prior access-grant create call. Alternative to account authorization for creating an SSH credential; providing both is rejected.
func (r SshAccessAPICreateTemporarySshCredentialRequest) XBoxLiteAppKey(xBoxLiteAppKey string) SshAccessAPICreateTemporarySshCredentialRequest {
	r.xBoxLiteAppKey = &xBoxLiteAppKey
	return r
}

// Use with JWT to specify the organization ID
func (r SshAccessAPICreateTemporarySshCredentialRequest) XBoxLiteOrganizationID(xBoxLiteOrganizationID string) SshAccessAPICreateTemporarySshCredentialRequest {
	r.xBoxLiteOrganizationID = &xBoxLiteOrganizationID
	return r
}

func (r SshAccessAPICreateTemporarySshCredentialRequest) Execute() (*TemporarySshCredentialCreated, *http.Response, error) {
	return r.ApiService.CreateTemporarySshCredentialExecute(r)
}

/*
CreateTemporarySshCredential Create a temporary SSH credential for a box

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param boxIdOrName ID or name of the box
 @return SshAccessAPICreateTemporarySshCredentialRequest
*/
func (a *SshAccessAPIService) CreateTemporarySshCredential(ctx context.Context, boxIdOrName string) SshAccessAPICreateTemporarySshCredentialRequest {
	return SshAccessAPICreateTemporarySshCredentialRequest{
		ApiService: a,
		ctx: ctx,
		boxIdOrName: boxIdOrName,
	}
}

// Execute executes the request
//  @return TemporarySshCredentialCreated
func (a *SshAccessAPIService) CreateTemporarySshCredentialExecute(r SshAccessAPICreateTemporarySshCredentialRequest) (*TemporarySshCredentialCreated, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *TemporarySshCredentialCreated
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SshAccessAPIService.CreateTemporarySshCredential")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/box/{boxIdOrName}/ssh-access"
	localVarPath = strings.Replace(localVarPath, "{"+"boxIdOrName"+"}", url.PathEscape(parameterValueToString(r.boxIdOrName, "boxIdOrName")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.createTemporarySshCredential == nil {
		return localVarReturnValue, nil, reportError("createTemporarySshCredential is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xBoxLiteAppKey != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-BoxLite-App-Key", r.xBoxLiteAppKey, "simple", "")
	}
	if r.xBoxLiteOrganizationID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-BoxLite-Organization-ID", r.xBoxLiteOrganizationID, "simple", "")
	}
	// body params
	localVarPostBody = r.createTemporarySshCredential
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type SshAccessAPIListTemporarySshCredentialsRequest struct {
	ctx context.Context
	ApiService SshAccessAPI
	boxIdOrName string
	xBoxLiteOrganizationID *string
}

// Use with JWT to specify the organization ID
func (r SshAccessAPIListTemporarySshCredentialsRequest) XBoxLiteOrganizationID(xBoxLiteOrganizationID string) SshAccessAPIListTemporarySshCredentialsRequest {
	r.xBoxLiteOrganizationID = &xBoxLiteOrganizationID
	return r
}

func (r SshAccessAPIListTemporarySshCredentialsRequest) Execute() ([]TemporarySshCredential, *http.Response, error) {
	return r.ApiService.ListTemporarySshCredentialsExecute(r)
}

/*
ListTemporarySshCredentials List temporary SSH credentials for a box

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param boxIdOrName ID or name of the box
 @return SshAccessAPIListTemporarySshCredentialsRequest
*/
func (a *SshAccessAPIService) ListTemporarySshCredentials(ctx context.Context, boxIdOrName string) SshAccessAPIListTemporarySshCredentialsRequest {
	return SshAccessAPIListTemporarySshCredentialsRequest{
		ApiService: a,
		ctx: ctx,
		boxIdOrName: boxIdOrName,
	}
}

// Execute executes the request
//  @return []TemporarySshCredential
func (a *SshAccessAPIService) ListTemporarySshCredentialsExecute(r SshAccessAPIListTemporarySshCredentialsRequest) ([]TemporarySshCredential, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  []TemporarySshCredential
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SshAccessAPIService.ListTemporarySshCredentials")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/box/{boxIdOrName}/ssh-access"
	localVarPath = strings.Replace(localVarPath, "{"+"boxIdOrName"+"}", url.PathEscape(parameterValueToString(r.boxIdOrName, "boxIdOrName")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xBoxLiteOrganizationID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-BoxLite-Organization-ID", r.xBoxLiteOrganizationID, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type SshAccessAPIRevokeTemporarySshCredentialRequest struct {
	ctx context.Context
	ApiService SshAccessAPI
	boxIdOrName string
	credentialId string
	xBoxLiteOrganizationID *string
}

// Use with JWT to specify the organization ID
func (r SshAccessAPIRevokeTemporarySshCredentialRequest) XBoxLiteOrganizationID(xBoxLiteOrganizationID string) SshAccessAPIRevokeTemporarySshCredentialRequest {
	r.xBoxLiteOrganizationID = &xBoxLiteOrganizationID
	return r
}

func (r SshAccessAPIRevokeTemporarySshCredentialRequest) Execute() (*http.Response, error) {
	return r.ApiService.RevokeTemporarySshCredentialExecute(r)
}

/*
RevokeTemporarySshCredential Revoke a temporary SSH credential

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param boxIdOrName ID or name of the box
 @param credentialId ID of the SSH credential to revoke
 @return SshAccessAPIRevokeTemporarySshCredentialRequest
*/
func (a *SshAccessAPIService) RevokeTemporarySshCredential(ctx context.Context, boxIdOrName string, credentialId string) SshAccessAPIRevokeTemporarySshCredentialRequest {
	return SshAccessAPIRevokeTemporarySshCredentialRequest{
		ApiService: a,
		ctx: ctx,
		boxIdOrName: boxIdOrName,
		credentialId: credentialId,
	}
}

// Execute executes the request
func (a *SshAccessAPIService) RevokeTemporarySshCredentialExecute(r SshAccessAPIRevokeTemporarySshCredentialRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SshAccessAPIService.RevokeTemporarySshCredential")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/box/{boxIdOrName}/ssh-access/{credentialId}"
	localVarPath = strings.Replace(localVarPath, "{"+"boxIdOrName"+"}", url.PathEscape(parameterValueToString(r.boxIdOrName, "boxIdOrName")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"credentialId"+"}", url.PathEscape(parameterValueToString(r.credentialId, "credentialId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xBoxLiteOrganizationID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-BoxLite-Organization-ID", r.xBoxLiteOrganizationID, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}
