/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


type UsageAPI interface {

	/*
	GetBoxUsage Get aggregated usage totals for a box over a time range

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param boxId ID of the box
	@return UsageAPIGetBoxUsageRequest
	*/
	GetBoxUsage(ctx context.Context, boxId string) UsageAPIGetBoxUsageRequest

	// GetBoxUsageExecute executes the request
	GetBoxUsageExecute(r UsageAPIGetBoxUsageRequest) (*http.Response, error)

	/*
	ReportBoxActualUsage Report a box actual cgroup usage (runner -> control-plane)

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param boxId ID of the box
	@return UsageAPIReportBoxActualUsageRequest
	*/
	ReportBoxActualUsage(ctx context.Context, boxId string) UsageAPIReportBoxActualUsageRequest

	// ReportBoxActualUsageExecute executes the request
	ReportBoxActualUsageExecute(r UsageAPIReportBoxActualUsageRequest) (*http.Response, error)
}

// UsageAPIService UsageAPI service
type UsageAPIService service

type UsageAPIGetBoxUsageRequest struct {
	ctx context.Context
	ApiService UsageAPI
	boxId string
	from *string
	to *string
}

// ISO start (default: 30d ago)
func (r UsageAPIGetBoxUsageRequest) From(from string) UsageAPIGetBoxUsageRequest {
	r.from = &from
	return r
}

// ISO end (default: now)
func (r UsageAPIGetBoxUsageRequest) To(to string) UsageAPIGetBoxUsageRequest {
	r.to = &to
	return r
}

func (r UsageAPIGetBoxUsageRequest) Execute() (*http.Response, error) {
	return r.ApiService.GetBoxUsageExecute(r)
}

/*
GetBoxUsage Get aggregated usage totals for a box over a time range

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param boxId ID of the box
 @return UsageAPIGetBoxUsageRequest
*/
func (a *UsageAPIService) GetBoxUsage(ctx context.Context, boxId string) UsageAPIGetBoxUsageRequest {
	return UsageAPIGetBoxUsageRequest{
		ApiService: a,
		ctx: ctx,
		boxId: boxId,
	}
}

// Execute executes the request
func (a *UsageAPIService) GetBoxUsageExecute(r UsageAPIGetBoxUsageRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "UsageAPIService.GetBoxUsage")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/usage/box/{boxId}"
	localVarPath = strings.Replace(localVarPath, "{"+"boxId"+"}", url.PathEscape(parameterValueToString(r.boxId, "boxId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.from != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "from", r.from, "form", "")
	}
	if r.to != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "to", r.to, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type UsageAPIReportBoxActualUsageRequest struct {
	ctx context.Context
	ApiService UsageAPI
	boxId string
	reportBoxActualUsageDto *ReportBoxActualUsageDto
}

func (r UsageAPIReportBoxActualUsageRequest) ReportBoxActualUsageDto(reportBoxActualUsageDto ReportBoxActualUsageDto) UsageAPIReportBoxActualUsageRequest {
	r.reportBoxActualUsageDto = &reportBoxActualUsageDto
	return r
}

func (r UsageAPIReportBoxActualUsageRequest) Execute() (*http.Response, error) {
	return r.ApiService.ReportBoxActualUsageExecute(r)
}

/*
ReportBoxActualUsage Report a box actual cgroup usage (runner -> control-plane)

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param boxId ID of the box
 @return UsageAPIReportBoxActualUsageRequest
*/
func (a *UsageAPIService) ReportBoxActualUsage(ctx context.Context, boxId string) UsageAPIReportBoxActualUsageRequest {
	return UsageAPIReportBoxActualUsageRequest{
		ApiService: a,
		ctx: ctx,
		boxId: boxId,
	}
}

// Execute executes the request
func (a *UsageAPIService) ReportBoxActualUsageExecute(r UsageAPIReportBoxActualUsageRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "UsageAPIService.ReportBoxActualUsage")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/usage/box/{boxId}/actual"
	localVarPath = strings.Replace(localVarPath, "{"+"boxId"+"}", url.PathEscape(parameterValueToString(r.boxId, "boxId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.reportBoxActualUsageDto == nil {
		return nil, reportError("reportBoxActualUsageDto is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.reportBoxActualUsageDto
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}
