/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the TopUpCheckoutDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TopUpCheckoutDto{}

// TopUpCheckoutDto struct for TopUpCheckoutDto
type TopUpCheckoutDto struct {
	// Provider checkout URL to redirect the user to
	Url string `json:"url"`
	AdditionalProperties map[string]interface{}
}

type _TopUpCheckoutDto TopUpCheckoutDto

// NewTopUpCheckoutDto instantiates a new TopUpCheckoutDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTopUpCheckoutDto(url string) *TopUpCheckoutDto {
	this := TopUpCheckoutDto{}
	this.Url = url
	return &this
}

// NewTopUpCheckoutDtoWithDefaults instantiates a new TopUpCheckoutDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTopUpCheckoutDtoWithDefaults() *TopUpCheckoutDto {
	this := TopUpCheckoutDto{}
	return &this
}

// GetUrl returns the Url field value
func (o *TopUpCheckoutDto) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *TopUpCheckoutDto) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *TopUpCheckoutDto) SetUrl(v string) {
	o.Url = v
}

func (o TopUpCheckoutDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TopUpCheckoutDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["url"] = o.Url

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TopUpCheckoutDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTopUpCheckoutDto := _TopUpCheckoutDto{}

	err = json.Unmarshal(data, &varTopUpCheckoutDto)

	if err != nil {
		return err
	}

	*o = TopUpCheckoutDto(varTopUpCheckoutDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "url")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTopUpCheckoutDto struct {
	value *TopUpCheckoutDto
	isSet bool
}

func (v NullableTopUpCheckoutDto) Get() *TopUpCheckoutDto {
	return v.value
}

func (v *NullableTopUpCheckoutDto) Set(val *TopUpCheckoutDto) {
	v.value = val
	v.isSet = true
}

func (v NullableTopUpCheckoutDto) IsSet() bool {
	return v.isSet
}

func (v *NullableTopUpCheckoutDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTopUpCheckoutDto(val *TopUpCheckoutDto) *NullableTopUpCheckoutDto {
	return &NullableTopUpCheckoutDto{value: val, isSet: true}
}

func (v NullableTopUpCheckoutDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTopUpCheckoutDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
