/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the BoxCreateDefaults type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BoxCreateDefaults{}

// BoxCreateDefaults struct for BoxCreateDefaults
type BoxCreateDefaults struct {
	// Default CPU cores used when create omits cpu
	Cpu float32 `json:"cpu"`
	// Default memory in GiB used when create omits memory
	Memory float32 `json:"memory"`
	// Default disk in GiB used when create omits disk
	Disk float32 `json:"disk"`
	AdditionalProperties map[string]interface{}
}

type _BoxCreateDefaults BoxCreateDefaults

// NewBoxCreateDefaults instantiates a new BoxCreateDefaults object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBoxCreateDefaults(cpu float32, memory float32, disk float32) *BoxCreateDefaults {
	this := BoxCreateDefaults{}
	this.Cpu = cpu
	this.Memory = memory
	this.Disk = disk
	return &this
}

// NewBoxCreateDefaultsWithDefaults instantiates a new BoxCreateDefaults object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBoxCreateDefaultsWithDefaults() *BoxCreateDefaults {
	this := BoxCreateDefaults{}
	return &this
}

// GetCpu returns the Cpu field value
func (o *BoxCreateDefaults) GetCpu() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Cpu
}

// GetCpuOk returns a tuple with the Cpu field value
// and a boolean to check if the value has been set.
func (o *BoxCreateDefaults) GetCpuOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cpu, true
}

// SetCpu sets field value
func (o *BoxCreateDefaults) SetCpu(v float32) {
	o.Cpu = v
}

// GetMemory returns the Memory field value
func (o *BoxCreateDefaults) GetMemory() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Memory
}

// GetMemoryOk returns a tuple with the Memory field value
// and a boolean to check if the value has been set.
func (o *BoxCreateDefaults) GetMemoryOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Memory, true
}

// SetMemory sets field value
func (o *BoxCreateDefaults) SetMemory(v float32) {
	o.Memory = v
}

// GetDisk returns the Disk field value
func (o *BoxCreateDefaults) GetDisk() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Disk
}

// GetDiskOk returns a tuple with the Disk field value
// and a boolean to check if the value has been set.
func (o *BoxCreateDefaults) GetDiskOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Disk, true
}

// SetDisk sets field value
func (o *BoxCreateDefaults) SetDisk(v float32) {
	o.Disk = v
}

func (o BoxCreateDefaults) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BoxCreateDefaults) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cpu"] = o.Cpu
	toSerialize["memory"] = o.Memory
	toSerialize["disk"] = o.Disk

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BoxCreateDefaults) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"cpu",
		"memory",
		"disk",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBoxCreateDefaults := _BoxCreateDefaults{}

	err = json.Unmarshal(data, &varBoxCreateDefaults)

	if err != nil {
		return err
	}

	*o = BoxCreateDefaults(varBoxCreateDefaults)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "cpu")
		delete(additionalProperties, "memory")
		delete(additionalProperties, "disk")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBoxCreateDefaults struct {
	value *BoxCreateDefaults
	isSet bool
}

func (v NullableBoxCreateDefaults) Get() *BoxCreateDefaults {
	return v.value
}

func (v *NullableBoxCreateDefaults) Set(val *BoxCreateDefaults) {
	v.value = val
	v.isSet = true
}

func (v NullableBoxCreateDefaults) IsSet() bool {
	return v.isSet
}

func (v *NullableBoxCreateDefaults) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBoxCreateDefaults(val *BoxCreateDefaults) *NullableBoxCreateDefaults {
	return &NullableBoxCreateDefaults{value: val, isSet: true}
}

func (v NullableBoxCreateDefaults) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBoxCreateDefaults) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


