/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateTemporarySshCredential type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateTemporarySshCredential{}

// CreateTemporarySshCredential struct for CreateTemporarySshCredential
type CreateTemporarySshCredential struct {
	// ID of a previously issued, active `ssh`-scoped access grant for this box
	GrantId string `json:"grantId"`
	// Canonical OpenSSH public key line, e.g. \"ssh-ed25519 AAAA... user@host\"
	PublicKey string `json:"publicKey"`
	// Credential lifetime in seconds (default 300, max bounded by the parent grant expiry)
	ExpiresInSeconds *float32 `json:"expiresInSeconds,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateTemporarySshCredential CreateTemporarySshCredential

// NewCreateTemporarySshCredential instantiates a new CreateTemporarySshCredential object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateTemporarySshCredential(grantId string, publicKey string) *CreateTemporarySshCredential {
	this := CreateTemporarySshCredential{}
	this.GrantId = grantId
	this.PublicKey = publicKey
	return &this
}

// NewCreateTemporarySshCredentialWithDefaults instantiates a new CreateTemporarySshCredential object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateTemporarySshCredentialWithDefaults() *CreateTemporarySshCredential {
	this := CreateTemporarySshCredential{}
	return &this
}

// GetGrantId returns the GrantId field value
func (o *CreateTemporarySshCredential) GetGrantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GrantId
}

// GetGrantIdOk returns a tuple with the GrantId field value
// and a boolean to check if the value has been set.
func (o *CreateTemporarySshCredential) GetGrantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GrantId, true
}

// SetGrantId sets field value
func (o *CreateTemporarySshCredential) SetGrantId(v string) {
	o.GrantId = v
}

// GetPublicKey returns the PublicKey field value
func (o *CreateTemporarySshCredential) GetPublicKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PublicKey
}

// GetPublicKeyOk returns a tuple with the PublicKey field value
// and a boolean to check if the value has been set.
func (o *CreateTemporarySshCredential) GetPublicKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PublicKey, true
}

// SetPublicKey sets field value
func (o *CreateTemporarySshCredential) SetPublicKey(v string) {
	o.PublicKey = v
}

// GetExpiresInSeconds returns the ExpiresInSeconds field value if set, zero value otherwise.
func (o *CreateTemporarySshCredential) GetExpiresInSeconds() float32 {
	if o == nil || IsNil(o.ExpiresInSeconds) {
		var ret float32
		return ret
	}
	return *o.ExpiresInSeconds
}

// GetExpiresInSecondsOk returns a tuple with the ExpiresInSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTemporarySshCredential) GetExpiresInSecondsOk() (*float32, bool) {
	if o == nil || IsNil(o.ExpiresInSeconds) {
		return nil, false
	}
	return o.ExpiresInSeconds, true
}

// HasExpiresInSeconds returns a boolean if a field has been set.
func (o *CreateTemporarySshCredential) HasExpiresInSeconds() bool {
	if o != nil && !IsNil(o.ExpiresInSeconds) {
		return true
	}

	return false
}

// SetExpiresInSeconds gets a reference to the given float32 and assigns it to the ExpiresInSeconds field.
func (o *CreateTemporarySshCredential) SetExpiresInSeconds(v float32) {
	o.ExpiresInSeconds = &v
}

func (o CreateTemporarySshCredential) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateTemporarySshCredential) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["grantId"] = o.GrantId
	toSerialize["publicKey"] = o.PublicKey
	if !IsNil(o.ExpiresInSeconds) {
		toSerialize["expiresInSeconds"] = o.ExpiresInSeconds
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateTemporarySshCredential) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"grantId",
		"publicKey",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateTemporarySshCredential := _CreateTemporarySshCredential{}

	err = json.Unmarshal(data, &varCreateTemporarySshCredential)

	if err != nil {
		return err
	}

	*o = CreateTemporarySshCredential(varCreateTemporarySshCredential)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "grantId")
		delete(additionalProperties, "publicKey")
		delete(additionalProperties, "expiresInSeconds")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateTemporarySshCredential struct {
	value *CreateTemporarySshCredential
	isSet bool
}

func (v NullableCreateTemporarySshCredential) Get() *CreateTemporarySshCredential {
	return v.value
}

func (v *NullableCreateTemporarySshCredential) Set(val *CreateTemporarySshCredential) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateTemporarySshCredential) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateTemporarySshCredential) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateTemporarySshCredential(val *CreateTemporarySshCredential) *NullableCreateTemporarySshCredential {
	return &NullableCreateTemporarySshCredential{value: val, isSet: true}
}

func (v NullableCreateTemporarySshCredential) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateTemporarySshCredential) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


