/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

var _ MappedNullable = &LinuxCapabilities{}

// LinuxCapabilities is the effective Linux capability policy for a box.
type LinuxCapabilities struct {
	// Linux capabilities added to the default container capability set
	Add []string `json:"add"`
	// Linux capabilities removed from the container capability set
	Drop                 []string `json:"drop"`
	AdditionalProperties map[string]interface{}
}

type _LinuxCapabilities LinuxCapabilities

func NewLinuxCapabilities(add []string, drop []string) *LinuxCapabilities {
	this := LinuxCapabilities{}
	this.Add = add
	this.Drop = drop
	return &this
}

func NewLinuxCapabilitiesWithDefaults() *LinuxCapabilities {
	this := LinuxCapabilities{}
	return &this
}

func (o *LinuxCapabilities) GetAdd() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Add
}

func (o *LinuxCapabilities) GetAddOk() (*[]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Add, true
}

func (o *LinuxCapabilities) SetAdd(v []string) {
	o.Add = v
}

func (o *LinuxCapabilities) GetDrop() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Drop
}

func (o *LinuxCapabilities) GetDropOk() (*[]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Drop, true
}

func (o *LinuxCapabilities) SetDrop(v []string) {
	o.Drop = v
}

func (o LinuxCapabilities) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LinuxCapabilities) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{
		"add":  o.Add,
		"drop": o.Drop,
	}
	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}
	return toSerialize, nil
}

func (o *LinuxCapabilities) UnmarshalJSON(data []byte) error {
	allProperties := make(map[string]interface{})
	if err := json.Unmarshal(data, &allProperties); err != nil {
		return err
	}
	for _, requiredProperty := range []string{"add", "drop"} {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLinuxCapabilities := _LinuxCapabilities{}
	if err := json.Unmarshal(data, &varLinuxCapabilities); err != nil {
		return err
	}
	*o = LinuxCapabilities(varLinuxCapabilities)

	additionalProperties := make(map[string]interface{})
	if err := json.Unmarshal(data, &additionalProperties); err != nil {
		return err
	}
	delete(additionalProperties, "add")
	delete(additionalProperties, "drop")
	o.AdditionalProperties = additionalProperties
	return nil
}

type NullableLinuxCapabilities struct {
	value *LinuxCapabilities
	isSet bool
}

func (v NullableLinuxCapabilities) Get() *LinuxCapabilities { return v.value }
func (v *NullableLinuxCapabilities) Set(val *LinuxCapabilities) {
	v.value = val
	v.isSet = true
}
func (v NullableLinuxCapabilities) IsSet() bool { return v.isSet }
func (v *NullableLinuxCapabilities) Unset() {
	v.value = nil
	v.isSet = false
}
func NewNullableLinuxCapabilities(val *LinuxCapabilities) *NullableLinuxCapabilities {
	return &NullableLinuxCapabilities{value: val, isSet: true}
}
func (v NullableLinuxCapabilities) MarshalJSON() ([]byte, error) { return json.Marshal(v.value) }
func (v *NullableLinuxCapabilities) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
