/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the SystemImagesConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SystemImagesConfig{}

// SystemImagesConfig struct for SystemImagesConfig
type SystemImagesConfig struct {
	// Curated Base image reference
	Base string `json:"base"`
	// Curated Python image reference
	Python string `json:"python"`
	// Curated Node.js image reference
	Node string `json:"node"`
	AdditionalProperties map[string]interface{}
}

type _SystemImagesConfig SystemImagesConfig

// NewSystemImagesConfig instantiates a new SystemImagesConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSystemImagesConfig(base string, python string, node string) *SystemImagesConfig {
	this := SystemImagesConfig{}
	this.Base = base
	this.Python = python
	this.Node = node
	return &this
}

// NewSystemImagesConfigWithDefaults instantiates a new SystemImagesConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSystemImagesConfigWithDefaults() *SystemImagesConfig {
	this := SystemImagesConfig{}
	return &this
}

// GetBase returns the Base field value
func (o *SystemImagesConfig) GetBase() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Base
}

// GetBaseOk returns a tuple with the Base field value
// and a boolean to check if the value has been set.
func (o *SystemImagesConfig) GetBaseOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Base, true
}

// SetBase sets field value
func (o *SystemImagesConfig) SetBase(v string) {
	o.Base = v
}

// GetPython returns the Python field value
func (o *SystemImagesConfig) GetPython() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Python
}

// GetPythonOk returns a tuple with the Python field value
// and a boolean to check if the value has been set.
func (o *SystemImagesConfig) GetPythonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Python, true
}

// SetPython sets field value
func (o *SystemImagesConfig) SetPython(v string) {
	o.Python = v
}

// GetNode returns the Node field value
func (o *SystemImagesConfig) GetNode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Node
}

// GetNodeOk returns a tuple with the Node field value
// and a boolean to check if the value has been set.
func (o *SystemImagesConfig) GetNodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Node, true
}

// SetNode sets field value
func (o *SystemImagesConfig) SetNode(v string) {
	o.Node = v
}

func (o SystemImagesConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SystemImagesConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["base"] = o.Base
	toSerialize["python"] = o.Python
	toSerialize["node"] = o.Node

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SystemImagesConfig) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"base",
		"python",
		"node",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSystemImagesConfig := _SystemImagesConfig{}

	err = json.Unmarshal(data, &varSystemImagesConfig)

	if err != nil {
		return err
	}

	*o = SystemImagesConfig(varSystemImagesConfig)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "base")
		delete(additionalProperties, "python")
		delete(additionalProperties, "node")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSystemImagesConfig struct {
	value *SystemImagesConfig
	isSet bool
}

func (v NullableSystemImagesConfig) Get() *SystemImagesConfig {
	return v.value
}

func (v *NullableSystemImagesConfig) Set(val *SystemImagesConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableSystemImagesConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableSystemImagesConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSystemImagesConfig(val *SystemImagesConfig) *NullableSystemImagesConfig {
	return &NullableSystemImagesConfig{value: val, isSet: true}
}

func (v NullableSystemImagesConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSystemImagesConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
