/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the OrganizationUsageOverview type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizationUsageOverview{}

// OrganizationUsageOverview struct for OrganizationUsageOverview
type OrganizationUsageOverview struct {
	// vCPU currently consumed by running boxes
	CurrentCpuUsage float32 `json:"currentCpuUsage"`
	// Total vCPU the organization may consume
	TotalCpuQuota float32 `json:"totalCpuQuota"`
	// Memory in GB currently consumed by running boxes
	CurrentMemoryUsage float32 `json:"currentMemoryUsage"`
	// Total memory in GB the organization may consume
	TotalMemoryQuota float32 `json:"totalMemoryQuota"`
	// Disk in GB currently occupied by boxes
	CurrentDiskUsage float32 `json:"currentDiskUsage"`
	// Total disk in GB the organization may occupy
	TotalDiskQuota float32 `json:"totalDiskQuota"`
	// GPUs currently consumed by running boxes
	CurrentGpuUsage float32 `json:"currentGpuUsage"`
	// Total GPUs the organization may consume; 0 denies GPU boxes
	TotalGpuQuota float32 `json:"totalGpuQuota"`
	// Boxes currently running
	CurrentBoxUsage float32 `json:"currentBoxUsage"`
	// Maximum number of concurrently running boxes
	MaxConcurrentBoxes float32 `json:"maxConcurrentBoxes"`
	AdditionalProperties map[string]interface{}
}

type _OrganizationUsageOverview OrganizationUsageOverview

// NewOrganizationUsageOverview instantiates a new OrganizationUsageOverview object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationUsageOverview(currentCpuUsage float32, totalCpuQuota float32, currentMemoryUsage float32, totalMemoryQuota float32, currentDiskUsage float32, totalDiskQuota float32, currentGpuUsage float32, totalGpuQuota float32, currentBoxUsage float32, maxConcurrentBoxes float32) *OrganizationUsageOverview {
	this := OrganizationUsageOverview{}
	this.CurrentCpuUsage = currentCpuUsage
	this.TotalCpuQuota = totalCpuQuota
	this.CurrentMemoryUsage = currentMemoryUsage
	this.TotalMemoryQuota = totalMemoryQuota
	this.CurrentDiskUsage = currentDiskUsage
	this.TotalDiskQuota = totalDiskQuota
	this.CurrentGpuUsage = currentGpuUsage
	this.TotalGpuQuota = totalGpuQuota
	this.CurrentBoxUsage = currentBoxUsage
	this.MaxConcurrentBoxes = maxConcurrentBoxes
	return &this
}

// NewOrganizationUsageOverviewWithDefaults instantiates a new OrganizationUsageOverview object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationUsageOverviewWithDefaults() *OrganizationUsageOverview {
	this := OrganizationUsageOverview{}
	return &this
}

// GetCurrentCpuUsage returns the CurrentCpuUsage field value
func (o *OrganizationUsageOverview) GetCurrentCpuUsage() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.CurrentCpuUsage
}

// GetCurrentCpuUsageOk returns a tuple with the CurrentCpuUsage field value
// and a boolean to check if the value has been set.
func (o *OrganizationUsageOverview) GetCurrentCpuUsageOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CurrentCpuUsage, true
}

// SetCurrentCpuUsage sets field value
func (o *OrganizationUsageOverview) SetCurrentCpuUsage(v float32) {
	o.CurrentCpuUsage = v
}

// GetTotalCpuQuota returns the TotalCpuQuota field value
func (o *OrganizationUsageOverview) GetTotalCpuQuota() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.TotalCpuQuota
}

// GetTotalCpuQuotaOk returns a tuple with the TotalCpuQuota field value
// and a boolean to check if the value has been set.
func (o *OrganizationUsageOverview) GetTotalCpuQuotaOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalCpuQuota, true
}

// SetTotalCpuQuota sets field value
func (o *OrganizationUsageOverview) SetTotalCpuQuota(v float32) {
	o.TotalCpuQuota = v
}

// GetCurrentMemoryUsage returns the CurrentMemoryUsage field value
func (o *OrganizationUsageOverview) GetCurrentMemoryUsage() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.CurrentMemoryUsage
}

// GetCurrentMemoryUsageOk returns a tuple with the CurrentMemoryUsage field value
// and a boolean to check if the value has been set.
func (o *OrganizationUsageOverview) GetCurrentMemoryUsageOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CurrentMemoryUsage, true
}

// SetCurrentMemoryUsage sets field value
func (o *OrganizationUsageOverview) SetCurrentMemoryUsage(v float32) {
	o.CurrentMemoryUsage = v
}

// GetTotalMemoryQuota returns the TotalMemoryQuota field value
func (o *OrganizationUsageOverview) GetTotalMemoryQuota() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.TotalMemoryQuota
}

// GetTotalMemoryQuotaOk returns a tuple with the TotalMemoryQuota field value
// and a boolean to check if the value has been set.
func (o *OrganizationUsageOverview) GetTotalMemoryQuotaOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalMemoryQuota, true
}

// SetTotalMemoryQuota sets field value
func (o *OrganizationUsageOverview) SetTotalMemoryQuota(v float32) {
	o.TotalMemoryQuota = v
}

// GetCurrentDiskUsage returns the CurrentDiskUsage field value
func (o *OrganizationUsageOverview) GetCurrentDiskUsage() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.CurrentDiskUsage
}

// GetCurrentDiskUsageOk returns a tuple with the CurrentDiskUsage field value
// and a boolean to check if the value has been set.
func (o *OrganizationUsageOverview) GetCurrentDiskUsageOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CurrentDiskUsage, true
}

// SetCurrentDiskUsage sets field value
func (o *OrganizationUsageOverview) SetCurrentDiskUsage(v float32) {
	o.CurrentDiskUsage = v
}

// GetTotalDiskQuota returns the TotalDiskQuota field value
func (o *OrganizationUsageOverview) GetTotalDiskQuota() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.TotalDiskQuota
}

// GetTotalDiskQuotaOk returns a tuple with the TotalDiskQuota field value
// and a boolean to check if the value has been set.
func (o *OrganizationUsageOverview) GetTotalDiskQuotaOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalDiskQuota, true
}

// SetTotalDiskQuota sets field value
func (o *OrganizationUsageOverview) SetTotalDiskQuota(v float32) {
	o.TotalDiskQuota = v
}

// GetCurrentGpuUsage returns the CurrentGpuUsage field value
func (o *OrganizationUsageOverview) GetCurrentGpuUsage() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.CurrentGpuUsage
}

// GetCurrentGpuUsageOk returns a tuple with the CurrentGpuUsage field value
// and a boolean to check if the value has been set.
func (o *OrganizationUsageOverview) GetCurrentGpuUsageOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CurrentGpuUsage, true
}

// SetCurrentGpuUsage sets field value
func (o *OrganizationUsageOverview) SetCurrentGpuUsage(v float32) {
	o.CurrentGpuUsage = v
}

// GetTotalGpuQuota returns the TotalGpuQuota field value
func (o *OrganizationUsageOverview) GetTotalGpuQuota() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.TotalGpuQuota
}

// GetTotalGpuQuotaOk returns a tuple with the TotalGpuQuota field value
// and a boolean to check if the value has been set.
func (o *OrganizationUsageOverview) GetTotalGpuQuotaOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalGpuQuota, true
}

// SetTotalGpuQuota sets field value
func (o *OrganizationUsageOverview) SetTotalGpuQuota(v float32) {
	o.TotalGpuQuota = v
}

// GetCurrentBoxUsage returns the CurrentBoxUsage field value
func (o *OrganizationUsageOverview) GetCurrentBoxUsage() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.CurrentBoxUsage
}

// GetCurrentBoxUsageOk returns a tuple with the CurrentBoxUsage field value
// and a boolean to check if the value has been set.
func (o *OrganizationUsageOverview) GetCurrentBoxUsageOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CurrentBoxUsage, true
}

// SetCurrentBoxUsage sets field value
func (o *OrganizationUsageOverview) SetCurrentBoxUsage(v float32) {
	o.CurrentBoxUsage = v
}

// GetMaxConcurrentBoxes returns the MaxConcurrentBoxes field value
func (o *OrganizationUsageOverview) GetMaxConcurrentBoxes() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.MaxConcurrentBoxes
}

// GetMaxConcurrentBoxesOk returns a tuple with the MaxConcurrentBoxes field value
// and a boolean to check if the value has been set.
func (o *OrganizationUsageOverview) GetMaxConcurrentBoxesOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxConcurrentBoxes, true
}

// SetMaxConcurrentBoxes sets field value
func (o *OrganizationUsageOverview) SetMaxConcurrentBoxes(v float32) {
	o.MaxConcurrentBoxes = v
}

func (o OrganizationUsageOverview) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizationUsageOverview) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["currentCpuUsage"] = o.CurrentCpuUsage
	toSerialize["totalCpuQuota"] = o.TotalCpuQuota
	toSerialize["currentMemoryUsage"] = o.CurrentMemoryUsage
	toSerialize["totalMemoryQuota"] = o.TotalMemoryQuota
	toSerialize["currentDiskUsage"] = o.CurrentDiskUsage
	toSerialize["totalDiskQuota"] = o.TotalDiskQuota
	toSerialize["currentGpuUsage"] = o.CurrentGpuUsage
	toSerialize["totalGpuQuota"] = o.TotalGpuQuota
	toSerialize["currentBoxUsage"] = o.CurrentBoxUsage
	toSerialize["maxConcurrentBoxes"] = o.MaxConcurrentBoxes

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *OrganizationUsageOverview) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"currentCpuUsage",
		"totalCpuQuota",
		"currentMemoryUsage",
		"totalMemoryQuota",
		"currentDiskUsage",
		"totalDiskQuota",
		"currentGpuUsage",
		"totalGpuQuota",
		"currentBoxUsage",
		"maxConcurrentBoxes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrganizationUsageOverview := _OrganizationUsageOverview{}

	err = json.Unmarshal(data, &varOrganizationUsageOverview)

	if err != nil {
		return err
	}

	*o = OrganizationUsageOverview(varOrganizationUsageOverview)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "currentCpuUsage")
		delete(additionalProperties, "totalCpuQuota")
		delete(additionalProperties, "currentMemoryUsage")
		delete(additionalProperties, "totalMemoryQuota")
		delete(additionalProperties, "currentDiskUsage")
		delete(additionalProperties, "totalDiskQuota")
		delete(additionalProperties, "currentGpuUsage")
		delete(additionalProperties, "totalGpuQuota")
		delete(additionalProperties, "currentBoxUsage")
		delete(additionalProperties, "maxConcurrentBoxes")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableOrganizationUsageOverview struct {
	value *OrganizationUsageOverview
	isSet bool
}

func (v NullableOrganizationUsageOverview) Get() *OrganizationUsageOverview {
	return v.value
}

func (v *NullableOrganizationUsageOverview) Set(val *OrganizationUsageOverview) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationUsageOverview) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationUsageOverview) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationUsageOverview(val *OrganizationUsageOverview) *NullableOrganizationUsageOverview {
	return &NullableOrganizationUsageOverview{value: val, isSet: true}
}

func (v NullableOrganizationUsageOverview) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationUsageOverview) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


