/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the WalletResponseDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WalletResponseDto{}

// WalletResponseDto struct for WalletResponseDto
type WalletResponseDto struct {
	BalanceCents float32 `json:"balanceCents"`
	OngoingBalanceCents float32 `json:"ongoingBalanceCents"`
	Name string `json:"name"`
	CreditCardConnected bool `json:"creditCardConnected"`
	FreeBalanceCents *float32 `json:"freeBalanceCents,omitempty"`
	PaidBalanceCents *float32 `json:"paidBalanceCents,omitempty"`
	BillingStatus *string `json:"billingStatus,omitempty"`
	HasFailedOrPendingInvoice *bool `json:"hasFailedOrPendingInvoice,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _WalletResponseDto WalletResponseDto

// NewWalletResponseDto instantiates a new WalletResponseDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWalletResponseDto(balanceCents float32, ongoingBalanceCents float32, name string, creditCardConnected bool) *WalletResponseDto {
	this := WalletResponseDto{}
	this.BalanceCents = balanceCents
	this.OngoingBalanceCents = ongoingBalanceCents
	this.Name = name
	this.CreditCardConnected = creditCardConnected
	return &this
}

// NewWalletResponseDtoWithDefaults instantiates a new WalletResponseDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWalletResponseDtoWithDefaults() *WalletResponseDto {
	this := WalletResponseDto{}
	return &this
}

// GetBalanceCents returns the BalanceCents field value
func (o *WalletResponseDto) GetBalanceCents() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.BalanceCents
}

// GetBalanceCentsOk returns a tuple with the BalanceCents field value
// and a boolean to check if the value has been set.
func (o *WalletResponseDto) GetBalanceCentsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BalanceCents, true
}

// SetBalanceCents sets field value
func (o *WalletResponseDto) SetBalanceCents(v float32) {
	o.BalanceCents = v
}

// GetOngoingBalanceCents returns the OngoingBalanceCents field value
func (o *WalletResponseDto) GetOngoingBalanceCents() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.OngoingBalanceCents
}

// GetOngoingBalanceCentsOk returns a tuple with the OngoingBalanceCents field value
// and a boolean to check if the value has been set.
func (o *WalletResponseDto) GetOngoingBalanceCentsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OngoingBalanceCents, true
}

// SetOngoingBalanceCents sets field value
func (o *WalletResponseDto) SetOngoingBalanceCents(v float32) {
	o.OngoingBalanceCents = v
}

// GetName returns the Name field value
func (o *WalletResponseDto) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *WalletResponseDto) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *WalletResponseDto) SetName(v string) {
	o.Name = v
}

// GetCreditCardConnected returns the CreditCardConnected field value
func (o *WalletResponseDto) GetCreditCardConnected() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.CreditCardConnected
}

// GetCreditCardConnectedOk returns a tuple with the CreditCardConnected field value
// and a boolean to check if the value has been set.
func (o *WalletResponseDto) GetCreditCardConnectedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreditCardConnected, true
}

// SetCreditCardConnected sets field value
func (o *WalletResponseDto) SetCreditCardConnected(v bool) {
	o.CreditCardConnected = v
}

// GetFreeBalanceCents returns the FreeBalanceCents field value if set, zero value otherwise.
func (o *WalletResponseDto) GetFreeBalanceCents() float32 {
	if o == nil || IsNil(o.FreeBalanceCents) {
		var ret float32
		return ret
	}
	return *o.FreeBalanceCents
}

// GetFreeBalanceCentsOk returns a tuple with the FreeBalanceCents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WalletResponseDto) GetFreeBalanceCentsOk() (*float32, bool) {
	if o == nil || IsNil(o.FreeBalanceCents) {
		return nil, false
	}
	return o.FreeBalanceCents, true
}

// HasFreeBalanceCents returns a boolean if a field has been set.
func (o *WalletResponseDto) HasFreeBalanceCents() bool {
	if o != nil && !IsNil(o.FreeBalanceCents) {
		return true
	}

	return false
}

// SetFreeBalanceCents gets a reference to the given float32 and assigns it to the FreeBalanceCents field.
func (o *WalletResponseDto) SetFreeBalanceCents(v float32) {
	o.FreeBalanceCents = &v
}

// GetPaidBalanceCents returns the PaidBalanceCents field value if set, zero value otherwise.
func (o *WalletResponseDto) GetPaidBalanceCents() float32 {
	if o == nil || IsNil(o.PaidBalanceCents) {
		var ret float32
		return ret
	}
	return *o.PaidBalanceCents
}

// GetPaidBalanceCentsOk returns a tuple with the PaidBalanceCents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WalletResponseDto) GetPaidBalanceCentsOk() (*float32, bool) {
	if o == nil || IsNil(o.PaidBalanceCents) {
		return nil, false
	}
	return o.PaidBalanceCents, true
}

// HasPaidBalanceCents returns a boolean if a field has been set.
func (o *WalletResponseDto) HasPaidBalanceCents() bool {
	if o != nil && !IsNil(o.PaidBalanceCents) {
		return true
	}

	return false
}

// SetPaidBalanceCents gets a reference to the given float32 and assigns it to the PaidBalanceCents field.
func (o *WalletResponseDto) SetPaidBalanceCents(v float32) {
	o.PaidBalanceCents = &v
}

// GetBillingStatus returns the BillingStatus field value if set, zero value otherwise.
func (o *WalletResponseDto) GetBillingStatus() string {
	if o == nil || IsNil(o.BillingStatus) {
		var ret string
		return ret
	}
	return *o.BillingStatus
}

// GetBillingStatusOk returns a tuple with the BillingStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WalletResponseDto) GetBillingStatusOk() (*string, bool) {
	if o == nil || IsNil(o.BillingStatus) {
		return nil, false
	}
	return o.BillingStatus, true
}

// HasBillingStatus returns a boolean if a field has been set.
func (o *WalletResponseDto) HasBillingStatus() bool {
	if o != nil && !IsNil(o.BillingStatus) {
		return true
	}

	return false
}

// SetBillingStatus gets a reference to the given string and assigns it to the BillingStatus field.
func (o *WalletResponseDto) SetBillingStatus(v string) {
	o.BillingStatus = &v
}

// GetHasFailedOrPendingInvoice returns the HasFailedOrPendingInvoice field value if set, zero value otherwise.
func (o *WalletResponseDto) GetHasFailedOrPendingInvoice() bool {
	if o == nil || IsNil(o.HasFailedOrPendingInvoice) {
		var ret bool
		return ret
	}
	return *o.HasFailedOrPendingInvoice
}

// GetHasFailedOrPendingInvoiceOk returns a tuple with the HasFailedOrPendingInvoice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WalletResponseDto) GetHasFailedOrPendingInvoiceOk() (*bool, bool) {
	if o == nil || IsNil(o.HasFailedOrPendingInvoice) {
		return nil, false
	}
	return o.HasFailedOrPendingInvoice, true
}

// HasHasFailedOrPendingInvoice returns a boolean if a field has been set.
func (o *WalletResponseDto) HasHasFailedOrPendingInvoice() bool {
	if o != nil && !IsNil(o.HasFailedOrPendingInvoice) {
		return true
	}

	return false
}

// SetHasFailedOrPendingInvoice gets a reference to the given bool and assigns it to the HasFailedOrPendingInvoice field.
func (o *WalletResponseDto) SetHasFailedOrPendingInvoice(v bool) {
	o.HasFailedOrPendingInvoice = &v
}

func (o WalletResponseDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WalletResponseDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["balanceCents"] = o.BalanceCents
	toSerialize["ongoingBalanceCents"] = o.OngoingBalanceCents
	toSerialize["name"] = o.Name
	toSerialize["creditCardConnected"] = o.CreditCardConnected
	if !IsNil(o.FreeBalanceCents) {
		toSerialize["freeBalanceCents"] = o.FreeBalanceCents
	}
	if !IsNil(o.PaidBalanceCents) {
		toSerialize["paidBalanceCents"] = o.PaidBalanceCents
	}
	if !IsNil(o.BillingStatus) {
		toSerialize["billingStatus"] = o.BillingStatus
	}
	if !IsNil(o.HasFailedOrPendingInvoice) {
		toSerialize["hasFailedOrPendingInvoice"] = o.HasFailedOrPendingInvoice
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *WalletResponseDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"balanceCents",
		"ongoingBalanceCents",
		"name",
		"creditCardConnected",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWalletResponseDto := _WalletResponseDto{}

	err = json.Unmarshal(data, &varWalletResponseDto)

	if err != nil {
		return err
	}

	*o = WalletResponseDto(varWalletResponseDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "balanceCents")
		delete(additionalProperties, "ongoingBalanceCents")
		delete(additionalProperties, "name")
		delete(additionalProperties, "creditCardConnected")
		delete(additionalProperties, "freeBalanceCents")
		delete(additionalProperties, "paidBalanceCents")
		delete(additionalProperties, "billingStatus")
		delete(additionalProperties, "hasFailedOrPendingInvoice")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableWalletResponseDto struct {
	value *WalletResponseDto
	isSet bool
}

func (v NullableWalletResponseDto) Get() *WalletResponseDto {
	return v.value
}

func (v *NullableWalletResponseDto) Set(val *WalletResponseDto) {
	v.value = val
	v.isSet = true
}

func (v NullableWalletResponseDto) IsSet() bool {
	return v.isSet
}

func (v *NullableWalletResponseDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWalletResponseDto(val *WalletResponseDto) *NullableWalletResponseDto {
	return &NullableWalletResponseDto{value: val, isSet: true}
}

func (v NullableWalletResponseDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWalletResponseDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
