/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the AggregatedUsage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AggregatedUsage{}

// AggregatedUsage struct for AggregatedUsage
type AggregatedUsage struct {
	BoxCount float32 `json:"boxCount"`
	FirstStart *time.Time `json:"firstStart,omitempty"`
	LastEnd *time.Time `json:"lastEnd,omitempty"`
	TotalCPUSeconds float32 `json:"totalCPUSeconds"`
	TotalDiskGBSeconds float32 `json:"totalDiskGBSeconds"`
	TotalGPUSeconds float32 `json:"totalGPUSeconds"`
	// Always 0 for the self-hosted raw ledger. Monetary rating belongs to the external billing service.
	TotalPrice float32 `json:"totalPrice"`
	TotalRAMGBSeconds float32 `json:"totalRAMGBSeconds"`
	AdditionalProperties map[string]interface{}
}

type _AggregatedUsage AggregatedUsage

// NewAggregatedUsage instantiates a new AggregatedUsage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAggregatedUsage(boxCount float32, totalCPUSeconds float32, totalDiskGBSeconds float32, totalGPUSeconds float32, totalPrice float32, totalRAMGBSeconds float32) *AggregatedUsage {
	this := AggregatedUsage{}
	this.BoxCount = boxCount
	this.TotalCPUSeconds = totalCPUSeconds
	this.TotalDiskGBSeconds = totalDiskGBSeconds
	this.TotalGPUSeconds = totalGPUSeconds
	this.TotalPrice = totalPrice
	this.TotalRAMGBSeconds = totalRAMGBSeconds
	return &this
}

// NewAggregatedUsageWithDefaults instantiates a new AggregatedUsage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAggregatedUsageWithDefaults() *AggregatedUsage {
	this := AggregatedUsage{}
	return &this
}

// GetBoxCount returns the BoxCount field value
func (o *AggregatedUsage) GetBoxCount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.BoxCount
}

// GetBoxCountOk returns a tuple with the BoxCount field value
// and a boolean to check if the value has been set.
func (o *AggregatedUsage) GetBoxCountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BoxCount, true
}

// SetBoxCount sets field value
func (o *AggregatedUsage) SetBoxCount(v float32) {
	o.BoxCount = v
}

// GetFirstStart returns the FirstStart field value if set, zero value otherwise.
func (o *AggregatedUsage) GetFirstStart() time.Time {
	if o == nil || IsNil(o.FirstStart) {
		var ret time.Time
		return ret
	}
	return *o.FirstStart
}

// GetFirstStartOk returns a tuple with the FirstStart field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AggregatedUsage) GetFirstStartOk() (*time.Time, bool) {
	if o == nil || IsNil(o.FirstStart) {
		return nil, false
	}
	return o.FirstStart, true
}

// HasFirstStart returns a boolean if a field has been set.
func (o *AggregatedUsage) HasFirstStart() bool {
	if o != nil && !IsNil(o.FirstStart) {
		return true
	}

	return false
}

// SetFirstStart gets a reference to the given time.Time and assigns it to the FirstStart field.
func (o *AggregatedUsage) SetFirstStart(v time.Time) {
	o.FirstStart = &v
}

// GetLastEnd returns the LastEnd field value if set, zero value otherwise.
func (o *AggregatedUsage) GetLastEnd() time.Time {
	if o == nil || IsNil(o.LastEnd) {
		var ret time.Time
		return ret
	}
	return *o.LastEnd
}

// GetLastEndOk returns a tuple with the LastEnd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AggregatedUsage) GetLastEndOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastEnd) {
		return nil, false
	}
	return o.LastEnd, true
}

// HasLastEnd returns a boolean if a field has been set.
func (o *AggregatedUsage) HasLastEnd() bool {
	if o != nil && !IsNil(o.LastEnd) {
		return true
	}

	return false
}

// SetLastEnd gets a reference to the given time.Time and assigns it to the LastEnd field.
func (o *AggregatedUsage) SetLastEnd(v time.Time) {
	o.LastEnd = &v
}

// GetTotalCPUSeconds returns the TotalCPUSeconds field value
func (o *AggregatedUsage) GetTotalCPUSeconds() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.TotalCPUSeconds
}

// GetTotalCPUSecondsOk returns a tuple with the TotalCPUSeconds field value
// and a boolean to check if the value has been set.
func (o *AggregatedUsage) GetTotalCPUSecondsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalCPUSeconds, true
}

// SetTotalCPUSeconds sets field value
func (o *AggregatedUsage) SetTotalCPUSeconds(v float32) {
	o.TotalCPUSeconds = v
}

// GetTotalDiskGBSeconds returns the TotalDiskGBSeconds field value
func (o *AggregatedUsage) GetTotalDiskGBSeconds() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.TotalDiskGBSeconds
}

// GetTotalDiskGBSecondsOk returns a tuple with the TotalDiskGBSeconds field value
// and a boolean to check if the value has been set.
func (o *AggregatedUsage) GetTotalDiskGBSecondsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalDiskGBSeconds, true
}

// SetTotalDiskGBSeconds sets field value
func (o *AggregatedUsage) SetTotalDiskGBSeconds(v float32) {
	o.TotalDiskGBSeconds = v
}

// GetTotalGPUSeconds returns the TotalGPUSeconds field value
func (o *AggregatedUsage) GetTotalGPUSeconds() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.TotalGPUSeconds
}

// GetTotalGPUSecondsOk returns a tuple with the TotalGPUSeconds field value
// and a boolean to check if the value has been set.
func (o *AggregatedUsage) GetTotalGPUSecondsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalGPUSeconds, true
}

// SetTotalGPUSeconds sets field value
func (o *AggregatedUsage) SetTotalGPUSeconds(v float32) {
	o.TotalGPUSeconds = v
}

// GetTotalPrice returns the TotalPrice field value
func (o *AggregatedUsage) GetTotalPrice() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.TotalPrice
}

// GetTotalPriceOk returns a tuple with the TotalPrice field value
// and a boolean to check if the value has been set.
func (o *AggregatedUsage) GetTotalPriceOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalPrice, true
}

// SetTotalPrice sets field value
func (o *AggregatedUsage) SetTotalPrice(v float32) {
	o.TotalPrice = v
}

// GetTotalRAMGBSeconds returns the TotalRAMGBSeconds field value
func (o *AggregatedUsage) GetTotalRAMGBSeconds() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.TotalRAMGBSeconds
}

// GetTotalRAMGBSecondsOk returns a tuple with the TotalRAMGBSeconds field value
// and a boolean to check if the value has been set.
func (o *AggregatedUsage) GetTotalRAMGBSecondsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalRAMGBSeconds, true
}

// SetTotalRAMGBSeconds sets field value
func (o *AggregatedUsage) SetTotalRAMGBSeconds(v float32) {
	o.TotalRAMGBSeconds = v
}

func (o AggregatedUsage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AggregatedUsage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["boxCount"] = o.BoxCount
	if !IsNil(o.FirstStart) {
		toSerialize["firstStart"] = o.FirstStart
	}
	if !IsNil(o.LastEnd) {
		toSerialize["lastEnd"] = o.LastEnd
	}
	toSerialize["totalCPUSeconds"] = o.TotalCPUSeconds
	toSerialize["totalDiskGBSeconds"] = o.TotalDiskGBSeconds
	toSerialize["totalGPUSeconds"] = o.TotalGPUSeconds
	toSerialize["totalPrice"] = o.TotalPrice
	toSerialize["totalRAMGBSeconds"] = o.TotalRAMGBSeconds

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AggregatedUsage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"boxCount",
		"totalCPUSeconds",
		"totalDiskGBSeconds",
		"totalGPUSeconds",
		"totalPrice",
		"totalRAMGBSeconds",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAggregatedUsage := _AggregatedUsage{}

	err = json.Unmarshal(data, &varAggregatedUsage)

	if err != nil {
		return err
	}

	*o = AggregatedUsage(varAggregatedUsage)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "boxCount")
		delete(additionalProperties, "firstStart")
		delete(additionalProperties, "lastEnd")
		delete(additionalProperties, "totalCPUSeconds")
		delete(additionalProperties, "totalDiskGBSeconds")
		delete(additionalProperties, "totalGPUSeconds")
		delete(additionalProperties, "totalPrice")
		delete(additionalProperties, "totalRAMGBSeconds")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAggregatedUsage struct {
	value *AggregatedUsage
	isSet bool
}

func (v NullableAggregatedUsage) Get() *AggregatedUsage {
	return v.value
}

func (v *NullableAggregatedUsage) Set(val *AggregatedUsage) {
	v.value = val
	v.isSet = true
}

func (v NullableAggregatedUsage) IsSet() bool {
	return v.isSet
}

func (v *NullableAggregatedUsage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAggregatedUsage(val *AggregatedUsage) *NullableAggregatedUsage {
	return &NullableAggregatedUsage{value: val, isSet: true}
}

func (v NullableAggregatedUsage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAggregatedUsage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


