/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the RunnerBoxObservation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RunnerBoxObservation{}

// RunnerBoxObservation struct for RunnerBoxObservation
type RunnerBoxObservation struct {
	// Control-plane box ID observed on the runner
	BoxId string `json:"boxId"`
	// Actual box state observed by the runner
	ActualState BoxState `json:"actualState"`
	// Control-plane runtime generation associated with the observed instance. Zero means the runner cannot provide generation evidence.
	RuntimeGeneration int64 `json:"runtimeGeneration"`
	AdditionalProperties map[string]interface{}
}

type _RunnerBoxObservation RunnerBoxObservation

// NewRunnerBoxObservation instantiates a new RunnerBoxObservation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRunnerBoxObservation(boxId string, actualState BoxState, runtimeGeneration int64) *RunnerBoxObservation {
	this := RunnerBoxObservation{}
	this.BoxId = boxId
	this.ActualState = actualState
	this.RuntimeGeneration = runtimeGeneration
	return &this
}

// NewRunnerBoxObservationWithDefaults instantiates a new RunnerBoxObservation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRunnerBoxObservationWithDefaults() *RunnerBoxObservation {
	this := RunnerBoxObservation{}
	return &this
}

// GetBoxId returns the BoxId field value
func (o *RunnerBoxObservation) GetBoxId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BoxId
}

// GetBoxIdOk returns a tuple with the BoxId field value
// and a boolean to check if the value has been set.
func (o *RunnerBoxObservation) GetBoxIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BoxId, true
}

// SetBoxId sets field value
func (o *RunnerBoxObservation) SetBoxId(v string) {
	o.BoxId = v
}

// GetActualState returns the ActualState field value
func (o *RunnerBoxObservation) GetActualState() BoxState {
	if o == nil {
		var ret BoxState
		return ret
	}

	return o.ActualState
}

// GetActualStateOk returns a tuple with the ActualState field value
// and a boolean to check if the value has been set.
func (o *RunnerBoxObservation) GetActualStateOk() (*BoxState, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ActualState, true
}

// SetActualState sets field value
func (o *RunnerBoxObservation) SetActualState(v BoxState) {
	o.ActualState = v
}

// GetRuntimeGeneration returns the RuntimeGeneration field value
func (o *RunnerBoxObservation) GetRuntimeGeneration() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.RuntimeGeneration
}

// GetRuntimeGenerationOk returns a tuple with the RuntimeGeneration field value
// and a boolean to check if the value has been set.
func (o *RunnerBoxObservation) GetRuntimeGenerationOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RuntimeGeneration, true
}

// SetRuntimeGeneration sets field value
func (o *RunnerBoxObservation) SetRuntimeGeneration(v int64) {
	o.RuntimeGeneration = v
}

func (o RunnerBoxObservation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RunnerBoxObservation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["boxId"] = o.BoxId
	toSerialize["actualState"] = o.ActualState
	toSerialize["runtimeGeneration"] = o.RuntimeGeneration

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RunnerBoxObservation) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"boxId",
		"actualState",
		"runtimeGeneration",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRunnerBoxObservation := _RunnerBoxObservation{}

	err = json.Unmarshal(data, &varRunnerBoxObservation)

	if err != nil {
		return err
	}

	*o = RunnerBoxObservation(varRunnerBoxObservation)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "boxId")
		delete(additionalProperties, "actualState")
		delete(additionalProperties, "runtimeGeneration")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRunnerBoxObservation struct {
	value *RunnerBoxObservation
	isSet bool
}

func (v NullableRunnerBoxObservation) Get() *RunnerBoxObservation {
	return v.value
}

func (v *NullableRunnerBoxObservation) Set(val *RunnerBoxObservation) {
	v.value = val
	v.isSet = true
}

func (v NullableRunnerBoxObservation) IsSet() bool {
	return v.isSet
}

func (v *NullableRunnerBoxObservation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRunnerBoxObservation(val *RunnerBoxObservation) *NullableRunnerBoxObservation {
	return &NullableRunnerBoxObservation{value: val, isSet: true}
}

func (v NullableRunnerBoxObservation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRunnerBoxObservation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


