/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the SupportedBoxImage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SupportedBoxImage{}

// SupportedBoxImage struct for SupportedBoxImage
type SupportedBoxImage struct {
	// Stable image option ID shown by the dashboard
	Id string `json:"id"`
	// Display name for the supported image
	Name string `json:"name"`
	// Pinned OCI image reference accepted by box creation
	Ref string `json:"ref"`
	// Whether this image is used when create omits an image
	IsDefault bool `json:"isDefault"`
	AdditionalProperties map[string]interface{}
}

type _SupportedBoxImage SupportedBoxImage

// NewSupportedBoxImage instantiates a new SupportedBoxImage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSupportedBoxImage(id string, name string, ref string, isDefault bool) *SupportedBoxImage {
	this := SupportedBoxImage{}
	this.Id = id
	this.Name = name
	this.Ref = ref
	this.IsDefault = isDefault
	return &this
}

// NewSupportedBoxImageWithDefaults instantiates a new SupportedBoxImage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSupportedBoxImageWithDefaults() *SupportedBoxImage {
	this := SupportedBoxImage{}
	return &this
}

// GetId returns the Id field value
func (o *SupportedBoxImage) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SupportedBoxImage) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SupportedBoxImage) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *SupportedBoxImage) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SupportedBoxImage) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SupportedBoxImage) SetName(v string) {
	o.Name = v
}

// GetRef returns the Ref field value
func (o *SupportedBoxImage) GetRef() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Ref
}

// GetRefOk returns a tuple with the Ref field value
// and a boolean to check if the value has been set.
func (o *SupportedBoxImage) GetRefOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ref, true
}

// SetRef sets field value
func (o *SupportedBoxImage) SetRef(v string) {
	o.Ref = v
}

// GetIsDefault returns the IsDefault field value
func (o *SupportedBoxImage) GetIsDefault() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsDefault
}

// GetIsDefaultOk returns a tuple with the IsDefault field value
// and a boolean to check if the value has been set.
func (o *SupportedBoxImage) GetIsDefaultOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsDefault, true
}

// SetIsDefault sets field value
func (o *SupportedBoxImage) SetIsDefault(v bool) {
	o.IsDefault = v
}

func (o SupportedBoxImage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SupportedBoxImage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["ref"] = o.Ref
	toSerialize["isDefault"] = o.IsDefault

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SupportedBoxImage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"ref",
		"isDefault",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSupportedBoxImage := _SupportedBoxImage{}

	err = json.Unmarshal(data, &varSupportedBoxImage)

	if err != nil {
		return err
	}

	*o = SupportedBoxImage(varSupportedBoxImage)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "ref")
		delete(additionalProperties, "isDefault")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSupportedBoxImage struct {
	value *SupportedBoxImage
	isSet bool
}

func (v NullableSupportedBoxImage) Get() *SupportedBoxImage {
	return v.value
}

func (v *NullableSupportedBoxImage) Set(val *SupportedBoxImage) {
	v.value = val
	v.isSet = true
}

func (v NullableSupportedBoxImage) IsSet() bool {
	return v.isSet
}

func (v *NullableSupportedBoxImage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSupportedBoxImage(val *SupportedBoxImage) *NullableSupportedBoxImage {
	return &NullableSupportedBoxImage{value: val, isSet: true}
}

func (v NullableSupportedBoxImage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSupportedBoxImage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


