/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the UsageChartPoint type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UsageChartPoint{}

// UsageChartPoint struct for UsageChartPoint
type UsageChartPoint struct {
	// Average allocated CPUs in this UTC-day bucket
	Cpu float32 `json:"cpu"`
	// Always 0 for the self-hosted raw ledger. Monetary rating belongs to the external billing service.
	CpuPrice float32 `json:"cpuPrice"`
	// Average allocated disk GB in this UTC-day bucket
	DiskGB float32 `json:"diskGB"`
	// Always 0 for the self-hosted raw ledger. Monetary rating belongs to the external billing service.
	DiskPrice float32 `json:"diskPrice"`
	// Average allocated RAM GB in this UTC-day bucket
	RamGB float32 `json:"ramGB"`
	// Always 0 for the self-hosted raw ledger. Monetary rating belongs to the external billing service.
	RamPrice float32 `json:"ramPrice"`
	// Start of the UTC-day bucket, clipped to the requested range
	Time time.Time `json:"time"`
	AdditionalProperties map[string]interface{}
}

type _UsageChartPoint UsageChartPoint

// NewUsageChartPoint instantiates a new UsageChartPoint object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsageChartPoint(cpu float32, cpuPrice float32, diskGB float32, diskPrice float32, ramGB float32, ramPrice float32, time time.Time) *UsageChartPoint {
	this := UsageChartPoint{}
	this.Cpu = cpu
	this.CpuPrice = cpuPrice
	this.DiskGB = diskGB
	this.DiskPrice = diskPrice
	this.RamGB = ramGB
	this.RamPrice = ramPrice
	this.Time = time
	return &this
}

// NewUsageChartPointWithDefaults instantiates a new UsageChartPoint object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsageChartPointWithDefaults() *UsageChartPoint {
	this := UsageChartPoint{}
	return &this
}

// GetCpu returns the Cpu field value
func (o *UsageChartPoint) GetCpu() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Cpu
}

// GetCpuOk returns a tuple with the Cpu field value
// and a boolean to check if the value has been set.
func (o *UsageChartPoint) GetCpuOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cpu, true
}

// SetCpu sets field value
func (o *UsageChartPoint) SetCpu(v float32) {
	o.Cpu = v
}

// GetCpuPrice returns the CpuPrice field value
func (o *UsageChartPoint) GetCpuPrice() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.CpuPrice
}

// GetCpuPriceOk returns a tuple with the CpuPrice field value
// and a boolean to check if the value has been set.
func (o *UsageChartPoint) GetCpuPriceOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CpuPrice, true
}

// SetCpuPrice sets field value
func (o *UsageChartPoint) SetCpuPrice(v float32) {
	o.CpuPrice = v
}

// GetDiskGB returns the DiskGB field value
func (o *UsageChartPoint) GetDiskGB() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.DiskGB
}

// GetDiskGBOk returns a tuple with the DiskGB field value
// and a boolean to check if the value has been set.
func (o *UsageChartPoint) GetDiskGBOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DiskGB, true
}

// SetDiskGB sets field value
func (o *UsageChartPoint) SetDiskGB(v float32) {
	o.DiskGB = v
}

// GetDiskPrice returns the DiskPrice field value
func (o *UsageChartPoint) GetDiskPrice() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.DiskPrice
}

// GetDiskPriceOk returns a tuple with the DiskPrice field value
// and a boolean to check if the value has been set.
func (o *UsageChartPoint) GetDiskPriceOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DiskPrice, true
}

// SetDiskPrice sets field value
func (o *UsageChartPoint) SetDiskPrice(v float32) {
	o.DiskPrice = v
}

// GetRamGB returns the RamGB field value
func (o *UsageChartPoint) GetRamGB() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.RamGB
}

// GetRamGBOk returns a tuple with the RamGB field value
// and a boolean to check if the value has been set.
func (o *UsageChartPoint) GetRamGBOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RamGB, true
}

// SetRamGB sets field value
func (o *UsageChartPoint) SetRamGB(v float32) {
	o.RamGB = v
}

// GetRamPrice returns the RamPrice field value
func (o *UsageChartPoint) GetRamPrice() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.RamPrice
}

// GetRamPriceOk returns a tuple with the RamPrice field value
// and a boolean to check if the value has been set.
func (o *UsageChartPoint) GetRamPriceOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RamPrice, true
}

// SetRamPrice sets field value
func (o *UsageChartPoint) SetRamPrice(v float32) {
	o.RamPrice = v
}

// GetTime returns the Time field value
func (o *UsageChartPoint) GetTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Time
}

// GetTimeOk returns a tuple with the Time field value
// and a boolean to check if the value has been set.
func (o *UsageChartPoint) GetTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Time, true
}

// SetTime sets field value
func (o *UsageChartPoint) SetTime(v time.Time) {
	o.Time = v
}

func (o UsageChartPoint) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UsageChartPoint) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cpu"] = o.Cpu
	toSerialize["cpuPrice"] = o.CpuPrice
	toSerialize["diskGB"] = o.DiskGB
	toSerialize["diskPrice"] = o.DiskPrice
	toSerialize["ramGB"] = o.RamGB
	toSerialize["ramPrice"] = o.RamPrice
	toSerialize["time"] = o.Time

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UsageChartPoint) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"cpu",
		"cpuPrice",
		"diskGB",
		"diskPrice",
		"ramGB",
		"ramPrice",
		"time",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUsageChartPoint := _UsageChartPoint{}

	err = json.Unmarshal(data, &varUsageChartPoint)

	if err != nil {
		return err
	}

	*o = UsageChartPoint(varUsageChartPoint)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "cpu")
		delete(additionalProperties, "cpuPrice")
		delete(additionalProperties, "diskGB")
		delete(additionalProperties, "diskPrice")
		delete(additionalProperties, "ramGB")
		delete(additionalProperties, "ramPrice")
		delete(additionalProperties, "time")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUsageChartPoint struct {
	value *UsageChartPoint
	isSet bool
}

func (v NullableUsageChartPoint) Get() *UsageChartPoint {
	return v.value
}

func (v *NullableUsageChartPoint) Set(val *UsageChartPoint) {
	v.value = val
	v.isSet = true
}

func (v NullableUsageChartPoint) IsSet() bool {
	return v.isSet
}

func (v *NullableUsageChartPoint) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsageChartPoint(val *UsageChartPoint) *NullableUsageChartPoint {
	return &NullableUsageChartPoint{value: val, isSet: true}
}

func (v NullableUsageChartPoint) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsageChartPoint) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


