/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the BoxAccessGrantCreated type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BoxAccessGrantCreated{}

// BoxAccessGrantCreated struct for BoxAccessGrantCreated
type BoxAccessGrantCreated struct {
	// Unique identifier for the access grant
	Id string `json:"id"`
	// ID of the box this grant is scoped to
	BoxId string `json:"boxId"`
	// Capability scopes granted
	Scopes []string `json:"scopes"`
	// When the grant expires
	ExpiresAt time.Time `json:"expiresAt"`
	// One-time plaintext app key. Not recoverable after this response; store it now.
	AppKey string `json:"appKey"`
	AdditionalProperties map[string]interface{}
}

type _BoxAccessGrantCreated BoxAccessGrantCreated

// NewBoxAccessGrantCreated instantiates a new BoxAccessGrantCreated object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBoxAccessGrantCreated(id string, boxId string, scopes []string, expiresAt time.Time, appKey string) *BoxAccessGrantCreated {
	this := BoxAccessGrantCreated{}
	this.Id = id
	this.BoxId = boxId
	this.Scopes = scopes
	this.ExpiresAt = expiresAt
	this.AppKey = appKey
	return &this
}

// NewBoxAccessGrantCreatedWithDefaults instantiates a new BoxAccessGrantCreated object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBoxAccessGrantCreatedWithDefaults() *BoxAccessGrantCreated {
	this := BoxAccessGrantCreated{}
	return &this
}

// GetId returns the Id field value
func (o *BoxAccessGrantCreated) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *BoxAccessGrantCreated) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *BoxAccessGrantCreated) SetId(v string) {
	o.Id = v
}

// GetBoxId returns the BoxId field value
func (o *BoxAccessGrantCreated) GetBoxId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BoxId
}

// GetBoxIdOk returns a tuple with the BoxId field value
// and a boolean to check if the value has been set.
func (o *BoxAccessGrantCreated) GetBoxIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BoxId, true
}

// SetBoxId sets field value
func (o *BoxAccessGrantCreated) SetBoxId(v string) {
	o.BoxId = v
}

// GetScopes returns the Scopes field value
func (o *BoxAccessGrantCreated) GetScopes() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Scopes
}

// GetScopesOk returns a tuple with the Scopes field value
// and a boolean to check if the value has been set.
func (o *BoxAccessGrantCreated) GetScopesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Scopes, true
}

// SetScopes sets field value
func (o *BoxAccessGrantCreated) SetScopes(v []string) {
	o.Scopes = v
}

// GetExpiresAt returns the ExpiresAt field value
func (o *BoxAccessGrantCreated) GetExpiresAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value
// and a boolean to check if the value has been set.
func (o *BoxAccessGrantCreated) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresAt, true
}

// SetExpiresAt sets field value
func (o *BoxAccessGrantCreated) SetExpiresAt(v time.Time) {
	o.ExpiresAt = v
}

// GetAppKey returns the AppKey field value
func (o *BoxAccessGrantCreated) GetAppKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AppKey
}

// GetAppKeyOk returns a tuple with the AppKey field value
// and a boolean to check if the value has been set.
func (o *BoxAccessGrantCreated) GetAppKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AppKey, true
}

// SetAppKey sets field value
func (o *BoxAccessGrantCreated) SetAppKey(v string) {
	o.AppKey = v
}

func (o BoxAccessGrantCreated) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BoxAccessGrantCreated) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["boxId"] = o.BoxId
	toSerialize["scopes"] = o.Scopes
	toSerialize["expiresAt"] = o.ExpiresAt
	toSerialize["appKey"] = o.AppKey

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BoxAccessGrantCreated) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"boxId",
		"scopes",
		"expiresAt",
		"appKey",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBoxAccessGrantCreated := _BoxAccessGrantCreated{}

	err = json.Unmarshal(data, &varBoxAccessGrantCreated)

	if err != nil {
		return err
	}

	*o = BoxAccessGrantCreated(varBoxAccessGrantCreated)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "boxId")
		delete(additionalProperties, "scopes")
		delete(additionalProperties, "expiresAt")
		delete(additionalProperties, "appKey")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBoxAccessGrantCreated struct {
	value *BoxAccessGrantCreated
	isSet bool
}

func (v NullableBoxAccessGrantCreated) Get() *BoxAccessGrantCreated {
	return v.value
}

func (v *NullableBoxAccessGrantCreated) Set(val *BoxAccessGrantCreated) {
	v.value = val
	v.isSet = true
}

func (v NullableBoxAccessGrantCreated) IsSet() bool {
	return v.isSet
}

func (v *NullableBoxAccessGrantCreated) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBoxAccessGrantCreated(val *BoxAccessGrantCreated) *NullableBoxAccessGrantCreated {
	return &NullableBoxAccessGrantCreated{value: val, isSet: true}
}

func (v NullableBoxAccessGrantCreated) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBoxAccessGrantCreated) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


