/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the TemporarySshCredential type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TemporarySshCredential{}

// TemporarySshCredential struct for TemporarySshCredential
type TemporarySshCredential struct {
	Id string `json:"id"`
	GrantId string `json:"grantId"`
	BoxId string `json:"boxId"`
	PublicKeyFingerprint string `json:"publicKeyFingerprint"`
	Status string `json:"status"`
	ExpiresAt time.Time `json:"expiresAt"`
	CreatedBy string `json:"createdBy"`
	CreatedAt time.Time `json:"createdAt"`
	AdditionalProperties map[string]interface{}
}

type _TemporarySshCredential TemporarySshCredential

// NewTemporarySshCredential instantiates a new TemporarySshCredential object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTemporarySshCredential(id string, grantId string, boxId string, publicKeyFingerprint string, status string, expiresAt time.Time, createdBy string, createdAt time.Time) *TemporarySshCredential {
	this := TemporarySshCredential{}
	this.Id = id
	this.GrantId = grantId
	this.BoxId = boxId
	this.PublicKeyFingerprint = publicKeyFingerprint
	this.Status = status
	this.ExpiresAt = expiresAt
	this.CreatedBy = createdBy
	this.CreatedAt = createdAt
	return &this
}

// NewTemporarySshCredentialWithDefaults instantiates a new TemporarySshCredential object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemporarySshCredentialWithDefaults() *TemporarySshCredential {
	this := TemporarySshCredential{}
	return &this
}

// GetId returns the Id field value
func (o *TemporarySshCredential) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *TemporarySshCredential) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *TemporarySshCredential) SetId(v string) {
	o.Id = v
}

// GetGrantId returns the GrantId field value
func (o *TemporarySshCredential) GetGrantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GrantId
}

// GetGrantIdOk returns a tuple with the GrantId field value
// and a boolean to check if the value has been set.
func (o *TemporarySshCredential) GetGrantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GrantId, true
}

// SetGrantId sets field value
func (o *TemporarySshCredential) SetGrantId(v string) {
	o.GrantId = v
}

// GetBoxId returns the BoxId field value
func (o *TemporarySshCredential) GetBoxId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BoxId
}

// GetBoxIdOk returns a tuple with the BoxId field value
// and a boolean to check if the value has been set.
func (o *TemporarySshCredential) GetBoxIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BoxId, true
}

// SetBoxId sets field value
func (o *TemporarySshCredential) SetBoxId(v string) {
	o.BoxId = v
}

// GetPublicKeyFingerprint returns the PublicKeyFingerprint field value
func (o *TemporarySshCredential) GetPublicKeyFingerprint() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PublicKeyFingerprint
}

// GetPublicKeyFingerprintOk returns a tuple with the PublicKeyFingerprint field value
// and a boolean to check if the value has been set.
func (o *TemporarySshCredential) GetPublicKeyFingerprintOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PublicKeyFingerprint, true
}

// SetPublicKeyFingerprint sets field value
func (o *TemporarySshCredential) SetPublicKeyFingerprint(v string) {
	o.PublicKeyFingerprint = v
}

// GetStatus returns the Status field value
func (o *TemporarySshCredential) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *TemporarySshCredential) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *TemporarySshCredential) SetStatus(v string) {
	o.Status = v
}

// GetExpiresAt returns the ExpiresAt field value
func (o *TemporarySshCredential) GetExpiresAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value
// and a boolean to check if the value has been set.
func (o *TemporarySshCredential) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresAt, true
}

// SetExpiresAt sets field value
func (o *TemporarySshCredential) SetExpiresAt(v time.Time) {
	o.ExpiresAt = v
}

// GetCreatedBy returns the CreatedBy field value
func (o *TemporarySshCredential) GetCreatedBy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedBy
}

// GetCreatedByOk returns a tuple with the CreatedBy field value
// and a boolean to check if the value has been set.
func (o *TemporarySshCredential) GetCreatedByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedBy, true
}

// SetCreatedBy sets field value
func (o *TemporarySshCredential) SetCreatedBy(v string) {
	o.CreatedBy = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *TemporarySshCredential) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *TemporarySshCredential) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *TemporarySshCredential) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

func (o TemporarySshCredential) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TemporarySshCredential) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["grantId"] = o.GrantId
	toSerialize["boxId"] = o.BoxId
	toSerialize["publicKeyFingerprint"] = o.PublicKeyFingerprint
	toSerialize["status"] = o.Status
	toSerialize["expiresAt"] = o.ExpiresAt
	toSerialize["createdBy"] = o.CreatedBy
	toSerialize["createdAt"] = o.CreatedAt

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TemporarySshCredential) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"grantId",
		"boxId",
		"publicKeyFingerprint",
		"status",
		"expiresAt",
		"createdBy",
		"createdAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTemporarySshCredential := _TemporarySshCredential{}

	err = json.Unmarshal(data, &varTemporarySshCredential)

	if err != nil {
		return err
	}

	*o = TemporarySshCredential(varTemporarySshCredential)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "grantId")
		delete(additionalProperties, "boxId")
		delete(additionalProperties, "publicKeyFingerprint")
		delete(additionalProperties, "status")
		delete(additionalProperties, "expiresAt")
		delete(additionalProperties, "createdBy")
		delete(additionalProperties, "createdAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTemporarySshCredential struct {
	value *TemporarySshCredential
	isSet bool
}

func (v NullableTemporarySshCredential) Get() *TemporarySshCredential {
	return v.value
}

func (v *NullableTemporarySshCredential) Set(val *TemporarySshCredential) {
	v.value = val
	v.isSet = true
}

func (v NullableTemporarySshCredential) IsSet() bool {
	return v.isSet
}

func (v *NullableTemporarySshCredential) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemporarySshCredential(val *TemporarySshCredential) *NullableTemporarySshCredential {
	return &NullableTemporarySshCredential{value: val, isSet: true}
}

func (v NullableTemporarySshCredential) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemporarySshCredential) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


