/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the UsagePeriod type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UsagePeriod{}

// UsagePeriod struct for UsagePeriod
type UsagePeriod struct {
	Cpu float32 `json:"cpu"`
	DiskGB float32 `json:"diskGB"`
	EndAt time.Time `json:"endAt"`
	Gpu float32 `json:"gpu"`
	// Always 0 for the self-hosted raw ledger. Monetary rating belongs to the external billing service.
	Price float32 `json:"price"`
	RamGB float32 `json:"ramGB"`
	StartAt time.Time `json:"startAt"`
	AdditionalProperties map[string]interface{}
}

type _UsagePeriod UsagePeriod

// NewUsagePeriod instantiates a new UsagePeriod object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsagePeriod(cpu float32, diskGB float32, endAt time.Time, gpu float32, price float32, ramGB float32, startAt time.Time) *UsagePeriod {
	this := UsagePeriod{}
	this.Cpu = cpu
	this.DiskGB = diskGB
	this.EndAt = endAt
	this.Gpu = gpu
	this.Price = price
	this.RamGB = ramGB
	this.StartAt = startAt
	return &this
}

// NewUsagePeriodWithDefaults instantiates a new UsagePeriod object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsagePeriodWithDefaults() *UsagePeriod {
	this := UsagePeriod{}
	return &this
}

// GetCpu returns the Cpu field value
func (o *UsagePeriod) GetCpu() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Cpu
}

// GetCpuOk returns a tuple with the Cpu field value
// and a boolean to check if the value has been set.
func (o *UsagePeriod) GetCpuOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cpu, true
}

// SetCpu sets field value
func (o *UsagePeriod) SetCpu(v float32) {
	o.Cpu = v
}

// GetDiskGB returns the DiskGB field value
func (o *UsagePeriod) GetDiskGB() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.DiskGB
}

// GetDiskGBOk returns a tuple with the DiskGB field value
// and a boolean to check if the value has been set.
func (o *UsagePeriod) GetDiskGBOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DiskGB, true
}

// SetDiskGB sets field value
func (o *UsagePeriod) SetDiskGB(v float32) {
	o.DiskGB = v
}

// GetEndAt returns the EndAt field value
func (o *UsagePeriod) GetEndAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.EndAt
}

// GetEndAtOk returns a tuple with the EndAt field value
// and a boolean to check if the value has been set.
func (o *UsagePeriod) GetEndAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndAt, true
}

// SetEndAt sets field value
func (o *UsagePeriod) SetEndAt(v time.Time) {
	o.EndAt = v
}

// GetGpu returns the Gpu field value
func (o *UsagePeriod) GetGpu() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Gpu
}

// GetGpuOk returns a tuple with the Gpu field value
// and a boolean to check if the value has been set.
func (o *UsagePeriod) GetGpuOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Gpu, true
}

// SetGpu sets field value
func (o *UsagePeriod) SetGpu(v float32) {
	o.Gpu = v
}

// GetPrice returns the Price field value
func (o *UsagePeriod) GetPrice() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Price
}

// GetPriceOk returns a tuple with the Price field value
// and a boolean to check if the value has been set.
func (o *UsagePeriod) GetPriceOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Price, true
}

// SetPrice sets field value
func (o *UsagePeriod) SetPrice(v float32) {
	o.Price = v
}

// GetRamGB returns the RamGB field value
func (o *UsagePeriod) GetRamGB() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.RamGB
}

// GetRamGBOk returns a tuple with the RamGB field value
// and a boolean to check if the value has been set.
func (o *UsagePeriod) GetRamGBOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RamGB, true
}

// SetRamGB sets field value
func (o *UsagePeriod) SetRamGB(v float32) {
	o.RamGB = v
}

// GetStartAt returns the StartAt field value
func (o *UsagePeriod) GetStartAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.StartAt
}

// GetStartAtOk returns a tuple with the StartAt field value
// and a boolean to check if the value has been set.
func (o *UsagePeriod) GetStartAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartAt, true
}

// SetStartAt sets field value
func (o *UsagePeriod) SetStartAt(v time.Time) {
	o.StartAt = v
}

func (o UsagePeriod) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UsagePeriod) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cpu"] = o.Cpu
	toSerialize["diskGB"] = o.DiskGB
	toSerialize["endAt"] = o.EndAt
	toSerialize["gpu"] = o.Gpu
	toSerialize["price"] = o.Price
	toSerialize["ramGB"] = o.RamGB
	toSerialize["startAt"] = o.StartAt

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UsagePeriod) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"cpu",
		"diskGB",
		"endAt",
		"gpu",
		"price",
		"ramGB",
		"startAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUsagePeriod := _UsagePeriod{}

	err = json.Unmarshal(data, &varUsagePeriod)

	if err != nil {
		return err
	}

	*o = UsagePeriod(varUsagePeriod)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "cpu")
		delete(additionalProperties, "diskGB")
		delete(additionalProperties, "endAt")
		delete(additionalProperties, "gpu")
		delete(additionalProperties, "price")
		delete(additionalProperties, "ramGB")
		delete(additionalProperties, "startAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUsagePeriod struct {
	value *UsagePeriod
	isSet bool
}

func (v NullableUsagePeriod) Get() *UsagePeriod {
	return v.value
}

func (v *NullableUsagePeriod) Set(val *UsagePeriod) {
	v.value = val
	v.isSet = true
}

func (v NullableUsagePeriod) IsSet() bool {
	return v.isSet
}

func (v *NullableUsagePeriod) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsagePeriod(val *UsagePeriod) *NullableUsagePeriod {
	return &NullableUsagePeriod{value: val, isSet: true}
}

func (v NullableUsagePeriod) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsagePeriod) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


