/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the TopUpRequestDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TopUpRequestDto{}

// TopUpRequestDto struct for TopUpRequestDto
type TopUpRequestDto struct {
	// Amount to top up, in cents
	AmountCents float32 `json:"amountCents"`
	AdditionalProperties map[string]interface{}
}

type _TopUpRequestDto TopUpRequestDto

// NewTopUpRequestDto instantiates a new TopUpRequestDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTopUpRequestDto(amountCents float32) *TopUpRequestDto {
	this := TopUpRequestDto{}
	this.AmountCents = amountCents
	return &this
}

// NewTopUpRequestDtoWithDefaults instantiates a new TopUpRequestDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTopUpRequestDtoWithDefaults() *TopUpRequestDto {
	this := TopUpRequestDto{}
	return &this
}

// GetAmountCents returns the AmountCents field value
func (o *TopUpRequestDto) GetAmountCents() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.AmountCents
}

// GetAmountCentsOk returns a tuple with the AmountCents field value
// and a boolean to check if the value has been set.
func (o *TopUpRequestDto) GetAmountCentsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AmountCents, true
}

// SetAmountCents sets field value
func (o *TopUpRequestDto) SetAmountCents(v float32) {
	o.AmountCents = v
}

func (o TopUpRequestDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TopUpRequestDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["amountCents"] = o.AmountCents

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TopUpRequestDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"amountCents",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTopUpRequestDto := _TopUpRequestDto{}

	err = json.Unmarshal(data, &varTopUpRequestDto)

	if err != nil {
		return err
	}

	*o = TopUpRequestDto(varTopUpRequestDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "amountCents")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTopUpRequestDto struct {
	value *TopUpRequestDto
	isSet bool
}

func (v NullableTopUpRequestDto) Get() *TopUpRequestDto {
	return v.value
}

func (v *NullableTopUpRequestDto) Set(val *TopUpRequestDto) {
	v.value = val
	v.isSet = true
}

func (v NullableTopUpRequestDto) IsSet() bool {
	return v.isSet
}

func (v *NullableTopUpRequestDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTopUpRequestDto(val *TopUpRequestDto) *NullableTopUpRequestDto {
	return &NullableTopUpRequestDto{value: val, isSet: true}
}

func (v NullableTopUpRequestDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTopUpRequestDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
